### ISSUE TITLE
[Bug]: Ubuntu/Windows OBS on Windows show me Black Screen

### ISSUE THREAD

**Issue by imCruxi** [DistroAV/DistroAV#1021]
### Operating System Version

Windows 10 & Ubuntu 24.04 LTS

### CPU

Ryzen 5 3600

### GPU

RTX 3060ti EVGA

### OBS Version

30.1.2

### OBS Installation Method

.exe & .apt

### OBS-NDI Version

NDI SDK WIN64 6.0.1.0 & NDI SDK LINUX 5.6.1

### OBS-NDI Installation Method

.exe & .apt

### OBS Log [URL]

https://obsproject.com/logs/YPXOMBQaBul4n2Hf

### NDI Version

6.0.1.0

### Describe the bug

I have set up the NDI output of my OBS Linux to capture it with OBS Windows. On Windows, the Linux output can be recognized, but when trying to load it as a source, it remains black. I researched about https://github.com/obs-ndi/obs-ndi/wiki/2.-Troubleshooting#troubleshooting 

I have the network in private
I have firewall exception for OBS and NDI
I TRY turned off my firewall (nothing happen)

PS: if i set up the NDI Output in OBS Windows, Linux can recognized and show the screen.

### Screenshots

Windows 10:
![image](https://github.com/obs-ndi/obs-ndi/assets/99058402/c879a518-7584-4ab0-8e7a-916db776270a)

Ubuntu:
![Captura_desde_2024-05-13_21-12-19](https://github.com/obs-ndi/obs-ndi/assets/99058402/bb610309-5c1b-4601-9cd7-11d37033015d)

**Comment by Trouffman** [comment]
Closing as this is an issue on an older version.
Please update to the latest version of the DistroAV plugin.
