### ISSUE TITLE
[Bug]: NDI not providing sources

### ISSUE THREAD

**Issue by kori-time** [DistroAV/DistroAV#1024]
### Operating System Version

Windows 11 and Arch Linux

### CPU

ryzen 7 5700x

### GPU

rtx 3080 and rx 7800 xt

### NDI Devices

vseeface

### OBS Version

30.1.2  win11 and 30.1.2-1 arch linux

### OBS Installation Method

exe and yay

### OBS-NDI Version

4.13.2 win11 and 4.13.2-1 arch linux

### OBS-NDI Installation Method

exe and octopi

### OBS Log [URL]

(https://obsproject.com/logs/APMQPmramnp96olR) Win11 (https://obsproject.com/logs/D7ee10wbDKOcyWsl) Arch Linux

### NDI Version

4.13.2 win11 and 4.13.2-1 arch linux

### Describe the bug

I have this install on my win 11 vm to pass obs thru to the host system, and it wont show up in yes i try the drop down noting, please help
![image](https://github.com/obs-ndi/obs-ndi/assets/8308186/c01fddf4-d989-4526-a2c5-a2e2bfcdceb0)

### Steps to reproduce the problem

I uninstall reinstall remove everything still nothing, reinstall both os, same issue, i even reinstall the ndi software that make it work.

**Comment by RayneYoruka** [comment]
Firewall? https://github.com/obs-ndi/obs-ndi/wiki/2.-Troubleshooting

**Comment by korivirtual** [comment]
Not a firewall issue, the arch linux host system firewall disable, and the windows 11 pc firewall is disable

**Comment by RayneYoruka** [comment]
Then it's most likely in your network

**Comment by djungowski** [comment]
Start OBS as Administrator on both machines, then it works

**Comment by korivirtual** [comment]
The main system is Linux and the virtual system is windows the obs does run as admin and obs on Linux run as it should

**Comment by RayneYoruka** [comment]
Make sure all the ports are working, if it still does not work you might need to run the discovery on the win2 machine.

https://ndi.video/wp-content/uploads/2023/09/NDI-5.6-White-Paper-2023.pdf

**Comment by korivirtual** [comment]
I guess i will be happy to help
