### ISSUE TITLE
[Bug]: NDI Runtime not found - pop OS install script

### ISSUE THREAD

**Issue by khimoc97** [DistroAV/DistroAV#1038]
### Operating System Version

Pop!_OS 22.04 LTS

### OBS Version

30.1.2

### OBS Installation Method

PPA

### OBS-NDI Version

4.13.2

### OBS-NDI Installation Method

deb

### [Extra] Installation Steps

Follow the guide
https://github.com/DistroAV/DistroAV/wiki/1.-Installation

And also from
https://github.com/DistroAV/DistroAV/issues/1011

### NDI Version

6

### Describe the bug

Not sure am I doing anything wrong or not but my Obs keep pop the error like this issue (https://github.com/DistroAV/DistroAV/issues/1011) even when I already perform the command below
sudo bash ./libndi-get.sh install

**Comment by RayneYoruka** [comment]
It's been fixed on the dev branch.. https://github.com/DistroAV/DistroAV/blob/develop/CI/libndi-get.sh

Download it to your home then:
chmod +x libndi-get.sh  
sudo ./libndi-get.sh install

Feel free to report issuess at https://github.com/DistroAV/DistroAV/issues/949

**Comment by cue108** [comment]
> It's been fixed on the dev branch.. https://github.com/DistroAV/DistroAV/blob/develop/CI/libndi-get.sh
> 
> Download it to your home then: chmod +x libndi-get.sh sudo ./libndi-get.sh install
> 
> Feel free to report issuess at #949

The script is still wrong as the last ln statement is wrong.
I made a PR https://github.com/DistroAV/DistroAV/pull/1040
