### ISSUE TITLE
[Bug]: NDI Stutter on OBS but not studio monitor

### ISSUE THREAD

**Issue by jahaddow** [DistroAV/DistroAV#1053]
### Operating System Version

Windows 11

### CPU

AMD 7800X3D

### GPU

Nvidia 4070 Super

### NDI Devices

Kiloview U40 & 3 x Zowiebox NDI HX1/2/3 Encoders

### OBS Version

30.2.2

### OBS Installation Method

.exe

### OBS-NDI Version

4.14.0

### OBS-NDI Installation Method

.exe

### NDI Version

6.0.1

### Describe the bug

All NDI sources micro-stuttering every second or 2 on Windows machine with high specs. When I use the exact same sources using RTSP or SRT the stutter does not occur. The result seems to be the same no matter the frame rate. Currently running 59.94 out of the cameras and a 60fps canvas on OBS. (59.94 canvas is worse). Screen refresh rate doesnt help, I have been using both 60 & 120hz to no avail. 
I have tried a number of different OBS and obs ndi versions and even reinstalled windows with no difference in performance. I am also getting the exact same result on a different pc with worse specs.

**Comment by Trouffman** [comment]
Can you provide a bit more data on your sources ?

Does that ALSO appear when the source comes from the same machine or just when it's from the kiloview/ ZowieBox? (trying to target this to local or network impact).

How high are you CPU usage  on that machine?

Also please check the incoming feed with the NDI analysis Tool : https://ndi.video/tools/ndi-analysis/
(theses devices should be NDI 5 since at least mid-2022 :D - just checking here.)

**Comment by jahaddow** [comment]
Sure. It happens when I use NDI Bridge to transcode it locally and bring it into OBS as well. Important to note that the issue does not occur on my M1 Max Mac on the same network, using OBS NDI plugin and even the same Network NIC.

The Zowiebox encoders can do HX1/2/3 1080p60 or 4k30. I have tried both resolutions and all HX versions with no difference in performance. The encoders also output an RTSP feed alongside NDI and this feed does not have any issues in OBS, nor does SRT. I have tried both H264 and H265 as well. NDI Studio on the windows machine also works well.

CPU usage is very low <10%. Have also tried NDI Analysis and can't see any issues.

**Comment by jahaddow** [comment]
I will try Windows 10 and report back.

**Comment by ohmywyattkane** [comment]
One of our PCs started doing the NDI obs stuttering today.
The feed was fine in Studio Monitor, but it was like a slide show in OBS. 

These are the steps I did and now it seems to be working.
admin powershell "sfc/ scannow"
2024-07 Cumulative Update Preview for Windows 11 Version 23H2 for x64-based Systems (KB5040527)
Uninstalled OBS-NDI
Uninstalled OBS (keeping settings) & all other plugins
Installed OBS & all other plugins
Installed OBS NDI(DistroAV) 4.14
Reinstalled NDI 6 + Tools 6.0.1
Rebooted
I am not sure which one of these things fixed it. But it stopped doing it for now.

**Comment by Trouffman** [comment]
Glad the clean uninstall + reinstall seems to have fixed it. Will close this, you can reopen if that appears again.

**Comment by jahaddow** [comment]
Didn't change anything for me, nor did Windows 10. We've had to ditch NDI HX and now use the RTSP outputs from the encoders in the same codec/bitrate with no issues.
