### ISSUE TITLE
[Bug]: Installation of NDI SDK in Ubuntu fails to register with DistroAV

### ISSUE THREAD

**Issue by D337z** [DistroAV/DistroAV#1059]
### Operating System Version

Ubuntu 24.04 LTS

### CPU

Intel i7 5820K

### GPU

GTX980

### OBS Version

30.0.2.1-3build1 (64-bit)

### OBS Installation Method

apt-get

### OBS-NDI Version

4.14.0

### OBS-NDI Installation Method

dpkg (debian)

### [Extra] Installation Steps

Installed DistroAV via sudo dpkg command in terminal, installed the SDK via the link in the plugin via terminal under sudo.  OBS NDI plugin does not find SDK.  Same steps produced a working NDI plugin under Arch Linux on Steam Deck, but not under Ubuntu on PC.

### OBS Log [URL]

https://obsproject.com/logs/n6nG5xme7r5fX6pZ

### NDI Version

Unknown

### Describe the bug

NDI SDK fails to register as installed when loading OBS. The plugin continues to ask me to install via the link. I've attempted multiple times to no avail even though the installation completes successfully.

**Comment by paulpv** [comment]
```
02:54:28.850: [obs-ndi] obs_module_load: you can haz obs-ndi (Version 4.14.0)
02:54:28.850: [obs-ndi] obs_module_load: Qt Version: 6.4.2 (runtime), 6.2.4 (compiled)
02:54:28.850: [obs-ndi] load_ndilib: Trying '/usr/lib/libndi.so.5'
02:54:28.850: [obs-ndi] load_ndilib: Trying '/usr/local/lib/libndi.so.5'
02:54:28.850: [obs-ndi] load_ndilib: ERROR: Can't find the NDI library
02:54:28.850: [obs-ndi] obs_module_load: ERROR - load_ndilib() failed; message=NDI™ Runtime not found.<br><br>Download the installer here:<br><a href="https://distroav.org/ndi/redist-linux">https://distroav.org/ndi/redist-linux</a>
02:54:28.850: Failed to initialize module 'obs-ndi.so'
```

How did you install NDI SDK?

Run `ln -la /usr/lib/libndi*` and `ln -la /usr/local/lib/libndi*`

**Comment by D337z** [comment]
I'm not sure what you're trying to have me do, but -la is an incorrect
operation for ln.  That may be the issue.

**Comment by paulpv** [comment]
> From what I can tell, you mean for me to run ls to list files. THAT I can do.

Yeah, I meant ls.
Sorry.

**Comment by D337z** [comment]
No worries.  Once I linked the non-local files, the DistroAV plug-in began
working properly.  The issue was in the NDI SDK sh file.  If run with sudo,
as many people might, it looks in the incorrect location (local/lib) to
attempt to symbolically link the libndi.so.6 file to the version 5 for
compatibility.

**Comment by paulpv** [comment]
DistroAV 6.0 alpha/beta is available at https://github.com/DistroAV/DistroAV/actions/runs/10224340836 to try.
Should not require any symlink hack.
