### ISSUE TITLE
[Problem]: NDI Runtime not found even after running redist-linux and installing ndi-sdk-bin downgrading the ndi-sdk 5.6.1 works but not 6.0.1

### ISSUE THREAD

**Issue by OzzyHelix** [DistroAV/DistroAV#1063]
### Operating System Version

Arch Linux

### CPU

Ryzen 9 7900X3D

### GPU

AMD RX 7800 XT, RTX 3060

### NDI Devices

HOST Computer

### OBS Version

30.2.2

### OBS Installation Method

AUR

### OBS-NDI Version

4.14.1

### OBS-NDI Installation Method

ndi-sdk-bin AUR Package

### [Extra] Installation Steps

I modified the obs-ndi-bin package to install the 4.14.1 deb package using the PKGBUILD script

### OBS Log [URL]

https://obsproject.com/logs/v48gJ89OCBJPmpvP

### NDI Version

6.0.1

### Describe the bug

NDI Runtime not found even after running redist-linux and installing ndi-sdk-bin downgrading the ndi-sdk  5.6.1 works but not 6.0.1

### Steps to reproduce the problem

install obs-studio
install obs-ndi and ndi-sdk from the aur 
and it will not be able to detect the NDI runtime

### Expected behavior

it detects the NDI runtime 

### Screenshots

![image](https://github.com/user-attachments/assets/bde2f9d6-ba14-45be-b018-03843cbe58a9)

### Additional context

this might not be a bug however I reported the issue to the maintainer of the obs-ndi-bin aur package and downgrading the ndi-sdk  5.6.1 works but not 6.0.1. I have an AMD card but a VFIO GPU passthrough with a RTX 3060 and I have been using obs-ndi with that Windows VM for using NVENC for encoding

**Comment by paulpv** [comment]
Duplicate of https://github.com/DistroAV/DistroAV/issues/1059

```
17:08:20.694: [obs-ndi] obs_module_load: you can haz obs-ndi (Version 4.14.1)
17:08:20.694: [obs-ndi] obs_module_load: Qt Version: 6.7.2 (runtime), 6.2.4 (compiled)
17:08:20.694: [obs-ndi] load_ndilib: Trying '/usr/lib/libndi.so.5'
17:08:20.694: [obs-ndi] load_ndilib: Trying '/usr/local/lib/libndi.so.5'
17:08:20.694: [obs-ndi] load_ndilib: ERROR: Can't find the NDI library
17:08:20.694: [obs-ndi] obs_module_load: ERROR - load_ndilib() failed; message=NDI™ Runtime not found.<br><br>Download the installer here:<br><a href="https://distroav.org/ndi/redist-linux">https://distroav.org/ndi/redist-linux</a>
```

Run `ls -la /usr/lib/libndi*` and `ls -la /usr/local/lib/libndi*`

@Trouffman Perhaps the script is buggy (I get those `ln -s src dest` args reversed in my head all of the time and usually have to triple check).

**Comment by paulpv** [comment]
DistroAV 6.0 alpha/beta is available at https://github.com/DistroAV/DistroAV/actions/runs/10224340836 to try.
Should not require any symlink hack.

**Comment by OzzyHelix** [comment]
I'm ok with downgrading ndi-sdk 5 and waiting for this to be fixed I can't really install a deb package that easily on Arch Linux

**Comment by OzzyHelix** [comment]
also my Virtual Machine is running Windows so I would need a Windows build of DistroAV so this would have to wait for that

**Comment by RayneYoruka** [comment]
The artifacts on the above [link](https://github.com/DistroAV/DistroAV/actions/runs/10231355580) are .zip files. You can install Windows already. The Ubuntu .deb is also there. Unless you want to install from source

**Comment by OzzyHelix** [comment]
DistroAV 6 is going to fix this installing it did fix it I found a way to install the deb file on Arch and it worked thanks
