### ISSUE TITLE
Lag & freezing NDI 

### ISSUE THREAD

**Issue by Qmajorbeatz** [DistroAV/DistroAV#1068]
hello I am having an issue with NDI, the previous versions had no issues but now it does this lagging and freezing on the laptop that is receiving they are both connected via ethernet/ teleport "an NDI kinda fork" I have no issues plus I have pretty fast internet not sure what the issue is. NDI is updated on both firewalls has been config and everything

**Comment by Keduber** [comment]
Lags audio not working broken ndi
