### ISSUE TITLE
NDI VM drops to 15 FPS

### ISSUE THREAD

**Issue by Nexow91** [DistroAV/DistroAV#1085]
Hello everyone, after I have not found a solution to my problem, I hope one of you can help me or know some advice. 

I am using NDI via a Windows 10 VM (Proxmox Hypervisor). 
4 cores
4 GB RAM 
vgpu 1660 Super 2GB VRAM 
The VM runs on NVMes

Even without a connection to the source computer, the FPS drops to 15 FPS after approx. 20 minutes and remains there constantly. When I restart the VM, I have 60 FPS again for 20 minutes and then it goes back to 15 FPS. 
I don't see any utilisation in the task manager and increasing the VM resources to 32GB Ram + 6GB Vram GPU and 8 cores has shown no improvement. 

Apparently I'm not the only one with a similar problem. 

[https://www.reddit.com/r/obs/comments/rmjkpc/the_obsndi_capture_suddenly_goes_from_60fps_to/](url)

As I said, there is still no connection to the source computer, so I rule out network-related (lack of packets) or other problems. 

If anyone knows anything, I would be grateful for any advice. 

![image](https://github.com/user-attachments/assets/2b3ad7e2-0649-4a20-bf76-65392a09805d)

**Comment by Nexow91** [comment]
??

**Comment by RayneYoruka** [comment]
I test in proxmox with Linux VM's and I havent seen this behaviour, are you passing the whole gpu or just virtualising it?

**Comment by Nexow91** [comment]
Hello and thx for answer.
Ich hab virtualising my gtx 1660 super.

**Comment by RayneYoruka** [comment]
Are you doing something like this? https://pve.proxmox.com/wiki/PCI_Passthrough

**Comment by Nexow91** [comment]
vGPU unlock and then pathtrough to vm

https://gitlab.com/polloloco/vgpu-proxmox

**Comment by RayneYoruka** [comment]
Does this happen with obs without DistroAV as well?

**Comment by Nexow91** [comment]
Oh right, I could still test that. I'll do it tomorrow, I'll let you know, it's 22:41 at night here. I'll let you know as soon as I know more.

Thanks for the help so far. 
In Linux it would be interesting to know if this also occurs with a normal pathtrough.

**Comment by Nexow91** [comment]
Hi sry for the late message so I could test it. 
I have removed OBS NDI from the Windows PC and the FPS drops after some time to 15 FPS so it's not because of the Github repo then I guess I have to keep looking. 

Thanks for everything though.

**Comment by Trouffman** [comment]
Thank you for testing & checking. We will close this issue as it's not linked to the plugin. If you ever find the solution. Please share it back here for anyone ending here from search engine.
