### ISSUE TITLE
[Bug]: NDI™ Runtime not found.

### ISSUE THREAD

**Issue by p34t1k** [DistroAV/DistroAV#1087]
### Operating System Version

NAME="Kali GNU/Linux" VERSION_ID="2024.3" VERSION="2024.3" VERSION_CODENAME=kali-rolling ID=kali ID_LIKE=debian

### CPU

CPU: Intel i7-8565U (8) @ 4.600GHz 

### GPU

GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620] ,GPU: AMD Radeon 520 Mobile 

### NDI Devices

.

### OBS Version

30.1.2.1-1

### OBS Installation Method

deb , sh  and snap all have issue

### DistroAV Version

obs-ndi-4.14.1-x86_64-linux-gnu

### DistroAV Installation Method

sh

### [Extra] Installation Steps

.

### OBS Log [URL]

https://obsproject.com/logs/3Hj7shiUPOlVRJe1

### NDI Version

NDI 2024-05-06 r139791 v6.0.1

### Describe the bug

.

### Expected behavior

.

### Screenshots

![image](https://github.com/user-attachments/assets/42b3acf2-d1bd-4dce-a1ad-9cffc766f446)

### Additional context

.

**Comment by Trouffman** [comment]
Please follow the installation steps in the Wiki : https://github.com/DistroAV/DistroAV/wiki/1.-Installation#linux

As you are using NDI SDK v6 but plugin is still V4 you need to add the symlink.

This is already solved in V6 (coming soon)
