### ISSUE TITLE
OBS NDI Install Debian 12

### ISSUE THREAD

**Issue by Nexow91** [DistroAV/DistroAV#1089]
Hello everyone, 

I am new to OBS-NDI using Linux. 
I have been trying to install it several times now, but unfortunately it is not possible to run the ./libndi-get.sh script. 
I have installed the SDK and therefore the NDI runtime should have been installed. 

Here are my instructions for the installation. 

NDI SDK (Runtime) Installation:

- wget https://downloads.ndi.tv/SDK/NDI_SDK_Linux/Install_NDI_SDK_v6_Linux.tar.gz
- tar -xvzf Install_NDI_SDK_v6_Linux.tar.gz
- sudo ./Install_NDI_SDK_v6_Linux.sh

LibNDI installation:

- wget https://github.com/DistroAV/DistroAV/blob/master/CI/libndi-get.sh
- chmod +x libndi-get.sh
- sudo ./libndi-get.sh

**Here it already failed at script line 8.** 

![image](https://github.com/user-attachments/assets/dcfe43ce-14be-4e21-8571-8ecf38f084c9)
![image](https://github.com/user-attachments/assets/f1e659da-c71e-46f7-8fd3-9cba02b9adb5)

sudo ln -s /usr/local/lib/libndi.so.6 /usr/local/lib/libndi.so.5

- Additional packages for NDI:
- sudo apt install avahi-daemon ffmpeg
- sudo systemctl enable avahi-daemon
- sudo systemctl start avahi-daemon

Open the required ports in the firewall:

- sudo ufw allow 5353/udp
- sudo ufw allow 5959:5969/tcp
- sudo ufw allow 5959:5969/udp
- sudo ufw allow 6960:6970/tcp
- sudo ufw allow 6960:6970/udp
- sudo ufw allow 7960:7970/tcp
- sudo ufw allow 7960:7970/udp
- sudo ufw allow 5960/tcp

**OBS-NDI Plugin (DistroAV) Installation:**

- sudo dpkg -i [obs-ndi-package-file].deb

**In case of problems, create symbolic links:**

- sudo ln -s /usr/lib/x86_64-linux-gnu/obs-plugins/obs-ndi.so /usr/local/lib/obs-plugins/obs-ndi.so
- sudo ln -s /usr/share/obs/obs-plugins/obs-ndi/ /usr/local/share/obs/obs-plugins/obs-ndi

Previously I had tried this instruction but unfortunately it did not work. OBS could not be started after the installation of NDI.

https://interfacinglinux.com/2024/08/15/ndi-6-on-linux-with-obs/

If I have done something wrong, please accept my apologies. My goal is to use OBS-NDI on a VM in Proxmox using vGPU of a GTX 1660 Super which is recognised as RTX 6000 instance. 
In Windows I could already test this, but after 20 minutes the FPS suddenly dropped to a constant 15 FPS, so now the attempt in Linux but I lack the necessary knowledge why it doesn't work. 

If anyone knows anything, thank you in advance. 

PS: According to instructions 
https://interfacinglinux.com/2024/08/15/ndi-6-on-linux-with-obs/
but then OBS no longer starts as can be seen on the screen. 

it then simply crashes or disappears, even a reboot did not help. 

It must be possible to get OBS + OBS-NDI to run.

![image](https://github.com/user-attachments/assets/bce2d468-190d-434c-a1e4-258faa97421f)

Translated with DeepL.com (free version)

**Comment by Nexow91** [comment]
??

**Comment by Trouffman** [comment]
For installation on supported systems, please follow the installation step in the wiki.
