### ISSUE TITLE
[Bug]: NDI download site not reachable

### ISSUE THREAD

**Issue by Godfdr** [DistroAV/DistroAV#1091]
### Operating System Version

MacOS Monterey

### CPU

MacOS

### OBS Version

30.1.2

### OBS Installation Method

.dmg

### DistroAV Version

4.14

### DistroAV Installation Method

github

### NDI Version

NDI 4.14

### Describe the bug

When i click the download link on the github page it does not load/start the download,  it rather shows "site not reachable"

### Expected behavior

To open the download page and start the download

**Comment by Godfdr** [comment]
When i click the download link on the github page it does not load/start the download, it rather shows "site not reachable"

**Comment by Trouffman** [comment]
Tested the link to download the NDI Library for MACOS > it works.

NDI.link is not using https and this can be blocked in some systems. (NDI has been informed of this already)
