### ISSUE TITLE
[Bug]: NDI not working

### ISSUE THREAD

**Issue by Scoprionnn** [DistroAV/DistroAV#1093]
### Operating System Version

Mac Apple M2 Pro - macOS Sonoma V14.6.1

### CPU

M2 Pro

### OBS Version

30.2.3

### OBS Installation Method

pkg

### DistroAV Version

4.14.1

### DistroAV Installation Method

pkg

### NDI Version

obs-ndi-4.14.1-macos-universal

### Describe the bug

Hi, the plugin does not start and gives an error when opening OBS.

### Screenshots

<img width="436" alt="Screenshot 2024-09-12 alle 08 38 59" src="https://github.com/user-attachments/assets/1cb0abad-d71c-4ff6-85dc-2de2a1d1a13d">

**Comment by RayneYoruka** [comment]
> Did you install ndi runtime?

I don't think the error window is clear enough.. I doubt its a bug

https://github.com/DistroAV/DistroAV/wiki/1.-Installation
