### ISSUE TITLE
[Bug]: BLACK SCREEN ON SONOMA

### ISSUE THREAD

**Issue by ible80** [DistroAV/DistroAV#1095]
### Operating System Version

MACOS 15 Sequoia

### CPU

M2

### GPU

m2

### OBS Version

30

### OBS Installation Method

pkg

### DistroAV Version

4.14

### DistroAV Installation Method

pkg

### NDI Version

6

### Describe the bug

The OBS loads all libs but dont show the video from camera. The NDI Video Monitor works properly.

We have 2 cams. All works fine before update MacOs to last version - Sequoia

The log goes after

22:59:52.335: [obs-ndi] obs_module_load: you can haz obs-ndi (Version 4.14.1)
22:59:52.335: [obs-ndi] obs_module_load: Qt Version: 6.6.3 (runtime), 6.6.2 (compiled)
22:59:52.335: [obs-ndi] load_ndilib: Trying '/usr/lib/libndi.dylib'
22:59:52.335: [obs-ndi] load_ndilib: Trying '/usr/local/lib/libndi.dylib'
22:59:52.335: [obs-ndi] load_ndilib: Found '/usr/local/lib/libndi.dylib'; attempting to load NDI library...
22:59:52.774: [obs-ndi] load_ndilib: NDI library loaded successfully
22:59:52.774: [obs-ndi] load_ndilib: NDIlib_v5_load found
22:59:52.775: [obs-ndi] obs_module_load: NDI library initialized successfully ('NDI SDK APPLE 09:05:57 May  6 2024 6.0.1')
22:59:52.793: [obs-ndi] preview_output_init('OBS Preview', '')
22:59:52.793: [obs-ndi] +ndi_output_create(name='OBS Preview', groups='', ...)
22:59:52.793: [obs-ndi] ndi_output_update(name='OBS Preview', groups='', ...)
22:59:52.793: [obs-ndi] -ndi_output_create(name='OBS Preview', groups='', ...)

### Screenshots

![Captura de Tela 2024-09-18 às 23 07 24](https://github.com/user-attachments/assets/ee7a6219-1c47-4231-bdcd-7854690b2305)
![Captura de Tela 2024-09-18 às 23 07 43](https://github.com/user-attachments/assets/9bb01420-bc67-47aa-8b4d-3d48aec658bb)

**Comment by Trouffman** [comment]
Can you access this NDI Video feed from the Studio Monitor?

**Comment by AnKlaGo** [comment]
I am having the same problem. Black screen since Sequoia Update in OBS. Source name is found but no feed. Tried 4.14.1 and 6.0.0 RC1. Completely removed OBS and the Plugin in between with no luck. The NDI Video Monitor is working without issues directly.

**Comment by Trouffman** [comment]
Please check in the firewall settings if OBS is there :

https://support.apple.com/en-ca/guide/mac-help/mh11783/15.0/mac/15.0

I could not reproduce the issue on my side. So it's hard to diagnose

**Comment by AnKlaGo** [comment]
Did another fresh install of OBS and the Plugin and now its suddenly working, but only with 4.14.1. IDK why, didn''t change any other settings. 6 RC1 plugin still did not work though.

**Comment by Trouffman** [comment]
Please use the V6 release.

And make sure OBS/distroav are allowed to use the network discovery in the new MacOS prompt.
