### ISSUE TITLE
[Bug]: NDI™ Runtime not found.

### ISSUE THREAD

**Issue by hcampana91** [DistroAV/DistroAV#1101]
### Operating System Version

macOS Sonoma version 14.6.1

### CPU

Apple M2 Pro

### OBS Version

30.2.3 (64bit)

### OBS Installation Method

.dmg

### DistroAV Version

is not posible to see thar info 

### DistroAV Installation Method

.dmg

### NDI Version

4.x54

### Describe the bug

obs-ndi cannot continue and will be unloaded. If this problem persists, please:
[Report an obs-ndi Issue](https://distroav.org/report-bug)
-or-
[Uninstall obs-ndi](https://distroav.org/wiki/uninstall)
![Screenshot 2024-10-01 at 8 30 09 AM](https://github.com/user-attachments/assets/c51ff152-40b7-4597-92a9-383a09567d9e)

**Comment by paulpv** [comment]
@hcampana91 Did you install the NDI Runtime? 

NDI did have a problem with their link not working for a few days recently.

**Comment by Trouffman** [comment]
Please follow the pre-requirement installation : 
https://github.com/DistroAV/DistroAV/wiki/1.-Installation
