### ISSUE TITLE
NDI Runtime link does not work

### ISSUE THREAD

**Issue by Jaybonaut** [DistroAV/DistroAV#1102]
### Operating System Version

N/A

### CPU

N/A

### GPU

N/A

### NDI Devices

N/A

### OBS Version

30.2.3

### OBS Installation Method

N/A

### DistroAV Version

N/A

### DistroAV Installation Method

N/A

### [Extra] Installation Steps

N/A

### NDI Version

4.14.1

### Describe the bug

The link http://ndi.link/NDIRedistV6 goes nowhere as of this post.

**Comment by BitRate27** [comment]
This link does not show up in the 6.0.0 RC1. It is a new link to ndi.video, however I still see the Redist URLs in the code. Where are you seeing this link in 4.14.1? I suspect this is not a user issue starting with 6.0.0, but rather something we need to clean up in the code base.

**Comment by RayneYoruka** [comment]
it's been mentioned on the discord server, the link to the redist isn't working

**Comment by Jaybonaut** [comment]
> This link does not show up in the 6.0.0 RC1. It is a new link to ndi.video, however I still see the Redist URLs in the code. Where are you seeing this link in 4.14.1? I suspect this is not a user issue starting with 6.0.0, but rather something we need to clean up in the code base.

Right on the releases page.

**Comment by paulpv** [comment]
This link is pulled directly from the NDI source code:
https://github.com/DistroAV/DistroAV/blob/master/lib/ndi/Processing.NDI.Lib.h#L53-L57
```
#				define NDILIB_REDIST_URL    "http://ndi.link/NDIRedistV6"
...
#				define NDILIB_REDIST_URL    "http://ndi.link/NDIRedistV6"
```

But NDI has changed this in the past and it caused problems, so I invented a way to attempt to mitigate this a bit by using our own redirect URLs:
https://github.com/DistroAV/DistroAV/blob/master/src/plugin-main.h#L61-L84
```
#define PLUGIN_UPDATE_URL "https://distroav.org/api/update"

#define PLUGIN_REDIRECT_DISCORD_URL "https://distroav.org/discord"
#define PLUGIN_REDIRECT_DONATE_URL "https://distroav.org/donate"
#define PLUGIN_REDIRECT_REPORT_BUG_URL "https://distroav.org/report-bug"
#define PLUGIN_REDIRECT_TROUBLESHOOTING_URL \
	"https://distroav.org/kb/troubleshooting"
#define PLUGIN_REDIRECT_UNINSTALL_URL "https://distroav.org/kb/uninstall"
#define PLUGIN_REDIRECT_UNINSTALL_OBSNDI_URL \
	"https://distroav.org/kb/uninstall-obs-ndi"
#if defined(Q_OS_WIN)
// Windows
#define PLUGIN_REDIRECT_NDI_REDIST_URL "https://distroav.org/ndi/redist-windows"
#elif defined(Q_OS_MACOS)
// MacOS
#define PLUGIN_REDIRECT_NDI_REDIST_URL "https://distroav.org/ndi/redist-macos"
#else
// Linux
#define PLUGIN_REDIRECT_NDI_REDIST_URL "https://distroav.org/ndi/redist-linux"
#endif
#define PLUGIN_REDIRECT_NDI_SDK_CPU_REQUIREMENTS_URL \
	"https://distroav.org/ndi/sdk-cpu-requirements"
#define PLUGIN_REDIRECT_NDI_TOOLS_URL "https://distroav.org/ndi/tools"
#define PLUGIN_REDIRECT_NDI_WEB_URL "https://distroav.org/ndi/web"
```

Those are controlled in the private repo https://github.com/DistroAV/firebase/blob/main/functions/index.js#L65-L115
```
app.get("/code", async (req, res) => {
  logAndRedirect(req, res, "https://github.com/DistroAV/DistroAV");
});
app.get("/discord", async (req, res) => {
  logAndRedirect(req, res, "https://discord.gg/ZuTxbUK3ug");
});
app.get("/donate", async (req, res) => {
  logAndRedirect(req, res, "https://opencollective.com/distroav/donate");
});
app.get("/download", async (req, res) => {
  logAndRedirect(req, res, "https://github.com/DistroAV/DistroAV/releases/latest");
});
app.get("/forum", async (req, res) => {
  logAndRedirect(req, res, "https://obsproject.com/forum/resources/distroav-network-audio-video-in-obs-studio-using-ndi-technology.528/");
});
app.get("/report-bug", async (req, res) => {
  logAndRedirect(req, res, "https://github.com/DistroAV/DistroAV/issues/new?labels=bug%2Ctriage&template=BUG.yml&title=%5BBug%5D%3A+");
});
app.get("/kb/obs-ndi-is-now-distroav", async (req, res) => {
  logAndRedirect(req, res, "https://github.com/DistroAV/DistroAV/wiki/OBS%E2%80%90NDI-Is-Now-DistroAV");
});
app.get("/kb/troubleshooting", async (req, res) => {
  logAndRedirect(req, res, "https://github.com/DistroAV/DistroAV/wiki/2.-Troubleshooting");
});
app.get("/kb/uninstall", async (req, res) => {
  logAndRedirect(req, res, "https://github.com/DistroAV/DistroAV/wiki/1.-Installation#uninstall");
});
app.get("/kb/uninstall-obs-ndi", async (req, res) => {
  logAndRedirect(req, res, "https://github.com/DistroAV/DistroAV/wiki/OBS%E2%80%90NDI-Is-Now-DistroAV#uninstall-obs-ndi");
});
app.get("/ndi/redist-linux", async (req, res) => {
  logAndRedirect(req, res, "https://github.com/DistroAV/DistroAV/blob/master/CI/libndi-get.sh");
});
app.get("/ndi/redist-macos", async (req, res) => {
  logAndRedirect(req, res, "http://ndi.link/NDIRedistV6Apple");
});
app.get("/ndi/redist-windows", async (req, res) => {
  logAndRedirect(req, res, "http://ndi.link/NDIRedistV6");
});
app.get("/ndi/sdk-cpu-requirements", async (req, res) => {
  logAndRedirect(req, res, "https://docs.ndi.video/docs/sdk/cpu-requirements");
});
app.get("/ndi/tools", async (req, res) => {
  logAndRedirect(req, res, "https://ndi.video/tools/download/");
});
app.get("/ndi/web", async (req, res) => {
  logAndRedirect(req, res, "https://ndi.video");
});
app.get("/obs-studio", async (req, res) => {
  logAndRedirect(req, res, "https://obsproject.com");
});
```

The theory is/was that if any of those redirects change then we can change them on our server and not have to require any update to the plugin itself.

This theory works well... when the links themselves are not bad.

The reality seems to be that http://ndi.link/NDIRedistV6 is indeed 404, and I have no idea what the new URL should be to change to.

I have downloaded the latest NDI SDK and there is no change here.

Do we have a contact at NDI?

**Comment by paulpv** [comment]
@Jaybonaut this seems to be working again. 
Please confirm. 

Our NDI contact said:
> It's some kind of migration issue with DNS.  Hoping that's resolved soon, though it's been some time already... 🙄

**Comment by Jaybonaut** [comment]
> @Jaybonaut this seems to be working again. Please confirm.
> 
> Our NDI contact said:
> 
> > It's some kind of migration issue with DNS.  Hoping that's resolved soon, though it's been some time already... 🙄

Yes, thanks, seems to be good now.
