### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mar470** [DistroAV/DistroAV#1103]
### Operating System Version

b ki

### CPU

nv

### GPU

kljfg

### NDI Devices

,l4f

### OBS Version

30.2.3

### OBS Installation Method

y0

### DistroAV Version

moho

### DistroAV Installation Method

jj

### [Extra] Installation Steps

jig

### OBS Log [URL]

oihy[9vy

### NDI Version

30

### Describe the bug

jiu

### Steps to reproduce the problem

kh

### Expected behavior

lkh o

### Screenshots

koho 

### Additional context

kjh b9

**Comment by mar470** [comment]
,hj più

**Comment by paulpv** [comment]
trash/spam/junk
