### ISSUE TITLE
[Bug]: NDI Runtime Not Found Even thought i installed what i thought it was everything.

### ISSUE THREAD

**Issue by presurized** [DistroAV/DistroAV#1107]
### Operating System Version

Linux Mint System:   Kernel: 5.15.0-122-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4     tk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia     base: Ubuntu 22.04 jammy

### CPU

Info: 6-core model: AMD Ryzen 5 2600X bits: 64

### GPU

Graphics:   Device-1: NVIDIA GP104 [GeForce GTX 1070] vendor: eVga.com. driver: nvidia v: 535.183.01 pcie:     speed: 2.5 GT/s lanes: 16 ports: active: none off: HDMI-A-1 empty: DP-1, DP-2, DP-3, DVI-D-1     bus-ID: 07:00.0 chip-ID: 10de:1b81 class-ID: 0300   Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia     unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia display-ID: :0 screens: 1   Screen-1: 0 s-res: 1920x1080 s-dpi: 55 s-size: 887x499mm (34.9x19.6") s-diag: 1018mm (40.1")   Monitor-1: HDMI-0 res: 1920x1080 hz: 60 dpi: 56 size: 878x485mm (34.6x19.1")     diag: 1003mm (39.5")   OpenGL: renderer: NVIDIA GeForce GTX 1070/PCIe/SSE2 v: 4.6.0 NVIDIA 535.183.01     direct render: Yes

### NDI Devices

Another PC with a NDI source

### OBS Version

30.2.3

### OBS Installation Method

obs-ndi-4.14.1-x86_64-linux-gnu.deb

### DistroAV Version

obs-ndi-4.14.1-x86_64-linux-gnu.deb

### DistroAV Installation Method

obs-ndi-4.14.1-x86_64-linux-gnu.deb

### [Extra] Installation Steps

Followed the instructions here:
https://github.com/DistroAV/DistroAV/wiki/1.-Installation#required---ndi-runtime

### OBS Log [URL]

https://obsproject.com/logs/qGcBCDu3SOAKrKsm

### NDI Version

That menu is not available (Tools->NDI Output Settings, NDI SDK ...)

### Describe the bug

Received this toast:
NDI™ Runtime not found.

Download the installer here:
https://distroav.org/ndi/redist-linux

obs-ndi cannot continue and will be unloaded. If this problem persists, please:
[Report an obs-ndi Issue](https://distroav.org/report-bug)
-or-
[Uninstall obs-ndi](https://distroav.org/wiki/uninstall)

### Steps to reproduce the problem

Open OBS.

### Screenshots

![Screenshot from 2024-10-13 22-43-28](https://github.com/user-attachments/assets/53577322-810f-4ea0-bc34-6726c3c9ad06)

**Comment by RayneYoruka** [comment]
did you download and install through this? https://github.com/DistroAV/DistroAV/blob/master/CI/libndi-get.sh

**Comment by presurized** [comment]
I tried that as well, No changes

**Comment by RayneYoruka** [comment]
did you install with this specific way "sudo ./libndi-get.sh install" ?

**Comment by presurized** [comment]
Thank you, You just fixed it for me.
No, I did not use the sudo command, Went ahead and tried it and that fixed
it.
Again, Thank you.

**Comment by RayneYoruka** [comment]
Np! don't forget to close!

**Comment by paulpv** [comment]
@RayneYoruka We should probably put sudo inside the script! 😄

**Comment by RayneYoruka** [comment]
It would streamline the process definitely 💯

**Comment by presurized** [comment]
I was wondering why it wasn't a thing, But i figured there was a reason, I
think that would make it easier for people like me!
