### ISSUE TITLE
[Bug]: "NDI Runtime not found" on OBS startup; despite having installed NDI runtime

### ISSUE THREAD

**Issue by raleighlittles** [DistroAV/DistroAV#1111]
### Operating System Version

Ubuntu 24.04.1 LTS

### CPU

Intel i9-14900 (32) @ 5.500GHz

### GPU

NVIDIA Geforce RTX 3050 

### OBS Version

30.0.2.-1-3build1

### OBS Installation Method

flatpack

### DistroAV Version

6.0.1

### DistroAV Installation Method

git

### OBS Log [URL]

https://obsproject.com/logs/S9xFl4YSiDRETZjT

### NDI Version

Latest

### Describe the bug

Every time I open OBS I get an popup error saying that the NDI runtime is not installed.

![Screenshot from 2024-10-22 23-18-40](https://github.com/user-attachments/assets/41372692-8beb-4fd8-815d-7be43e6a74aa)

However, I've already installed the NDI runtime by running `libndi-get.sh` from here https://github.com/DistroAV/DistroAV/blob/master/CI/libndi-get.sh

and from the website, by downloading `Install_NDI_SDK_v6_Linux.tar.gz` and then running the installer script.

Here's a screenshot of me running the installer script for a second time, it correctly detects that NDI is already installed:

![image](https://github.com/user-attachments/assets/322575ad-703e-45a9-861b-e47ffe316e8b)

Here is the installer script `libndi-get.sh` after running successfully: 

![image](https://github.com/user-attachments/assets/eb64a29e-fdad-463f-9e7d-b16266ffd9a2)

Yet when I open OBS studio I still see the popup about the runtime not being available.

This is the version of DistroAV `9871ed64cb036dff41f737a5f7894b057d7ee7a5` that I have.

### Additional context

To add, I don't see a `/usr/local/lib/ndi` directory, so it looks for some reason the installer script doesn't work.

**Comment by BitRate27** [comment]
If you run the script with the "install" argument, it will copy the files to the long term location. You should see this in the log: Copying the library files to the long-term location.

**Comment by BitRate27** [comment]
I updated the install instructions for linux to show how to run the install script properly.

`./libndi-get.sh install`
