### ISSUE TITLE
[Bug]: NDI Audio recording/streaming output is distorted, but fine when monitoring real time in OBS

### ISSUE THREAD

**Issue by jahaddow** [DistroAV/DistroAV#1113]
### Operating System Version

Windows 11

### OBS Version

30.2.3

### OBS Installation Method

.exe

### DistroAV Version

6.0.0

### DistroAV Installation Method

.exe

### NDI Version

6

### Describe the bug

I am using a Kiloview bonding encoder. The server produces an NDI HX output which I am pulling into OBS. When monitoring the sound and picture everything appears fine, the audio and video are perfect and in sync. 

When recording or streaming, the recorded NDI sound is very distorted. I have tried changing between 48khz and 44.1 with no luck. I have also tried both core audio and ffmpeg aac encoders. 

If I change the audio video sync option to network, the audio records fine, however introduces video stuttering which is unusable. Why is the audio and picture perfect when monitoring but not recording/streaming?

**Comment by Trouffman** [comment]
Please provide the following:
- start OBS with --distroav-verbose argument 
- reproduce the bug
- provide a screenshot of the NDI source settings that have the issue
- provide screenshot of the NDI source settings without the issue
- are you recording on OBS itself or another tool? (Good if you can provide a video of the issue as well).

Thanks
