### ISSUE TITLE
OBS NDI video freezing problem

### ISSUE THREAD

**Issue by spkpal** [DistroAV/DistroAV#1114]
I have abit of a problem, everytime i use the OBS NDI plugin now, my videos i watch back on OBS preview on my streaming pc always freezes for a few seconds now, so i think there a bug on this newer version of this plugin

**Comment by RayneYoruka** [comment]
Please post a log of both machines

**Comment by spkpal** [comment]
https://obsproject.com/logs/yC0RBRJfXZsROgdq
https://obsproject.com/logs/CfW4rmrGzzDrIWaf

**Comment by RayneYoruka** [comment]
Wasn't the issue of your usb hub discussed and solved already on the discord?

**Comment by spkpal** [comment]
I unhooked my USB hub and its still doing the slow downs and freezing alot for me

**Comment by RayneYoruka** [comment]
Rendering lag on Log 1: https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FyC0RBRJfXZsROgdq

Mismatched sample rate on log 2: https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FCfW4rmrGzzDrIWaf

I refer to what I said on discord, a 3060 for doing ultrawide gaming isn't a good idea, not enough graphics power to handle obs.
https://obsproject.com/kb/encoding-performance-troubleshooting

**Comment by Trouffman** [comment]
Closing. No feedback and no details.
