### ISSUE TITLE
[Bug]: Not Seeing NDI Runtime

### ISSUE THREAD

**Issue by jvelasq** [DistroAV/DistroAV#1120]
### Operating System Version

Windows 10

### CPU

9900K

### GPU

2070

### NDI Devices

Only OBS and NDI tools

### OBS Version

31.0.0

### OBS Installation Method

.exe

### DistroAV Version

6.0

### DistroAV Installation Method

.exe, zip

### [Extra] Installation Steps

Installed via windows installer. Then via zip file after running the uninstall script.

### OBS Log [URL]

https://obsproject.com/logs/98BjuuwdQIeTmkvu

### NDI Version

6

### Describe the bug

From a clean install. I installed NDI Tools. Download DistroAV V6 and installed via the installer. Launched OBS saw nothing in tools. I ran the uninstall script then installed via extracting the zip file. Launched OBS and got a popup saying "NDI Runtime not found." I used the link to install the installed linked in the popup and same issue occurs.

### Screenshots

![image](https://github.com/user-attachments/assets/210875ea-4fd7-4700-9e47-3f630a16d68c)

### Additional context

I have used NDI before in OBS and it has work perfectly.

**Comment by paulpv** [comment]
Your OBS log output says:
```
01:40:13.807: [DistroAV] obs_module_load: you can haz DistroAV (Version 6.0.0)
01:40:13.807: [DistroAV] obs_module_load: Qt Version: 6.6.3 (runtime), 6.6.2 (compiled)
01:40:13.807: DEPRECATION: obs_frontend_get_global_config is deprecated. Read from global or user configuration explicitly instead.
01:40:13.807: DEPRECATION: obs_frontend_get_global_config is deprecated. Read from global or user configuration explicitly instead.
01:40:13.809: [DistroAV] load_ndilib: ERROR: Can't find the NDI library
01:40:13.809: [DistroAV] obs_module_load: ERROR - load_ndilib() failed; message=NDI® Runtime not found.<br><br>Download the installer here:<br><a href="http://ndi.link/NDIRedistV6">http://ndi.link/NDIRedistV6</a>
01:40:13.809: Failed to initialize module 'distroav.dll'
```

Open a command-prompt and run:
```
set NDI
```
Example output:
```
NDI_RUNTIME_DIR_V2=C:\Program Files\NDI\NDI 6 Tools\Runtime
NDI_RUNTIME_DIR_V3=C:\Program Files\NDI\NDI 6 Tools\Runtime
NDI_RUNTIME_DIR_V4=C:\Program Files\NDI\NDI 6 Tools\Runtime
NDI_RUNTIME_DIR_V5=C:\Program Files\NDI\NDI 6 Tools\Runtime
NDI_RUNTIME_DIR_V6=C:\Program Files\NDI\NDI 6 Tools\Runtime
```

I should probably just do this automatically on Windows and add to the log (and anything relevant/similar on MacOS & Linux).

I could be wrong, but if I recall correctly, in the past installing `NDI Tools` does not install the `NDI Runtime` [for 3rd party apps to use], it just "installed the NDI Runtime installer"; a user would still have to manually launch the NDI Runtime installer to install the runtime, 
Maybe I am just confusing this with the separate `NDI SDK`, which definitely still acts this way.

Regardless, I confirmed that installing `NDI Tools` does seem to install the `NDI Runtime` and set the required environment variables (the above example `set NDI` output is from my PC after NDI Tools was installed from scratch).

I just did this and it worked fine.

I uninstalled everything NDI on my Windows 11 PC and ensured I had no NDI files or environment variables set.
(I did not reboot).
I downloaded the latest NDI Tools and installed it.
I launched OBS (w/ DistroAV already installed) and OBS/DistroAV initialized just fine.

My OBS log output was:
```
04:05:47.375: [DistroAV] obs_module_load: you can haz DistroAV (Version 6.0.0)
04:05:47.375: [DistroAV] obs_module_load: Qt Version: 6.6.3 (runtime), 6.6.2 (compiled)
04:05:47.376: [DistroAV] load_ndilib: Trying 'C:\Program Files\NDI\NDI 6 Tools\Runtime\Processing.NDI.Lib.x64.dll'
04:05:47.376: [DistroAV] load_ndilib: Found 'C:\Program Files\NDI\NDI 6 Tools\Runtime\Processing.NDI.Lib.x64.dll'; attempting to load NDI library...
04:05:47.412: [DistroAV] load_ndilib: NDI library loaded successfully
04:05:47.412: [DistroAV] load_ndilib: NDIlib_v5_load found
04:05:47.730: [DistroAV] obs_module_load: NDI library initialized successfully ('NDI SDK WIN64 12:45:30 May  6 2024 6.0.1.0')
```

**Comment by jvelasq** [comment]
So I removed everything NDI related and restarted after I restarted I launched obs to download the linked NDI runtime. Once it installed I restarted again and now it now works normally EXCEPT my second computer sees the section but has a black screen. I used NDI monitor in the second computer but it does not see my first computer. If I send an image via signal generator with NDI tools it works just fine.

**Comment by RayneYoruka** [comment]
Disable firewall on both machines temporarely to confirm it's firewall

**Comment by jvelasq** [comment]
That worked. I feel dumb for not thinking of that. What do I need to do to allow the NDI past the firewall?

**Comment by RayneYoruka** [comment]
> That worked. I feel dumb for not thinking of that. What do I need to do to allow the NDI past the firewall?

You'd be surprised how many users have this issue.

Whitelist 5959, 5960 tcp/udp for incoming/outgoing connections on both machines (You'll have to google how to) I don't use winodws firewall due to the amount of issues it causes

**Comment by jvelasq** [comment]
Thanks everything is working now!
