### ISSUE TITLE
[Bug]: The screen sharing is working, but the audio is not working on the computer where I will broadcast.

### ISSUE THREAD

**Issue by akintelli** [DistroAV/DistroAV#1122]
### Operating System Version

Windows 10 

### CPU

Ryzen5 5600x ( Streaming ) - i5 12600k ( Gaming )

### GPU

RX 5600XT ( Streaming ) - 1080 Ti ( Gaming )

### NDI Devices

6

### OBS Version

30.2.3

### OBS Installation Method

exe

### DistroAV Version

6

### DistroAV Installation Method

exe

### OBS Log [URL]

https://obsproject.com/logs/fFZ7kjDUo2ghsbQi

### NDI Version

6

### Describe the bug

I had the same issue with the old version as well. I had uninstalled and reinstalled NDI 5 multiple times, and it worked then. (It worked when I set it to Audio Only, but not in normal mode.) I updated to NDI 6 after the new update, but now there’s no sound at all. I also tried going back to the old version, but that isn’t working either.

### Screenshots

![Adsız](https://github.com/user-attachments/assets/4cc41b4e-2d0b-4f1a-bca1-ad93d1514f7e)

**Comment by paulpv** [comment]
Does NDI Studio Monitor on the Streaming PC have audio?
What are you using to capture audio on the Gaming PC with?

**Comment by paulpv** [comment]
```
22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: Check for 'NDI Source Name' changes: new_ndi_source_name='DESKTOP-LREJEII (OBS Preview)' vs config.ndi_source_name='(null)'
22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: Check for 'Bandwidth' setting changes: new_bandwidth='0' vs config.bandwidth='0'
22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: Check for 'Latency' setting changes: new_latency='0' vs config.latency='0'
22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: Check for 'Framesync' setting changes: new_framesync_enabled='true' vs config.framesync_enabled='false'
22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: Check for 'Hardware Acceleration' setting changes: new_ndi_source_name='true' vs config.ndi_source_name='false'
22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: Check for 'Behavior' setting changes: behavior='0' vs config.behavior='0'
22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: Deactivate source output video (Actively reset the frame content)
22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: NDI Source 'DESKTOP-LREJEII (OBS Preview)' selected.
22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: Requesting Source Thread Start.
22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_thread_start: Started A/V ndi_source_thread for NDI source 'DESKTOP-LREJEII (OBS Preview)'
```

Why use a Preview source?

**Comment by akintelli** [comment]
> Does NDI Studio Monitor on the Streaming PC have audio? What are you using to capture audio on the Gaming PC with?

yes audio is working on streaming pc 
![image](https://github.com/user-attachments/assets/a7cf830a-1148-42ac-97a0-1c3ac00306a0)

Im using nothing for capture audio just obs both with default settings

**Comment by akintelli** [comment]
> ```
> 22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: Check for 'NDI Source Name' changes: new_ndi_source_name='DESKTOP-LREJEII (OBS Preview)' vs config.ndi_source_name='(null)'
> 22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: Check for 'Bandwidth' setting changes: new_bandwidth='0' vs config.bandwidth='0'
> 22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: Check for 'Latency' setting changes: new_latency='0' vs config.latency='0'
> 22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: Check for 'Framesync' setting changes: new_framesync_enabled='true' vs config.framesync_enabled='false'
> 22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: Check for 'Hardware Acceleration' setting changes: new_ndi_source_name='true' vs config.ndi_source_name='false'
> 22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: Check for 'Behavior' setting changes: behavior='0' vs config.behavior='0'
> 22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: Deactivate source output video (Actively reset the frame content)
> 22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: NDI Source 'DESKTOP-LREJEII (OBS Preview)' selected.
> 22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_update: Requesting Source Thread Start.
> 22:50:45.943: [DistroAV] 'NDI™ Source' ndi_source_thread_start: Started A/V ndi_source_thread for NDI source 'DESKTOP-LREJEII (OBS Preview)'
> ```
> 
> Why use a Preview source?

I’m trying all of them, but none of them are responding at all.

**Comment by paulpv** [comment]
> Im using nothing for capture audio just obs both with default settings

If you are using nothing to capture audio, then where do you expect the audio to come from?

**Comment by RayneYoruka** [comment]
What version where you on previously?

**Comment by akintelli** [comment]
https://obsproject.com/logs/0GGWbAgqKs9IXUE2

> What version where you on previously?

OBS-NDI 4.14.1 ,I tried using it again, but the same issue came up. I reinstalled OBS and NDI, but the problem didn’t change. The video is transmitting, but the audio isn’t.

**Comment by RayneYoruka** [comment]
The audio bug is pretty inconsistent and it's totally at random who gets it or doesn't. My advise is that you use your audio/video from the same NDI source. you won't have that issue anymore. If the issue persists you will have to remove the source or to enable/disable it until it comes back

**Comment by akintelli** [comment]
> The audio bug is pretty inconsistent and it's totally at random who gets it or doesn't. My advice is that you use your audio/video from the same NDI source. you won't have that issue anymore. If the issue persists you will have to remove the source or to enable/disable it until it comes back

I’m using the same NDI source, but the video is coming through, and the audio is not. I tried other methods to solve the issue.

**Comment by paulpv** [comment]
> Does NDI Studio Monitor on the Streaming PC have audio?

**Comment by akintelli** [comment]
> > Does NDI Studio Monitor on the Streaming PC have audio?
> 
> From the info you have provided I cannot tell if this is a capturing/sending problem or a receiving/rendering problem.

If you mean this application, I can’t get any sound from here either.
![image](https://github.com/user-attachments/assets/340d0794-6c25-46dd-b562-0cb7c4022e9f)

**Comment by RayneYoruka** [comment]
> > > Does NDI Studio Monitor on the Streaming PC have audio?
> > 
> > 
> > From the info you have provided I cannot tell if this is a capturing/sending problem or a receiving/rendering problem.
> 
> If you mean this application, I can’t get any sound from here either. ![image](https://private-user-images.githubusercontent.com/85977064/380896685-340d0794-6c25-46dd-b562-0cb7c4022e9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNTA3NzQsIm5iZiI6MTczMDE1MDQ3NCwicGF0aCI6Ii84NTk3NzA2NC8zODA4OTY2ODUtMzQwZDA3OTQtNmMyNS00NmRkLWI1NjItMGNiN2M0MDIyZTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDIxMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZDEyZjhjOTA1ZWRjYmEzOTZiMTM3OTlkYmQ0NDYwYzhhM2ZiNzlmMGY1YWY3ZWMxNmNjMDM3YWQ0MWUxNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lKNML-VoaINuuL0iF6NZ5I-rYIQ2dnfgY202aBBThFM)

Thats the main output (What you are selecting on NDI studio monitor). If you don't have any "audio device" (mic/desktop audio) on the OBS settings selected or added within obs as a source NDI won't send the audio. It's difficult to understand what the sources names are when they are not in english sadly

**Comment by akintelli** [comment]
> > > > Does NDI Studio Monitor on the Streaming PC have audio?
> > > 
> > > 
> > > From the info you have provided I cannot tell if this is a capturing/sending problem or a receiving/rendering problem.
> > 
> > 
> > If you mean this application, I can’t get any sound from here either. ![image](https://private-user-images.githubusercontent.com/85977064/380896685-340d0794-6c25-46dd-b562-0cb7c4022e9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNTA3NzQsIm5iZiI6MTczMDE1MDQ3NCwicGF0aCI6Ii84NTk3NzA2NC8zODA4OTY2ODUtMzQwZDA3OTQtNmMyNS00NmRkLWI1NjItMGNiN2M0MDIyZTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDIxMjExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjZDEyZjhjOTA1ZWRjYmEzOTZiMTM3OTlkYmQ0NDYwYzhhM2ZiNzlmMGY1YWY3ZWMxNmNjMDM3YWQ0MWUxNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lKNML-VoaINuuL0iF6NZ5I-rYIQ2dnfgY202aBBThFM)
> 
> Thats the main output (What you are selecting on NDI studio monitor). If you don't have any "audio device" (mic/desktop audio) on the OBS settings selected or added within obs as a source NDI won't send the audio. It's difficult to understand what the sources names are when they are not in english sadly

Oh, I changed the language and re-added the NDI source, and the sound is fixed. It was a strange solution, but thank you!

**Comment by paulpv** [comment]
Changed the language to what?
Could the problem be that the source names are not English?

**Comment by akintelli** [comment]
> Changed the language to what? Could the problem be that the source names are not standard English characters?

"I changed the language from Turkish to English, set the Gaming PC output back to main output, and it worked. I don’t want to dig too deep into the issue now that it’s fixed, as I need to get back to my streams. But it seems that changing the language to English was the solution.

**Comment by paulpv** [comment]
Were your previously working sources named in English or Turkish?

**Comment by akintelli** [comment]
> Daha önce çalıştığınız kaynakların isimleri İngilizce miydi yoksa Türkçe miydi?

There were no Turkish characters, I just changed the obs language

**Comment by paulpv** [comment]
Interesting; thanks.

**Comment by Trouffman** [comment]
I could not reproduce this issue even when changing the language.
Will close as this could not be reproduced.
