### ISSUE TITLE
[Bug]: Plugin does not work despite uninstalling OBS-NDI

### ISSUE THREAD

**Issue by TheLucEh** [DistroAV/DistroAV#1123]
### Operating System Version

Sequoia 15.0.1

### CPU

M2 Max

### GPU

M2 Max

### OBS Version

30.2.3

### OBS Installation Method

.dmg

### DistroAV Version

6.0.0

### DistroAV Installation Method

.pkg

### NDI Version

6.0.1

### Describe the bug

I have uninstalled everything that has to do with NDI. I still get the error message within OBS that DistroAV can only be installed if OBS-NDI is uninstalled.

**Comment by BitRate27** [comment]
Sorry for the issue. DId you delete ~/Library/Application Support/obs-studio/plugins/obs-ndi.plugin ?
DId you see that step in the installation instructions here: https://github.com/DistroAV/DistroAV/wiki/1.-Installation#macos-2 ?

**Comment by StLukeMark** [comment]
I just resolved this exact issue on my Mac as well. Here is how to fix it: 

1. Delete the file from ~/Library/Application Support/obs-studio/plugins/
2. THEN go and delete the obs-ndi folder from ~/Library/Application Support/obs-studio/plugins/ 
**_(without the ~)_**

Then it should work!

**Comment by Trouffman** [comment]
Good this is solved.

Will update the uninstall notes about this.
