### ISSUE TITLE
[Bug]: Uninstall all ndi components on MacBook Pro

### ISSUE THREAD

**Issue by louis52** [DistroAV/DistroAV#1124]
### Operating System Version

OS X Séquoia 

### CPU

Intel

### OBS Version

30.2.3

### OBS Installation Method

pkg

### DistroAV Version

6.0.0

### DistroAV Installation Method

pkg

### OBS Log [URL]

https://obsproject.com/logs/vDfOgzjRA1n2wFxo

### NDI Version

obs-ndi 4.14.1

### Describe the bug

I do desinstall all components find on Application support/OBS/plugin and put all ndi application, stop and restart OBS, but it appears that it's not desinstall.The message error is distroAV cannot be install, but all éléments are removed or absent, I follow the procedure on NDI tools desinstallation.

### Expected behavior

Clearly install distroAV

### Screenshots

<img width="408" alt="Capture d’écran 2024-10-29 à 13 34 28" src="https://github.com/user-attachments/assets/0d64efc1-ae43-4d87-b88f-db3d81709b8a">

**Comment by BitRate27** [comment]
Does the ~/Library/Application Support/obs-studio/plugins/obs-ndi.plugin file still exist? In Finder do Shift-Command-G and paste that file name and press enter. That is the file that needs to be deleted. You mentioned the "Application support/OBS/plugin" folder, which is not where the old obs-ndi.plugin resides.

**Comment by louis52** [comment]
Yes, we did it, thank for resolution of ban, I find the right files and deleted them, let's try to resolve the problem, think a lot for your reactivity, where are you from?

**Comment by louis52** [comment]
Everything is ok with distroAV now.

**Comment by paulpv** [comment]
Documented at https://github.com/DistroAV/DistroAV/wiki/1.-Installation#macos-2
> MacOS
> 1. Open Finder
> 2. Show hidden files with Command-Shift-.
> 3. Delete ~/Library/Application Support/obs-studio/plugins/obs-ndi.plugin
> 4. (Optional) Remove other NDI components
>   i. Finder->Applications: Delete all NDI * applications
>   ii. Delete /Library/Application Support/NewTek/NDI
>   iii. Delete /usr/local/lib/libndi*
