### ISSUE TITLE
[Bug]: Check for updates says that i didnt download an official release of distroAV?? 

### ISSUE THREAD

**Issue by alexandremix** [DistroAV/DistroAV#1125]
### Operating System Version

win 11

### OBS Version

30.2.3

### OBS Installation Method

.exe Windows

### DistroAV Version

6

### DistroAV Installation Method

.exe downloaded from github releases

### NDI Version

no NDI

### Describe the bug

![image](https://github.com/user-attachments/assets/e7a9b3e0-ad97-4e9d-992f-f3f58d47ef1c)

### Screenshots

![image](https://github.com/user-attachments/assets/4930411d-d580-4105-88f9-4d62a40075a6)

**Comment by BitRate27** [comment]
I get the same thing on macos. @paulpv is this something that can be fixed on the distroav.org server?

**Comment by RayneYoruka** [comment]
_It happened by accidnet. Please don't panic_

**Comment by RayneYoruka** [comment]
For me it still shows the same, I decided to reinstall the plugin to make sure

**Comment by paulpv** [comment]
I can bounce the server...

**Comment by RayneYoruka** [comment]
Working now in windows

**Comment by BitRate27** [comment]
...and on macos. Thanks!

**Comment by paulpv** [comment]
Fixed

@Trouffman

**Comment by Trouffman** [comment]
THis was a human mistake (mine). Sorry for that folks.

**Comment by alexandremix** [comment]
> THis was a human mistake (mine). Sorry for that folks.

Ty! its now fixed!
