### ISSUE TITLE
[Bug]: distrov ndi not working on my laptop after installation

### ISSUE THREAD

**Issue by ArinzeOkeke1** [DistroAV/DistroAV#1127]
### Operating System Version

windows 11 pro

### CPU

11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz   3.00 GHz

### NDI Devices

obs studio

### OBS Version

obs version 30.2.3

### OBS Installation Method

windows installer

### DistroAV Version

ex: 6.0.0

### DistroAV Installation Method

exe

### NDI Version

6.0.0

### Describe the bug

distov ndi is not reflecting on my obs

**Comment by RayneYoruka** [comment]
Have you followed the install instructions?  https://github.com/DistroAV/DistroAV/wiki/1.-Installation or checkedthe troubleshooting guide?  https://github.com/DistroAV/DistroAV/wiki/2.-Troubleshooting

**Comment by paulpv** [comment]
@ArinzeOkeke1 you have to tell us more than just "distov ndi is not reflecting on my obs".

Otherwise we cannot help and will just close this bug.

**Comment by Trouffman** [comment]
An OBS log is required for this typ eof issue. Please provide an OBS log and create a new Issue for this.
