### ISSUE TITLE
[Bug]: Cannot install DistroAV on MacBook (Intel)

### ISSUE THREAD

**Issue by K-Yo-GH** [DistroAV/DistroAV#1129]
### Operating System Version

MacOS Sonoma 14.6.1.

### CPU

1.1 GHz  Quad-Core Intel Core i5

### GPU

Intel Iris Plus Graphics 1536 MB

### NDI Devices

PTZOptics

### OBS Version

30.2.3

### OBS Installation Method

Download installer from OBSproject

### DistroAV Version

6.0.0

### DistroAV Installation Method

download from Github

### NDI Version

DistroAV 6.0.0

### Describe the bug

Upgrade from OBS 27 to 30 does not allow the loading of DistroAV. I have followed all the recommended steps, removed everything as suggested  (as far I can see) but I still get the message that I need to remove OBS-NDI. I tried to do this first on our MacBook Pro with intel processor which is connected to two PTZOptics camera (the MacBook Pro is the primary tool we use in our church services). As I have not been able to upgrade we are still using version 27 without a problem. I have tried to do the upgrade process on our MacBook Air with the same result. I have tried to repeat the steps several times, installing and uninstalling the different apps but to no success.

**Comment by BitRate27** [comment]
In addition to deleting ~/Library/Application Support/obs-studio/plugins/obs-ndi.plugin , you may need to remove /Library/Application Support/obs-studio/plugins/obs-ndi.plugin (without the ~) if it was installed for all users.

**Comment by Trouffman** [comment]
DistroAV requires : 
OBS >= 30.0.0 (Qt6, x64/ARM64/AppleSilicon)
[NDI Runtime >= 6](https://github.com/DistroAV/DistroAV/wiki/1.-Installation#required---ndi-runtime)
[Remove old OBS-NDI plugin](https://github.com/DistroAV/DistroAV/wiki/OBS%E2%80%90NDI-Is-Now-DistroAV)

If you use OBS 27 this will not work.

**Comment by K-Yo-GH** [comment]
You closed this before answering my question! Yes, I know what you said about the DistroAV.  I am using OBS 27 as I cannot upgrade to 30!  I coulnd't upgrade to OBS 30 even though I follow all the required steps. However thanks to the response from Bitrate24 solved the problem!
