### ISSUE TITLE
[Bug]: OBS Ndi MacOs 2024

### ISSUE THREAD

**Issue by kaylasndvl** [DistroAV/DistroAV#1138]
### Operating System Version

MacOs Sequoia 15.1

### CPU

Mac mini M2

### GPU

8gb

### NDI Devices

Propresenter

### OBS Version

30.1.2

### OBS Installation Method

exe

### DistroAV Version

Not available

### DistroAV Installation Method

exe

### NDI Version

NDi 4.5

### Describe the bug

NDI Runtime was not found.

### Expected behavior

NDI should properly be a function I can obtain within OBS. I never had an issue on a windows pc. But since we moved to MacOS I have not been able to get NDI to work

### Screenshots

![Screenshot 2024-11-09 at 11 50 30 AM](https://github.com/user-attachments/assets/d379c3d4-12ea-4a91-be4e-91753bf759d2)

**Comment by RayneYoruka** [comment]
You're using a old version of the plugin.
Uninstall then install the latest version following the instrcutions shown here: 

https://github.com/DistroAV/DistroAV/wiki/1.-Installation#uninstall
https://github.com/DistroAV/DistroAV/wiki/1.-Installation#installation

**Comment by kaylasndvl** [comment]
Thank you so much this helped. Now I am just not seeing NDI source appearing as an option to add. Any. idea what is wrong?
![Screenshot 2024-11-09 at 12 16 19 PM](https://github.com/user-attachments/assets/01c0a03a-a3a9-4b0d-b64b-dd8c83c0c949)

**Comment by RayneYoruka** [comment]
You will need to post an OBS log to see why the plugin isn't loading

**Comment by kaylasndvl** [comment]
https://obsproject.com/logs/QijVh5nSmnuKQrmo

**Comment by RayneYoruka** [comment]
The plugin doesn't show as installed on the log. Grab the installer from here https://github.com/DistroAV/DistroAV/releases/tag/6.0.0 for MacOS, if you have trouble installing refer to the previous link I sent.

**Comment by danielamar101** [comment]
The Link appears to be broken. Can anyone send a new one?

**Comment by BitRate27** [comment]
Which link is broken?

**Comment by Trouffman** [comment]
Get the latest version of the DistroAV : https://github.com/DistroAV/DistroAV/releases/tag/6.0.0

Get the lastest version of NDI Runtime : https://github.com/DistroAV/DistroAV/wiki/1.-Installation
