### ISSUE TITLE
[Bug]: Main NDI not sending to streaming pc

### ISSUE THREAD

**Issue by tyceglass9** [DistroAV/DistroAV#1139]
### Operating System Version

Windows 11

### OBS Version

30.2.3

### OBS Installation Method

.exe

### DistroAV Version

6

### DistroAV Installation Method

.exe

### NDI Version

6

### Describe the bug

My main ndi sends from streaming pc to gaming, and gaming sends the preview to the streaming pc. my main is enabled but is not showing in the options of NDI input

**Comment by RayneYoruka** [comment]
Sounds like firewall https://github.com/DistroAV/DistroAV/wiki/2.-Troubleshooting#firewall-settings--requirements

**Comment by tyceglass9** [comment]
all-settings--requirements



> Sounds like firewall https://github.com/DistroAV/DistroAV/wiki/2.-Troubleshooting#firewall-settings--requirements

i disabled firewall but the main still sending to streaming pc

**Comment by RayneYoruka** [comment]
Have you disabled it on both pcs? Verify signal from PC to PC with NDI studio monitor (from Ndi tools). If it still doesn't work you'll have to verify if it's not something else in your network. On that troubleshooting guide there is a guide of ports NDI uses as well if you want to open them manually.

**Comment by BitRate27** [comment]
If you can see the Preview but not the Main output, it could be the format of your Main output is not supported. The NDI library we use does not support HDR. Look for `[DistroAV] warning: unsupported pixel format` in the log file. If it says that, then you need to change the output format of OBS inorder to send it out as NDI.

**Comment by Trouffman** [comment]
his does not seem a DistroAV issue. no error in log and another application has the same issue.

@juniper275 Can you see the OBS output on the SAME computer using NDI Monitor?

    Open OBS
    Enable NDI Program Output
    Open NDI Studio Monitor
    Open the OBS Output stream

Does this works?

with 2 NIC > this is most likely the problem that it does not know which one to use. But this is NDI-related, DistroAV does not control this.

Read this on NDI : https://docs.ndi.video/guides/guides/tools-for-windows/access-manager#advanced-settings

**Comment by tyceglass9** [comment]
I'm not sure why, but I tried it again tonight after a few days. Worked immediately! Started setting up my OBS with NDI. I will update in a few days to make sure this issue isn't happening again. It is quite weird as my firearm is on, and I didn't do anything.

**Comment by Trouffman** [comment]
Perfect! Will close this issue as it's solved.  You can comment back with results to let other with similar issue know.
