### ISSUE TITLE
[Bug]: Windows 11 + DistroAV 6.0.0 output not working

### ISSUE THREAD

**Issue by juniper275** [DistroAV/DistroAV#1140]
### Operating System Version

windows 11 Pro 23H2

### CPU

12th Gen Intel(R) Core(TM) i7-12700   2.10 GHz

### GPU

Nvidia RTX A2000 12GB

### NDI Devices

two canon PTZ camera, one birddog mini encoder

### OBS Version

30.2.3

### OBS Installation Method

windows installer

### DistroAV Version

6.0.0

### DistroAV Installation Method

windows installer

### OBS Log [URL]

https://obsproject.com/logs/hWOo9QIj8u8KQO8E

### NDI Version

NDI SDK WIN64 12:45:30 May  6 2024 6.0.1.0

### Describe the bug

Everything works fine except obs NDI output, NDItools screen capture also doesn't work

The workstation has two network cards, one with the internet and one with a local network

Firewall is completely disabled

### Expected behavior

I expect distroAV to have NDI output

**Comment by RayneYoruka** [comment]
Sounds like firewall as per usual.

https://github.com/DistroAV/DistroAV/wiki/2.-Troubleshooting#firewall-settings--requirements

**Comment by juniper275** [comment]
> Sounds like firewall as per usual.
> 
> https://github.com/DistroAV/DistroAV/wiki/2.-Troubleshooting#firewall-settings--requirements

no, firewall is completely disabled

**Comment by BitRate27** [comment]
If you can see the Preview but not the Main output, it could be the format of your Main output is not supported. The NDI library we use does not support HDR output. Look for` [DistroAV] warning: unsupported pixel format` in the log file. If it says that, then you need to change the output format of OBS in order to send it out as NDI. Please let us know if this is the issue.

**Comment by juniper275** [comment]
> If you can see the Preview but not the Main output, it could be the format of your Main output is not supported. The NDI library we use does not support HDR output. Look for` [DistroAV] warning: unsupported pixel format` in the log file. If it says that, then you need to change the output format of OBS in order to send it out as NDI. Please let us know if this is the issue.

in the problem description there is also the link to the logs: 

https://obsproject.com/logs/hWOo9QIj8u8KQO8E

I don't have that warning and i don't use HDR...

Everything works fine except obs NDI output (main output and preview), NDItools screen capture also doesn't work

I can use every other NDI source on OBS (two PTZ camera and one encoder)

**Comment by BitRate27** [comment]
Thanks for providing the log file. It doesn't look like there is an issue with creating both Main and Preview output. I would look more towards the two network cards. You could be sending it on a network other than the one you think you are.

**Comment by RayneYoruka** [comment]
> > Sounds like firewall as per usual.
> > https://github.com/DistroAV/DistroAV/wiki/2.-Troubleshooting#firewall-settings--requirements
> 
> no, firewall is completely disabled

Some firewall in your network. If screen capture doesnt work then its something on your router / network blocking the traffic. Normally even wirh 2 network cards it should still work (I've run multiple and you can choose which one is the primary in NDI bridge)

**Comment by juniper275** [comment]
> > > Sounds like firewall as per usual.
> > > https://github.com/DistroAV/DistroAV/wiki/2.-Troubleshooting#firewall-settings--requirements
> > 
> > 
> > no, firewall is completely disabled
> 
> Some firewall in your network. If screen capture doesnt work then its something on your router / network blocking the traffic. Normally even wirh 2 network cards it should still work (I've run multiple and you can choose which one is the primary in NDI bridge)

No, i'm tracing with wireshark and It seems a mdns problem

**Comment by RayneYoruka** [comment]
> No, i'm tracing with wireshark and It seems a mdns problem

_NDI Discovery Server is an optional method to have NDI devices perform discovery. This can be beneficial in large configurations when you need to connect NDI devices between  or if mDNS is blocked._  5959 TCP.  
https://docs.ndi.video/docs/white-paper/ndi-related-network-ports .


This is exaplained on the NDI doc that it's listed within the firewall settings and requirements <3

**Comment by juniper275** [comment]
> > No, i'm tracing with wireshark and It seems a mdns problem
> 
> _NDI Discovery Server is an optional method to have NDI devices perform discovery. This can be beneficial in large configurations when you need to connect NDI devices between or if mDNS is blocked._ 5959 TCP. https://docs.ndi.video/docs/white-paper/ndi-related-network-ports .
> 
> This is exaplained on the NDI doc that it's listed within the firewall settings and requirements <3

mdns isn't blocked... don't answer randomly, there isn't  a firewall but a switch with direct connection between all devices (it's a test)

all other NDI sources are visible in OBS 

only OBS output and NDI screen capture have this behavior

**Comment by RayneYoruka** [comment]
Please take some time to read everything carefully. https://docs.ndi.video/docs/white-paper/ndi-related-network-ports
I hope you're able to figure out what is blocking your network traffic!

![image](https://github.com/user-attachments/assets/9b00109e-5fa0-4923-ab4e-23bb01e4cc51)

**Comment by juniper275** [comment]
no problem is MDNS, for some strange reason MDNS query related to OBS and OBS Preview is missing (first query with hostname)...

**Comment by juniper275** [comment]
@Trouffman i'm testing on the same computer and yes it's NDI bug

with two network card there isn't a MDNS reply to first DistroAV query but forcing to use a specific network card all working fine:

`Queries
    _ndi._tcp.local: type PTR, class IN, "QM" question
        Name: _ndi._tcp.local
        [Name Length: 15]
        [Label Count: 3]
        Type: PTR (12) (domain name PoinTeR)
        .000 0000 0000 0001 = Class: IN (0x0001)
        0... .... .... .... = "QU" question: False
`

`Answers
    _ndi._tcp.local: type PTR, class IN, DESKTOP-CC5TD0F (preview)._ndi._tcp.local
    DESKTOP-CC5TD0F (preview)._ndi._tcp.local: type SRV, class IN, cache flush, priority 0, weight 0, port 5964, target DESKTOP-CC5TD0F-00003ac0-ff98.local
    DESKTOP-CC5TD0F (preview)._ndi._tcp.local: type TXT, class IN, cache flush
    _ndi._tcp.local: type PTR, class IN, DESKTOP-CC5TD0F (main)._ndi._tcp.local
    DESKTOP-CC5TD0F (main)._ndi._tcp.local: type SRV, class IN, cache flush, priority 0, weight 0, port 5963, target DESKTOP-CC5TD0F-00003ac0-ff98.local
    DESKTOP-CC5TD0F (main)._ndi._tcp.local: type TXT, class IN, cache flush
`
I think it should be reported to those who develop NDI

Thanks
