### ISSUE TITLE
not installing to OBS

### ISSUE THREAD

**Issue by legallyyoursph** [DistroAV/DistroAV#1141]
### Operating System Version

sonoma

### OBS Version

30.2.3

### OBS Installation Method

exe

### DistroAV Version

latest

### DistroAV Installation Method

exe

### NDI Version

5

### Describe the bug

NOT APPEARING AND NOT FUNCTIONING IN obs 30

**Comment by Trouffman** [comment]
multiple issues opened at the same time. closing. please stick to one entry per issue.

Read the Wiki : https://github.com/DistroAV/DistroAV/wiki/1.-Installation
