### ISSUE TITLE
NDI RUNTIME NOT FOUND

### ISSUE THREAD

**Issue by legallyyoursph** [DistroAV/DistroAV#1143]
### Operating System Version

sonoma

### OBS Version

30.2.3

### OBS Installation Method

dmg

### DistroAV Version

latest

### DistroAV Installation Method

dmg

### NDI Version

5

### Describe the bug

NDI® Runtime not found.

Download the installer here:
http://ndi.link/NDIRedistV6Apple

DistroAV cannot continue and will not be loaded.
If this problem persists, please:
[Report an DistroAV Issue](https://distroav.org/report-bug)
-or-
[Uninstall DistroAV](https://distroav.org/kb/uninstall)

### Screenshots

![Screenshot 2024-11-16 at 12 33 12 AM](https://github.com/user-attachments/assets/167f7cae-7895-437c-9d5a-d554c3c37013)

**Comment by Trouffman** [comment]
multiple issues opened at the same time. closing. please stick to one entry per issue.
