### ISSUE TITLE
[Bug]: systemd-resolved support

### ISSUE THREAD

**Issue by travisghansen** [DistroAV/DistroAV#1144]
### Operating System Version

Arch Linux

### CPU

ryzon

### GPU

amd

### NDI Devices

All

### OBS Version

30.2.3

### OBS Installation Method

aur tytan

### DistroAV Version

6.0.0

### DistroAV Installation Method

aur/distroav 6.0.0-1 (+10 0.68)

### NDI Version

aur/ndi-sdk 6.0.1.r139791.20240506-1

### Describe the bug

I'm not so sure this is bug but more of a feature request. I run an avahi-less setup using systemd-resolved for local discovery. It appears there is currently a hard requirement on avahi so I'm wondering if it would be possible to support `systemd-resolved` as a resolver?

In addition, is it possible to manually specify an IP/port of a device so even if it's not on the broadcast network (or discovery doesn't work like in my case currently) that I can still connect?

Thanks!

**Comment by Trouffman** [comment]
Tha la for reporting this.

This is an NDI requirement and not something we can change at the plugin level.

Will close for now, if someone has a better solution, fell free to share..

**Comment by Trouffman** [comment]
For the record here is how you can manage manual connections with NDI

https://docs.ndi.video/docs/white-paper/discovery-and-registration/manual-connection
