### ISSUE TITLE
[Bug]: NDI|HX2 and NDI|HX3 frame skip/double frames

### ISSUE THREAD

**Issue by datamattsson** [DistroAV/DistroAV#1146]
### Operating System Version

macOS 14.6.1 (23G93)

### CPU

Apple M3 Max

### GPU

Apple M3 Max

### NDI Devices

ZowieTek 4K HDMI NDI Video Encoder, Magewell Ultra Encode HDMI Plus, Kiloview N60

### OBS Version

30.2.3

### OBS Installation Method

.dmg + self updates

### DistroAV Version

6.0.0

### DistroAV Installation Method

.dmg

### [Extra] Installation Steps

None

### NDI Version

NDI SDK APPLE 18:51:32 Jul 26 2023 5.6.0

### Describe the bug

I've used Magewell Pro Convert HDMI 4K Plus extensively with OBS the last year or so with great success. However, my requirements have changed slightly and I need to switch to NDI|HX2 or NDI|HX3. Both the ZowieTek and Magewell Ultra exhibit frame skips and double frames, multiple times per second in a 1080p60 feed. No setting seems to stop the stuttering. My reference recording with the Pro Convert skip a frame once every few seconds or so and not noticeable in the final production. Using the NDI Video Monitor, the skips and double frames can't be seen on any device.

If I switch the ZowieTek or Magewell Ultra to become SRT Callers to OBS, no frames are skipped.

### Steps to reproduce the problem

1. Enable NDI|HX2 or NDI|HX3 in 1080p60 on either device (suitable input: https://www.youtube.com/watch?v=Cyxixzi2dgQ use https://cobalt.tools to download the file)
2. Add NDI source to OBS.
3. Record a 60fps video and open it in VLC, step frame-by-frame with the 'e' key.

### Expected behavior

Stutter free NDI|HX2 and NDI|HX3 feed.

**Comment by RayneYoruka** [comment]
Sadly there is some inconsistencies with the plugin and HX, maybe in the future they might be solved. For now it's suggested to use NDI bridge to transcode the feed from HX to SpeedHQ or h264 if possible

**Comment by datamattsson** [comment]
Thanks for confirming @RayneYoruka. I'll use SRT for now but I rather use NDI. Hopefully this will be fixed.

**Comment by Trouffman** [comment]
NDI HX stream should be fine on NDI SDK 6 + DistroAV 6.
Please update your issue with your OBS log as well.

You can launch OBS with --distroav-verbose and --verbose to help diagnose it better.

FYI we do not have access to this device so we cannot debug / reproduce without your help.

**Comment by Trouffman** [comment]
Correct the NDI SDK you had was 5.6.0, the latest at this time is 6.0.1. 
Get the latest for your system at : https://github.com/DistroAV/DistroAV/discussions/831

**Comment by datamattsson** [comment]
Ok, frustrating. Why is NewTek making this so hard on users? I now have the correct version installed, thanks for the link. I will retest and come back.

`NDI SDK APPLE 09:05:57 May  6 2024 6.0.1`

**Comment by paulpv** [comment]
To be precise, that is `--distroav-verbose` (two dash prefix)

**Comment by paulpv** [comment]
(TIL that I can edit other people's comments? :) )

**Comment by RayneYoruka** [comment]
> (@Trouffman TIL that I can edit your comments? :) )

Mistakes were made? No problem I'll fix your mistake! /s

**Comment by datamattsson** [comment]
> Any update on this.

I plan on doing one last comparison between my baseline (the Magewell Pro Encoder with full NDI) against the ZowieTek and the KiloView N60 - with all the updates and flags you mention. Since this setup is mobile, it's most of the time packed up. I'm doing a production this weekend and will try make the time to capture the data you're asking for.

**Comment by datamattsson** [comment]
With everything updated to the current versions I did a comparison between the Magewell Pro Convert (full NDI) and ZowieTek using both HX2 and HX3. Under these circumstances I could not find consistent stuttering artifacts like I did prior across all tested devices.

Between then and now I did find out that the WiFi I was using at that time wasn't optimal for what I was trying to do. The tests I ran today was on my "production" WiFi and I have no means going back to the setup I had back then.

Nonetheless, this is a non-issue at this time.

**Comment by Trouffman** [comment]
@datamattsson quick update on this (closed) ticket. I noted that this is resolved so far.

I have a Magewell Pro Covnert HDMI 4K (not the Plus versions) and there is no settings to enable HX.

Also the official website does not seems to have HX either. Source : https://www.magewell.com/products/pro-convert-hdmi-4k-plus

Also OBS NDI does not send HX, only receive :)

As I spent some time testing, wanted to give a final update.

**Comment by datamattsson** [comment]
> I have a Magewell Pro Covnert HDMI 4K (not the Plus versions) and there is no settings to enable HX.

I used the Magewell Pro Convert as my reference. Full NDI always works flawless. I have a Magewell UltraEncode that does HX.
