### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mabangeamen** [DistroAV/DistroAV#1149]
### Operating System Version

Windows 10

### CPU

12,0 GB

### OBS Version

30.2.3

### OBS Installation Method

exe

### DistroAV Version

6.0.0

### DistroAV Installation Method

exe

### NDI Version

4.14.1

### Describe the bug

![image](https://github.com/user-attachments/assets/5cc9c11b-6a6f-4aa2-8e05-037f058b1ce7)

### Steps to reproduce the problem

![Capture](https://github.com/user-attachments/assets/10fdd6db-63ca-4cc1-bdcd-176bd4283ea5)
![Capture](https://github.com/user-attachments/assets/edc20845-a880-4a6f-a03c-60d5426553ea)

**Comment by BitRate27** [comment]
You need to uninstall obs-ndi from windows.

**Comment by mabangeamen** [comment]
I did Uninstall it

**Comment by BitRate27** [comment]
Then you need to delete it manually https://github.com/DistroAV/DistroAV/wiki/1.-Installation#windows-2
