### ISSUE TITLE
[RFE]: Local Network choosing feature

### ISSUE THREAD

**Issue by klikkerTV** [DistroAV/DistroAV#1170]
### Is there an existing issue or feature request for this?

- [X] I have searched and did not find a similar issue or feature request

### This feature does not exists on the latest available release of DistroAV nor in the upcoming PR?

- [X] I have checked and this is not available on the latest DistroAV version nor planned

### Explain the context or expected use-case of the feature request (problem, new NDI feature, ...)

Im actively using your NDI-DistroAV plugin in OBS and now it works much better than Teleport or xOBSBeam.

My only problem is that your plugin doesnt have any local network choosing feature like the others. 
Please put this feature in your plugin if you can its so important for me.

I using it for two PC streaming, and have a dedicated network for DistroAV.

I like to put one network for downloading etc, and the other separate network is for DistroAV.

### Solution Idea or Feature description

It is really similar to the other alternative plugins, you can choose from which local area network do you want to receive the data in OBS.

### How this feature can benefit the community?

You can seperate downloads, droidcam obs, or other wifi cameras from NDI to avoid screen lags and stutters.

### Are you able to contribute to this feature?

Im only a streamer, so i dont think so.

**Comment by RayneYoruka** [comment]
You can already do this with [NDI Access Manager (From NDI tools)](https://docs.ndi.video/all/using-ndi/ndi-tools/ndi-tools-for-windows/access-manager#advanced-settings). You select what NIC should be the preferred one systemwide. 

NDI is mostly used with gigabit or higher network speeds as they [recommend](https://docs.ndi.video/all/getting-started/white-paper/bandwidth). You can apply redundancy if you know how and NDI will load balance between the multiple nics.

**Comment by colaH16** [comment]
is it works?
I'm trying to capture windows from mac obs.
I set this on windows. but.. not works.
Also, Mac's access manager does not have such a setting.
