### ISSUE TITLE
Multiple Audio Tracks Over NDI Stacking

### ISSUE THREAD

**Issue by cflynn-ua** [DistroAV/DistroAV#303]
Good Afternoon OBS-NDI Team,

This one has been a head-scratcher for me, for some time now.  I am using Skype with NDI outputs into OBS, and the video works swimmingly.  However the audio does something strange, when attempting to have three people on the call:  it decides to stack the non-native callers (so the other two callers) onto the same audio track, with my native-track remaining  separate.  Is there a way to split an incoming NDI signal into three separate tracks?  I've played with Voicemeeter Potato to little avail, have tried using Virtual Audio Cables to create three distinct NDI out sources, but no dice.

My suspicion is that this is something native to NDI, and not OBS, but just wanted to bring the discussion to the experts :-)

Cheers!

**Comment by bmurray** [comment]
I have been seeing the same issue. Does the NDI protocol support multi-channel audio? This is a deal-breaker for us when using Skype. We have been working around it, barely, but don't have a solution.

**Comment by paulpv** [comment]
Please try on https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC.
