### ISSUE TITLE
No Skype conference in OBS

### ISSUE THREAD

**Issue by VaporToLife** [DistroAV/DistroAV#359]
Hi,
I have a problem with Skype integration in OBS
I have all NDI programs exactly after instructions on windows 10 installed.
1. windows installer
2. ZIP file
3. NDI 4.0 runtime
I can now also select NDI in OBS under source add.
I can also mark a source with Skype.
If I press OK, nothing happens.
I can not see the image signal with the connected skype contact or it is not displayed.
my settings can be seen on the screenshot
![Screenshot OBS Skype NDI Quelle](https://user-images.githubusercontent.com/56264656/66324926-a6530b00-e926-11e9-8cd8-6aeec36d2435.png)
.

PLEASE HELP ME !!!!!!!!

THANKS

**Comment by doggy8088** [comment]
I have the same problem if I use [Windows 10 version of Skype](https://www.microsoft.com/zh-tw/p/skype/9wzdncrfj364) app that download/installed from Microsoft Store.

 If you install the [Windows version of Skype](https://go.skype.com/windows.desktop.download), all problem gone. 

I don't know why.

**Comment by Palakis** [comment]
@doggy8088 Does it work in NDI Studio Monitor when outputting from the MS Store version of Skype?

**Comment by doggy8088** [comment]
I tried `NDIAnalysis.exe`. It's not working.

**Comment by Palakis** [comment]
@doggy8088 NDIAnalysis.exe analyzes advanced stuff like timestamps. You need to use the Studio Monitor app.
