### ISSUE TITLE
Source Name, phone as webcam is missing

### ISSUE THREAD

**Issue by Sean30n** [DistroAV/DistroAV#360]
only desktop obs is there. the phone was showing up but disapeared and now i cant fix it. tried reinstalling obs and NDI on both phone and pc

**Comment by unknowndomain** [comment]
@Sean30n Issues with sources not appearing are usually due to the source not being on the same subnet as the host.

**Comment by WreckWren** [comment]
This issue is still the only way I have ever seen this plugin displayed; failing to find sources that are clearly there and immediately found by studio monitor.

Is this ever going to be fixed?

**Comment by unknowndomain** [comment]
Remember this is an open source project, it may be frustrating but everyone does what they can.
