### ISSUE TITLE
audio is desynced 

### ISSUE THREAD

**Issue by benniadioz** [DistroAV/DistroAV#379]
The Audio Stutters are away since i did make a new ndi source for every audio and video source to my encoding pc and Disabling Device Timestamps on the desktop audio and setting NDI to Network sync on the encoding system.But now i have a new Problem , the stutters are absolutely away but my audio from the Game and my Voice isn´t synced to the Stream...Must i add a delay to the ndi sources of the encoding Pc? And which obs you start first? Gaming pc or encoding pc? Much Greets from Germany , i hop i can get an answer to make this problem go away....im slowly going crazy...

**Comment by paulpv** [comment]
Is this still an issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?
