### ISSUE TITLE
[RFI] Integrate BirdDog's Talk back audio

### ISSUE THREAD

**Issue by unknowndomain** [DistroAV/DistroAV#394]
Some products like those made by Bird Dog include talk back audio i.e. a 2nd audio channel that is distinct fromt the main video signal, this is useful for having a microphone at the same time as the video audio, however it's not clear that this is supported by this plug-in and would be great if it were.

**Comment by Palakis** [comment]
@unknowndomain Could you link me to documentation regarding this feature, please?

**Comment by unknowndomain** [comment]
This is where I read about it, all of the kit they sell has some kind of talk back type intercom feature.

https://www.bird-dog.tv/commslite-overview/

I presume it's a 2nd bi-directional audio stream in the NDI protocol, but I am not familiar beyond this. There are some super helpful people at BirdDog, I could ask one of them to speak to you about this.

**Comment by unknowndomain** [comment]
Also supported here:
https://apps.apple.com/us/app/ndintercom/id1459496365

**Comment by Trouffman** [comment]
Implementation is not clear, and act more as an independent second NDI (audo) stream back.

This will be set aside for now as there is no documentation available on the integration.

If that is the case, a source with the producer mic and a NDI filter output should achieve the same. Not sure how this can be selected on the BD devices (haven't seen much in the config from some of th BD unit I have access too.)
