### ISSUE TITLE
The output video is so lag.

### ISSUE THREAD

**Issue by zdev99** [DistroAV/DistroAV#413]
My PCS are connected to the same router by cat5e cables. This router is from the company and I have 300mbps. The problem is that on my streamer pc catch the output video of gaming pc, It looks good quality (1080p) but in so many moments the frames goes to 15-20 more or less and later to 60fps. What can i do?

**Comment by marcusademola** [comment]
Maybe check

1) Receiving PC (that runs OBS ) specs that is able to perform FullHD
 - e.g. is the problem when you do similar set-up through USB

2) Network, perhaps there is some other traffic

Please provide more details on the set-up here, maybe someone can help better.

**Comment by paulpv** [comment]
Is this still an issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?
