### ISSUE TITLE
OBS Can't Open after install (MOJAVE 10.14.6)

### ISSUE THREAD

**Issue by adamesq** [DistroAV/DistroAV#443]
OBS was working great.

Installed NDI Integration & runtime.

OBS Crashes on launch. I can't find any way to work around it. 

https://pastebin.com/9A68DBBV

**Comment by KonajuGames** [comment]
I have the same on Windows.  The module name "unknown" version "0.0.0.0" with timestamp "0x00000000" is the obs_ndi.dll.  It is a NULL reference in obs_ndi.dll (exception code 0xc0000005 with fault offset 0x00000000).  This looks to be the same error as shown in the Mac crash log above.

> Faulting application name: obs64.exe, version: 24.0.3.0, time stamp: 0x5da1792b
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x2e9c
Faulting application start time: 0x01d613eb60c869dc
Faulting application path: C:\Program Files\obs-studio\bin\64bit\obs64.exe
Faulting module path: unknown
Report Id: a9ba74ef-63a7-4994-bef4-ee64bc5a890e
Faulting package full name: 
Faulting package-relative application ID:

**Comment by KonajuGames** [comment]
Just saw the note on the obs-ndi 4.8.0 release about requiring OBS v25 or above.  Saw in the crash log that my OBS was v24.  Updated and the crash on launch no longer happens.

**Comment by gr01d** [comment]
This is on Windows:
I am using OBS 26.0.2 with the  NDI 4.9.0 (runtime 4.5.1) and the same thing. Crashes OBS after I enabled output, can't disable it now. Upon start up it crashes OBS before I can do a thing.

**Comment by paulpv** [comment]
Is this still an issue in 4.13.0?
