### ISSUE TITLE
No video feedback in Mac OBS 25.0.7 with 4.8.0 and NDI framework 4.5.1, audio seems fine

### ISSUE THREAD

**Issue by DrConflict** [DistroAV/DistroAV#444]
Edit: Rolling back to Runtime 4.0 from https://ndi.palakis.fr/runtime/ worked fine with plugin 4.8.0. So it would seem Runtime 4.5.1 is broken.

I have no video feedback in OBS 25.0.7 using NDI OBS plugin 4.8.0 and NDI framework 4.5.1. I do get audio feedback in my mixer settings, but no video. It worked fine earlier and have used it many times in the past. When I try it with Newtek NDI Video Monitor app it works fine with video so it seems either related to OBS or this plugin. Anyone know a solution to my issue?

Mac OS 10.15.4 and all latest software versions.

![Screenshot 2020-04-17 at 22 40 06](https://user-images.githubusercontent.com/48632976/79612170-70c08300-80fc-11ea-8825-b805f1a6bace.png)

**Comment by dataopt** [comment]
I ran into the same issue and I rolled back to runtime 4.0.0 as mentioned in your EDIT and everything is working as expected.

**Comment by high-solutions** [comment]
do you still have this problem (i tried the 4.5.1 runtime and the 5.0 runtime and i get black screens with both).
Problem is that the 4.0 doesn't support NDI 4/5.
So i need to choose now to use NDI from other sources (runtime 4.0), or my NDI camera's with NDI-4 (runtime 4.5.1 or above), but i can't use them at the same time.....

**Comment by paulpv** [comment]
Is this still an issue with 4.13.0?

**Comment by paulpv** [comment]
Seems related to https://github.com/obs-ndi/obs-ndi/issues/928
