### ISSUE TITLE
NDI source showing up as black screen

### ISSUE THREAD

**Issue by sch00lb0yq** [DistroAV/DistroAV#464]
When I successfully have the latest obs version 25 and after NDI 4.8.0 setup. I restarted my pc and other laptop with the same installation,  i put one as main and add the NDI source on my laptop with the standard settings. Every time I do this it will pop up as a black screen! What can i do?

**Comment by tt2468** [comment]
You probably have a firewall preventing proper communication.

**Comment by Kaizasouza** [comment]
I have the same issue, im using a iPhone 7plus with the latest update and a 2010 MacBook Pro, with Mac Os High Sierra V10,13.6 As i add source select settings it recognises it as a source however when i ok the screen is black with a thin red outline. You mentioned Firewall preventing. I would like a little more information please as OBS has allowed permissions for connections. I then switched off my firewall on my mac and it still didn't work. Still the black screen. Are you able to assist further.

**Comment by sch00lb0yq** [comment]
Well I eventually fixed it, the black screen was caused by I wasn’t showing anything on my streaming device so it picked up de black screen from obs!

**Comment by sander1** [comment]
> I have the same issue, im using a iPhone 7plus with the latest update and a 2010 MacBook Pro, with Mac Os High Sierra V10,13.6 As i add source select settings it recognises it as a source however when i ok the screen is black with a thin red outline. You mentioned Firewall preventing. I would like a little more information please as OBS has allowed permissions for connections. I then switched off my firewall on my mac and it still didn't work. Still the black screen. Are you able to assist further.

Running into this exact same issue with an almost similar setup:
- 2011 iMac with macOs High Sierra (10.13.6)
- OBS 25.0.8
- NDI runtime 4.5.1 and NDI plugin 4.9.0
- iPhone 6S with NDIHX camera app

I do see my NDI source and I can add it to a scene:

![Screen Shot 2020-05-26 at 02 54 16](https://user-images.githubusercontent.com/104684/82850485-e3433080-9efc-11ea-872f-834573b63311.jpg)

After that I can see it receives audio, but screen is just a tiny red dot:

![Screen Shot 2020-05-26 at 02 54 24](https://user-images.githubusercontent.com/104684/82850508-f9e98780-9efc-11ea-88da-ef144f6723c2.jpg)

Stretching it just shows a blank screen. Any help appreciated!

**Comment by sch00lb0yq** [comment]
I fixed it, my problem was I wasn’t showing anything on the NDI stream pc so it turnes up on the stream pc as a black screen!

**Comment by 360disrupt** [comment]
I can click in the source section on NDI and it shows the camera of my iPhone. But on the main screen also when I record I still got a black screen beside the other sources e.g. a logo image.

**Comment by MaximRouiller** [comment]
On Windows, enabling Media Streaming in the `Network and Sharing Center` fixed that issue for me.

It must have toggled something on the local firewall.

**Comment by trulow** [comment]
This still seems to be an issue as of Jan 2022, at least when using MacOS on Monterey 12.1. I've fixed the issue by using the NDI Runtime v4.0.0

https://ndi.palakis.fr/runtime/ndi-runtime-4.0.0-macOS.pkg

**Comment by high-solutions** [comment]
the downgrading fix is only partly fixing it....
so i've got my black screen NDI fixed but now my other (already working) NDI feeds are displaying a nice NDI picture with the text that is should update to NDI 4 or higher to make this work......

**Comment by degroteprijs** [comment]
I had the same problem and downgrading helped to show a NDI stream in OBS. Strange that there still is nog definite solution for this

**Comment by TheMy7teriou7One** [comment]
I'm having the same problem I'm using a BZB gear camera and it was working fine about a month ago but has been showing up as just a red square now.

**Comment by paulpv** [comment]
Is this still an issue in 4.13.0?

**Comment by byontea** [comment]
> Is this still an issue in 4.13.0?

Yes, same problem with Acer Nitro with GeForce RTX.

**Comment by paulpv** [comment]
Does `NDI Studio Monitor` have the same problem?

I am tempted to close this and wait for a new report w/ maybe more/new info.

**Comment by high-solutions** [comment]
@paulpv it was never a problem in NDI studio monitor, only in OBS.

i can try this afternoon if the issue is still ongoing

**Comment by Trouffman** [comment]
Try on latest version and if the blank screen still happen. >> On the source do :  right click > interact > maximize (or Ctrl + F).

**Comment by Trouffman** [comment]
The root cause has been identified :
- We sometimes create a "blank frame" that is 0x0 pixel, this happens when the frame is drawn bu not updated correctly.
Seems that this will be fixed at the same time as the audio-only fix set for release on v6.

This is hard to reproduce consistenly.

**Comment by Trouffman** [comment]
yes ! for everyone that had this issue please upgrade to the latest DistroAV v6 version.

There was a lot of change when we release v6. Including how the video start on a new NDI source.

This will be closed and anyone with the issue ( on v6 will need to open it's OWN issue + provide a log < No obs log = no way to diagnose).

Thank you all for contributing to this issue.

**Comment by ryanfur** [comment]
> Does `NDI Studio Monitor` have the same problem?
> 
> 
> 
> I am tempted to close this and wait for a new report w/ maybe more/new info.
> 
> 
> 
> @Trouffman 

I have the problem where the computer outputting the NDI can see it on the monitor but now the computer reciving can see that there is a NDI input but the monitor only shows black

**Comment by RayneYoruka** [comment]
> have the problem where the computer outputting the NDI can see it on the monitor but now the computer reciving can see that there is a NDI input but the monitor only shows black

Firewall. You may need to add the ports manually for inbound and outbound on the computers that you wish the NDI signal.
**On the computers.. not in your router.** 

https://github.com/DistroAV/DistroAV/wiki/2.-Troubleshooting#firewall-settings--requirements
