### ISSUE TITLE
LTC Source

### ISSUE THREAD

**Issue by reustaquiojr** [DistroAV/DistroAV#481]
Would be possible to atach LTC timecode into NDI feeds generated by the plugin ?

Somethink like this on Newtek Connect Pro that has automate external timecode configuration (including 24-hour wraparound) simply by plugging in a compatible LTC timecode source. Image above !

![image](https://user-images.githubusercontent.com/36238220/81355794-eee1cb00-90a5-11ea-9752-6209ff6c866e.png)

**Comment by Trouffman** [comment]
This is genlock https://docs.ndi.video/docs/white-paper/synchronization

This will not be implemented for now. (Required advanced SDK)
