### ISSUE TITLE
Digital Desync when using NDIHX camera app on IOS

### ISSUE THREAD

**Issue by gregk610** [DistroAV/DistroAV#485]
Audio desyncs when a NDIHX camera app transmits audio, and is transitioned into OBS.

**The setup:**
- OBS 25.0.8
- NDIHX Camera App
- Webcam (Or NDI Camera such as PTZ Optics NDI 30x)
- Media source in OBS (song, or music)

**During stream to youtube:**
-    First scene:   Webcam and media playing
-    Second scene: Iphone running NDIHX camera app
-   if you transition from first to second scene, your audio at Youtube (20 second delay) will coincide with garbled audio on the Youtube preview.   If you switch back to webcam, it will return to Normal.

**Quick fix:**
   On the Iphone NDIHX application, disable any audio from the device.   
   Click the gear icon, and mute the microphone.

**Patch Request:**
  

-  Is there a way on the OBS-NDI integration to disable audio at OBS / NDI source ?  This will allow the producer to disable audio in case someone forgot to disable the microphone from the application.   
- Or is this a NDI vs NDIHX issue?

https://youtu.be/USP82ekgLwQ?t=239
This segment shows the audio transitioning  from an NDIHX feed to a PTZ Optics NDI Camera.

**Comment by walterav1984** [comment]
Duplicate issue see #448 it also lists the mute mic in the NDI-HX source workaround.

**Comment by paulpv** [comment]
Interesting.
The current code for Sync `Network` vs `Source Timing` is:
https://github.com/obs-ndi/obs-ndi/blob/4daba126d0fc294a9f38213d9fb0a5a6b914c4ee/src/obs-ndi-source.cpp#L368-L380

I didn't write this code, so I am just saying as the current code maintainer that this option is obviously there for a reason.
Is the existence of this option enough to close this Issue?
Is there anything that should or needs to change?
