### ISSUE TITLE
So my NDI works but doesn't work over lan cable

### ISSUE THREAD

**Issue by badmouthkeyboard** [DistroAV/DistroAV#499]
So I've been streaming normally for the past few days. But I reformated my gaming PC. So I reinstalled obs, ndi, etc.

My setup is like this
![pUDwvtZ](https://user-images.githubusercontent.com/65778241/82685527-efbe5380-9c86-11ea-81b8-76e68069f3ad.png)

But right now my issue is that my display from gaming pc is being transfered to my streaming pc via WiFi. Even if I remove the ethernet cable it still shows the ndi source, but if I remove one pc from the wifi connection, the ndi source is lost. And cannot be detected without wifi. Then my obs keeps crashing and this is the crash log. One guy from discord in OBS told me to report here. 
https://obsproject.com/logs/KrtlcrCCuHX7QSBD

I hope I also get help here about how to fix my stream. I want the streaming pc to use the cable again to get display from gaming pc. Thank you so much

**Comment by paulpv** [comment]
Is this still an issue in 4.13.0?
