### ISSUE TITLE
Cannot see NDI in Tools OBS yet download appears successful

### ISSUE THREAD

**Issue by T4TD** [DistroAV/DistroAV#505]
I appear to have downloaded the Plugin successfully; Firewalls were off; Followed all the instructions. But cannot see it has been successfully installed in the Tools of OBS.
I am not a programmer. I am new to this.
I uninstalled, reinstalled - restarted several times. Still nothing works.
I see some are having issues with V25.0.08 which is what I am working with.
Please help??

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?
