### ISSUE TITLE
Unable to install obs-ndi: Ubuntu 20.04 for unmet dependencies

### ISSUE THREAD

**Issue by starapple2** [DistroAV/DistroAV#508]
Hi, I just attempted to install obs-ndi .deb packages. I got the following message when attempting the obs-ndi_4.9.0-1_amd64.deb.

"Unable to install obs-ndi:
The following packages have unmet dependencies:
Package created with checkinstall 1.6.2"

Would appreciate any feedback.
Thanks.

**Comment by starapple2** [comment]
Although the 4.9.0-1 deb release is said to be for OBS Studio >25.x, it really is for 25.0.7 or above.
I installed 4.7.1-1 on OBS Studio 25.03 with success.

**Comment by PatrickLohan** [comment]
Try using the PPA from OBS directly. Installs the latest stable which then can be used with 4.9.0-1

However, I can't seem to get any output on my stream pc. Did you get yours running? If so, what were the steps?

**Comment by starapple2** [comment]
> Try using the PPA from OBS directly. Installs the latest stable which then can be used with 4.9.0-1
> 
> However, I can't seem to get any output on my stream pc. Did you get yours running? If so, what were the steps?

I'm wary of using the various PPAs with Ubuntu Studio (20.04 LTS) because I find that updates and upgrades tend to make some deletions that put everything in a tailspin. Hence my decision to use an earlier version that's compatible with the OS.

That said, while I've added the plugin, and it shows in the OBS Studio interface, I don't have the NDI option in my Skype on Ubuntu. That seems to be a Windows and Mac option. I'll have to try at a later stage

**Comment by PatrickLohan** [comment]
Are you streaming from one Ubuntu pc to another? If so, do you get a picture on the 'host' obs instance?

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?
