### ISSUE TITLE
NDI plugin not creating references for multiple copies of a source

### ISSUE THREAD

**Issue by omniscientdeveloper** [DistroAV/DistroAV#511]
I am using scan converter via your OBS NDI plugin to send video to a capture computer. In the OBS scene collection there are multiple references to the same source. It seems the plugin is creating new connections for each reference, each about 150Mb. The number of connections is causing my network link to DDoS, because it is going over the capacity of the GbE link. If the same source is being requested, shouldn't the plugin use a reference?

Is there some way around this? Is there some donation that could be made to fix this? If so, how much?

**Comment by Trouffman** [comment]
Closing old issues. Please use the latest version of DistroAV / OBS and open a new issue if this persist.

This is fixed in latest distroAV version > option : behavior
