### ISSUE TITLE
Frame stutter and latency drift

### ISSUE THREAD

**Issue by digitalis99** [DistroAV/DistroAV#531]
I've noticed a problem that seems to be new to 4.9.0.  When receiving an NDI video stream over the network, there are very occasional frozen frames for a very short period of time.  These frozen frames seem to force the plugin to resume rendering frames where it left off, rather than skipping the frames that should have been displayed during the freeze.  As a result, the video latency increases over time.  Over the course of about 30 minutes of recording, I'm getting around 10 frames worth of latency increase at 25p.  I'm going to drop back to 4.8 to see if that eliminates the problem.  Recording the NDI video feed on the same system using Newtek's Studio Monitor doesn't exhibit this problem.

obs-ndi 4.9.0
OBS 25.0.8
Win10 Pro

My NDI sources are set to "source" sync.  I have no idea how that differs from "network" sync, as the sources are coming in via the network.  Surely there's a better naming scheme that can more accurately describe sync.

**Comment by digitalis99** [comment]
I tested with 4.8, and it exhibits the same problem.

**Comment by unknowndomain** [comment]
What kind of network connection are you using? Wi-Fi or Ethernet?

**Comment by digitalis99** [comment]
Wired GigE.  I've actually tuned both OBS and Studio Monitor to the same NDI feed, with both of them running on the same machine, and watched as the OBS preview slowly increased in latency over time.  Studio Monitor latency was fixed, but OBS' latency kept getting longer at a very slow pace.

**Comment by ccristob** [comment]
Did you ever find a workaround for this? I'm experiencing the same thing.

**Comment by digitalis99** [comment]
Nope.  It's extremely frustrating.  I'm going to have to switch to vMix.
