### ISSUE TITLE
Macbook Pro Broadcasting NDI to Windows PC has distorted image.

### ISSUE THREAD

**Issue by bumbleparrot** [DistroAV/DistroAV#535]
I have the latest version of OBS on a Windows and Macbook Pro.

Both have also the latest version of NDI.

When I broadcast via NDI on the Macbook Pro to the Windows PC, the output image is distorted. What's strange is that the NDI preview looks fine.

See images below. This is my first time posting an issue so please feel free to ask me for any required details.

[Distored](https://drive.google.com/file/d/1_DBK_No8xPSDTpO5EED3mkk-HM4Jasy9/view?usp=sharing)
[Preview looks okay](https://drive.google.com/file/d/1-KOTbPrfPptV3Zfc9NsTGG-P1kkZ9WwZ/view?usp=sharing)

The reverse (PC broadcasting NDI to Macbook) works fine.

**Comment by bumbleparrot** [comment]
Has anyone run into this issue?

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?
