### ISSUE TITLE
OBS Crashed when NDI Source's internet is Slow

### ISSUE THREAD

**Issue by sorn7chanratha** [DistroAV/DistroAV#544]
I am using PC for streaming and Laptop to connect group people via Skype. I notices that OBS always crashed when i tried to add NDI Source from other laptop that their internet very slow. 
I also tried reducing bandwidth to Low, YUV Range to Partial, and playing around Sync and Latency but it doesn't help.

**Comment by Trouffman** [comment]
Closing old issues. Please use the latest version of DistroAV / OBS and open a new issue if this persist.
