### ISSUE TITLE
NDI dedicated Audio output filter outputs garbage

### ISSUE THREAD

**Issue by nettings** [DistroAV/DistroAV#549]
This issue may be related to #548.

Source is
OBS 25.0.8/obs-ndi 4.9.0 on Windows 10 Rev 2004
Sink is
OBS 25.0.7-575-gaef10d46/obs-ndi c725201 on openSUSE Tumbleweed.

When I try to use the dedicated audio output filter on the source, I receive a garbage signal on the sink that immediately maxes out the NDI Source meter in the Audio Mixer at anything above -inf fader position. That strongly suggests utterly random numbers coming in.

Can this be a network endianness issue?

**Comment by nettings** [comment]
It may be that the actual problem is that _receiving_ audio is broken on Linux, and that the NDI audio output filter is not to blame. Can't test right now, but will retry asap. That would mean this is not a bug, and #548 is the root cause for both issues.

**Comment by paulpv** [comment]
Related to #548 ? I think there are several other "distorted" type of related issues.
