### ISSUE TITLE
OBS crashes when multicast is configured in specific way 

### ISSUE THREAD

**Issue by AvrumFeldman** [DistroAV/DistroAV#550]
Hi,

I had set my NDI access manager to use multicast and set the net mask to `225.225.225.252`. as long that was the setting configured  OBS would instantly crash on launch.

I'm not so well versed in multicast (vs unicast) and it could be that my mask was an impossible configuration for multicast (an error on my end) but I would prefer a warning instead of an crash. 

Please let me know what files/logs are needed and I will upload them.

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?
