### ISSUE TITLE
Feature Requst: deactivate source when not in use

### ISSUE THREAD

**Issue by denizkoekden** [DistroAV/DistroAV#554]
We use OBS-NDI for connection between CasparCG and OBS. When CasparCG-Playback is active, all scenes are overlayed by CasparCG and we can't see the Camera-Sources underlaying. But we have to have NDI-Source on Top of all scenes, so we can playout Graphics on all Scenes. So the solutions should be the "deactivate when not in use"-Option, which normally every Source in OBS has. But OBS-NDI under Windows doesn't. Is this planned or is there a workaround?

Regards,
Deniz

**Comment by nettings** [comment]
Not sure I understand your usecase, but OBS cannot "deactivate" an NDI source - the source doesn't know or care if it's being actively displayed by OBS.
If you have an NDI source on top of a camera source in a scene, and you want to see the camera when there is no signal coming via NDI, I think you are out of luck. Duplicate your set of scenes, and switch between them instead.

**Comment by nettings** [comment]
Also, this seems to be a duplicate or at least closely related to #553.

**Comment by tt2468** [comment]
@nettings The source can know if it is being displayed or not, as the tally functionality hooks into the appropriate signals already. Sources like the VLC source have similar functionality to what is being requested. We'll just have to find a good way of implementing it.

**Comment by nettings** [comment]
@denizkoekden, @tt2468, sorry for spreading confusion. I took "NDI source" to mean that you are sending an NDI signal _from_ OBS to somewhere. Of course you were using OBS terminology and meant a video source within OBS, which strictly speaking would be an NDI _sink_, hence my mistake.

**Comment by tt2468** [comment]
Ok so you are talking about the filter aspect of the plugin then?

**Comment by denizkoekden** [comment]
Better late than never.

Here again our usecase explained:

Four cameras are connected to a Decklink Quad card, OBS serves as a software image mixer and CasparCG we integrate via NDI.

When I run a video in CasparCG or for example we take a break and play a pause video I no longer see the cameras in the multiview. Every multiview View just shows the NDI-Source. If the NDI Plugin could recognize if the Scene is enable or disable and deactivate itself if the scene is disabled my problem should be fixed. :)

**Comment by haakonnessjoen** [comment]
We have another usecase for this feature. We are using OBS with a lot of NDI video sources coming into it. But we only show one source at the time. If all NDI sources are active at the same time, it overflows the network card. It would be so awesome if the NDI plugin had something like the VLC plugin has. (stop when not visible, restart when visible)
As an option of course, not to change the normal behaviour of the plugin. We could throw a few dollars at this if someone is interested.

**Comment by yetieater** [comment]
This feature would be very useful! I'm encountering network-related performance issues when running multiple NDI sources and sinks

**Comment by Trouffman** [comment]
This has been made possible in DistroAV 6.
Please update to the latest version of the DistroAV plugin.
