### ISSUE TITLE
Please document the requirement of avahi-daemon on Linux

### ISSUE THREAD

**Issue by DataBeaver** [DistroAV/DistroAV#557]
I spent a couple hours figuring out why my attempts at setting up a two-PC streaming setup were not successful.  Between two Linux PCs it worked out of the box but I couldn't get Linux to see any sources nor advertise itself as a source.  Tcpdump and ss showed no mdns traffic or open mdns sockets.  Eventually it dawned on me that the Linux version of libndi doesn't do mdns itself but instead relies on avahi-daemon, which I did not have installed.  After installing it NDI immediately started working as it should.

**Comment by tt2468** [comment]
What distro are you on? I'll add this, but I want to understand what OS's include it and what don't.

**Comment by DataBeaver** [comment]
A pretty customized installation of Debian unstable.  I don't run any desktop environment (just Sawfish as WM) and use sysvinit instead of systemd.

**Comment by Malex14** [comment]
On Archlinux it is also not installed or enabled by default. It would have saved a lot of time if there was a small notice to check avahi-deamon is running.

**Comment by Trouffman** [comment]
This should be in the wiki by now.
