### ISSUE TITLE
ndi plugin not showing up in tools

### ISSUE THREAD

**Issue by oulawithdebo** [DistroAV/DistroAV#563]
I have uninstalled and reinstalled everything more than once. the obs-ndi plug in is not showing up under tools. Please help. Thanks.

**Comment by NirodhaAvidya** [comment]
Same here. Installed on primary pc without issue. Secondary pc will not work. Un/Reinstalled OBS and NDI several times. Verified plugin files installed to proper location. Verified OBS-Studio firewall permissions.
Windows 10 Pro x64 v2004 19041.508
OBS 26.0.2
obs-ndi-4.9.0-Windows-Installer
obs-ndi-4.9.0-Windows (separate attempt)
ndi-runtime-4.5.1-Windows

**Comment by codegrue** [comment]
Just in case it's relevant, I found this in my OBS log file:

[obs-ndi] CPU unsupported by NDI library. Module won't load.

**Comment by Pysis868** [comment]
Wish it was more obvious, like when, for some reason on one of my many application restarts, it didn't think I have the NDI framework installed and showed an additional dialog box telling me that..
My CPU:
```
> less /proc/cpuinfo
model name      : AMD Phenom(tm) II X6 1090T Processor
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxenopl tsc_reliable nonstop_tsc cpuid aperfmperf pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt cpb hw_pstate npt lbrv svm_lock
```

I have a similar one that can;t handle USB3 through an expansion card except for file transfer, and doesn't support VR without SSSE3 I think as well..

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?

**Comment by Pysis868** [comment]
Installed packages:
```
obs-studio.x86_64 30.0.0~beta3-2.fc39
obs-studio-libs.x86_64 30.0.0~beta3-2.fc39

libndi-sdk-5.5.4-2.fc39.x86_64
obs-ndi-4.11.1-3.fc39.x86_64
libndi-0.0.1-8.gitc14b40c.fc39.x86_64
```

```
> ls /usr/share/obs/obs-plugins/obs-ndi/
locale/

> ls /usr/lib64/libndi*
/usr/lib64/libndi.so.0@  /usr/lib64/libndi.so.0.0.1*

# Cleaned that manual script-installed version and installed repo package instead.

> ls /usr/lib64/libndi*
/usr/lib64/libndi.so.5@  /usr/lib64/libndi.so.5.5.4*

> neofetch --stdout distro kernel shell
distro: Fedora release 39 (Thirty Nine) x86_64 
kernel: 6.5.11-300.fc39.x86_64 
shell: fish 3.6.1 
```

With that, I see the NDI Source.

**Comment by tytan652** [comment]
@Pysis868, you are using the reversed-engineered libndi prototype from VideoLAN devs.
https://code.videolan.org/jbk/libndi

obs-ndi is only compatible with NewTek official libndi.

**Comment by paulpv** [comment]
obs-ndi only looks in the following paths for libndi:
https://github.com/obs-ndi/obs-ndi/blob/7fe10f551d6629399477c274cc66eb768152ea21/src/plugin-main.cpp#L242-L250

If you make symbolic links to fake one of those paths then it might work.

Otherwise, what @tytan652 said https://github.com/obs-ndi/obs-ndi/issues/563#issuecomment-1817115748

**Comment by paulpv** [comment]
It also might help if you provided an OBS log, but I am pretty confident I already know what it would say, and that is that it could not find libndi in those above mentioned paths.
