### ISSUE TITLE
How to Silent Install?

### ISSUE THREAD

**Issue by goxia** [DistroAV/DistroAV#585]
I need to install this software completely silently, but I will be prompted to install obs-ndi runtime.

**Comment by jpooley-hearst** [comment]
It's easy to install [NDI Tools silently](https://forums.newtek.com/showthread.php/161183-NDI-Tools-silent-installer-component-switches), is there any way that you could make a switch to silently install obs-ndi so I can take care of NDI Tools myself in separate step in PDQ Deploy?

**Comment by paulpv** [comment]
@jpooley-hearst NDI silent installs came up today and I remembered this issue and came here to see how to install NDI tools but the link you provided is 404.
I even tried https://archive.org/web/
Do you happen to recall how to command-line install NDI?

**Comment by paulpv** [comment]
Oh, just above that post I linked too it does say:
```
Start-Process -Wait -FilePath "NDI-Tools.exe" -Verb RunAs -ArgumentList "/SP- /VERYSILENT /NORESTART /TYPE=all_tools"
```

So maybe that technically works.

The thread OP was just complaining that afterwards launching NDI Tools still pops up a license.

**Comment by jpooley-hearst** [comment]
wmic product where "name like 'NDI%%'" call uninstall /nointeractive
"NDI 4 Tools.exe" /VERYSILENT "/LOADINF=ndiconfig"

**Comment by Trouffman** [comment]
This has been solved. Look at the discussion on this repo talking about the easy one liner installer.
