### ISSUE TITLE
NDI settings window's modality breaks OBS tray icon functionality

### ISSUE THREAD

**Issue by PatTheMav** [DistroAV/DistroAV#587]
While investigating reports of "minimise to tray" functionality being either broken or buggy I was able to find plugins using modal windows interfering with OBS' ability to show/hide its window using the tray icon.

`obs-ndi` has these lines in its Qt UI file, `obs-websocket` does not have them, as such the latter doesn't trigger the issue:

```
  <property name="windowModality">
   <enum>Qt::WindowModal</enum>
  </property>
```

Removing those lines restores the functionality in OBS.

**Comment by paulpv** [comment]
Related to https://github.com/obs-ndi/obs-ndi/issues/599 ?

**Comment by paulpv** [comment]
Confirmed this is the line to fix.
https://github.com/obs-ndi/obs-ndi/blob/04ec2ca44202fd7b884f95d81829ba1c616c9dc9/src/forms/output-settings.ui#L6

Will be in next release.
