### ISSUE TITLE
Install on Mint Linux

### ISSUE THREAD

**Issue by Erichssf** [DistroAV/DistroAV#591]
Downloaded the .deb file. When trying to install it, it states that OBS is missing. I have OBS 26 installed on this machine.

**Comment by bylshaun** [comment]
Having the same issue on linux mint 20 with obs studio 26.02.  Get the following -  Dependency is not satisfiable: obs-studio (>= 25.0.7).

**Comment by Erichssf** [comment]
Any info on this issue yet?

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?
