### ISSUE TITLE
NDI Source

### ISSUE THREAD

**Issue by Demoncast** [DistroAV/DistroAV#604]
Hey, for me, NDI sometimes has problems that are difficult to explain, so I made an example video. Simply replaces the letters with a person. I dont understand why that happens i reinstalled Skype, OBS and NDI 2 times. But it doesn't always happen like in the video, but maybe every few minutes, which pretty much destroys the stream. I also tried to lock the source but it doesnt help. And sorry for my english c: . Please help me

https://user-images.githubusercontent.com/72348288/103157926-bf104080-47b8-11eb-963d-f48572cd32f2.mp4

**Comment by TrustMeICan** [comment]
What is the source of your NDI feed, is it Skype? Read "How do I stop the NDI feeds from changing sizes in OBS?" section in [this Skype help article](https://support.skype.com/en/faq/FA34853/what-is-skype-for-content-creators)
