### ISSUE TITLE
No sound from Magewell ProConvert

### ISSUE THREAD

**Issue by patrick-roan** [DistroAV/DistroAV#608]
hi, 

Windows10 version: build 1909/2004
OBS version: 26.0.2
NDI-OBS version: 4.9.1
Use Magewell ProConvert (SDI to NDI) as the NDI source. There is no sound in OBS, but there is sound when using NDI Monitor.

NDI-OBS "Sync" is set to "Network" or "Source Timing"

**Comment by patrick-roan** [comment]
png file
https://drive.google.com/drive/folders/18f4lajg9UNGpY7QhAF7a_D0PxTrsTNAd?usp=sharing

**Comment by peterfdej** [comment]
We have exactly the same problem with a Magewell pro convert SDI to NDI. Also tally light is not working. Several month ago we tried de hdmi to NDI Magewell converter and that worked well.

**Comment by peterfdej** [comment]
Update NDI runtime by downloading the latest NDI tools and install them. This will probably solve the problem. Tally light issue was a Windows firewall block.

**Comment by peterfdej** [comment]
Now we have the same problem with the Magewell ProConvert (SDI to NDI).
I tried NDI runtime 4.5 and 4.6 and both OBS 25 and 26. 
The response of Magewell support is: "It’s a behavior of OBS.
Please ask customer to have a test with vMix."
So I did try vMix and that is working well.

**Comment by Trouffman** [comment]
Should be fixed in latest DistroAV release.

Closing old issues. Please use the latest version of DistroAV / OBS and open a new issue if this persist.

**Comment by Trouffman** [comment]
Confirming this is resolved on DistroAV using Magewell Pro Convert HDMI 4K.

![Image](https://github.com/user-attachments/assets/417dd96d-9f95-45db-bcbb-4fddfc771331)

**Comment by RayneYoruka** [comment]
_There is never enough gandalf._

**Comment by WoutAndAbout** [comment]
I have exactly the same problem but with Haivision Makito X4 Enc to Magewell ProConvert (SDI to NDI)

Is there a solution for this to make this work? Vmix or OBS isn't an option in my case.

I have seen it work this way but it 'flaps' and is not stable. Now it doens't detect any audio channel
