### ISSUE TITLE
NDI HX OBS > Windows problems 

### ISSUE THREAD

**Issue by Topsn** [DistroAV/DistroAV#617]
Hi everybody.

That´s is a really interesting problem i have with the NDI HX app.
I use it on my iphone to use it as a cam in OBS Studio.

The strange thing is that the picture is perfect in the same network on my imac and also perfect when i send the picture from my imac over OBS-NDI Output to my pc.

But it don´t work directly from my iphone to my pc.
Because when i took the NDI Source directly from the iphone i have a short picture leak every 2 seconds   

And the second strange thing is that my PTZ NDI HX cams works perfect as well on PC and Imac on the same network

With the older NDI Newtek app for iphone i didn´t have that problem!

Is this a problem in windows? or with the OBS windows plugin?
Or do i use the wrong settings in windows or OBS - what I don't believe!

Because there is also that problem in the newer NDI OBS plugins with the sounds.
Because in the NDI options Y "sync" is only "network" and "source timming" but not "internal" anymore!
And it´s not possible to record the sound with the option "network"

Any ideas?!
And will there be a new NDI plugin version for OBS and when?! 
thanks a lot!
greetings

**Comment by paulpv** [comment]
Palakis installs v4.5.1 of the 
https://github.com/Palakis/obs-ndi/blob/master/installer/installer.iss
```
#define NDIRuntimeVersion "4.5.1"
  ndiRedistURL = 'https://ndi.palakis.fr/runtime/ndi-runtime-{#NDIRuntimeVersion}-Windows.exe';
```
The latest as of this moment is 4.6.1, which he has on his share:
https://ndi.palakis.fr/runtime/

You can try installing that and report back here.

**Comment by ForrestScott** [comment]
I can confirm the problem with the NewTek Hx camera app -> OBS on Windows 10.  Video freezes on a regular interval approx. 1-2 seconds.  Studio Monitor running in parallel to OBS doesn't exhibit the issue.

Upgrading the runtime from 4.5.1 to 4.6.1 does not fix the issue.
