### ISSUE TITLE
OBS NDI transmition protocol

### ISSUE THREAD

**Issue by TomKaland** [DistroAV/DistroAV#625]
Hi,

Been searching the web for an ansver on this.

The OBS NDI plugin uses witch protocol for trancfer in regrads for video and audio sources, UDP or TCP?

We use NDI/OBS and New Tech Access manger to transmit video (Zwift) and camera/audio over the internett. Sometimes we have a bit of lag/stuttering on both game and camera/audio without any network issues (both ways)

So we are checking out all our EQ and settings.

Regards
Tom Ove

**Comment by kanelp** [comment]
It depends on what you set in Access Manager and the version of NDI used on both sides of the connection.

With NDI 4.x, the default is typically TCP, unless you choose 'Prefer UDP' using Access Manager on the receiving computer.

With NDI 3.x the default is typically UDP.

NDI is a low latency protocol with no buffering, so if you are trying to directly send this over the Internet.  NDI is designed for LAN operation.  For Internet transmission, you often use a NDI Gateway product (Sienna, BirdDog, MediaLooks).
