### ISSUE TITLE
Choppy Audio when NDI source is active

### ISSUE THREAD

**Issue by noahbuttner** [DistroAV/DistroAV#649]
I have 1 NDI Source which is receiving video from an iPhone X using the NDI app.
I have a separate mic which works fine while the NDI source is not active.
As soon as the NDI source is activated, the audio of my mic becomes choppy on the output stream (I am using youtube). When I monitor the audio on my computer, it is fine.
CPU usage is only around 50%, so I don't think that would be an issue.
I have tried only monitoring the audio, and setting up a new audio output capture device as recommended [here](https://www.youtube.com/watch?v=PfCz_j3RD9I), however, it did not work.
I have seen several other issues addressing this, but have not seen a clear solution, thanks.

**Comment by JakobStadlhuber** [comment]
I have the same problem.

**Comment by JakobStadlhuber** [comment]
Okay I probably found the problem,

1. I used for testing Screen Capture and Screen Capture HX, the problem only appears on Screen Capture HX.
2. If I use Screen Capture HX I have to change Sync from Source Timing to Network then the audio was normal.

**Comment by rebb** [comment]
The fix mentioned in this video worked for me, using Screep Capture HX and "Source Timing" in the Settings :

https://www.youtube.com/watch?v=PfCz_j3RD9I

But just to re-iterate the fix here without the video :

In OBS go into "Advanced Audio Properties" in the Audio Mixer.
There, set your NDI Source Audio to "Monitor only - No Output".
Your Desktop Audio will now pick up the NDI Source Audio.
Make sure your Desktop Audio is enabled and unmuted and set to "Monitor Off".
Set the Audio Tracks as needed ( i had to enable all Audio Tracks for it to be picked up by the stream for some reason, but this is usually the default anyway ).

If all went right, the Audio should now be streamed / recorded without crackling.
