### ISSUE TITLE
OBS crashes on receiving PC when NDI Source selected

### ISSUE THREAD

**Issue by GitE5H** [DistroAV/DistroAV#669]
Everything was working fine but recently I installed VoiceMeeter and connected my both pc with VBAN, since then OBS crashes within couple of seconds as soon as I select NDI Source Scene on my secondary/receiving pc!! Host PC working fine!!
[Crash 2021-07-26 13-09-28.txt](https://github.com/Palakis/obs-ndi/files/6877871/Crash.2021-07-26.13-09-28.txt)

**Comment by da411d** [comment]
Same problem
