### ISSUE TITLE
NDI sources continue to send while filter is hidden

### ISSUE THREAD

**Issue by conn** [DistroAV/DistroAV#705]
Hiding the NDI output filter doesn't stop the source from being sent over the network. Other plugins (like the source-record plugin) will stop and start streams based on visibility. I would love for this plugin to respect filter visibility so that I may no longer need to remove the filter in order to prevent output being sent out.

https://user-images.githubusercontent.com/4983742/142797144-943da858-5482-41ab-8d89-948f73999b56.mp4

**Comment by nacalai** [comment]
+1 for that. I have been under the impression that it would stop the transmission and realizes it's still being sent out.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849
