### ISSUE TITLE
Disabled "Dedicated NDI output" filter still eating up CPU

### ISSUE THREAD

**Issue by olee** [DistroAV/DistroAV#719]
A little while ago I added a NDI output filter on my camera scene which I have disabled though most of the time.
Recently I noticed OBS taking 15% CPU performance instead of the usual 6% when idle and I was able to find out through process explorer that a thread in the NDI library was causing most of this.
After testing around a bit more I noticed that the NDI processing only seems to be disabled fully when the filter is completely deleted - disabling it does not free up the resources.
Even if the scene is not visible at all, it takes up that performance.

I think this should be fixed as it does not make sense for a completely disabled filter to take up soo much CPU performance.

**Comment by cyclemat** [comment]
Can confirm this problem

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849
