### ISSUE TITLE
Investigate/support NDI|HX 3

### ISSUE THREAD

**Issue by shleeable** [DistroAV/DistroAV#720]
https://videoguys.com/blogs/news-and-sales/ndi-hx3-is-here-takes-ndi-hx-to-the-next-level

**Comment by alessionossa** [comment]
I contacted people at NewTek / NDI and they said:

> NDI|XH3 is a format specification, you can create an HX3 stream with the actual SDK.
> 
> You simply implement an HX implementation as follows, 
> - GOP length of 1 or 2.
> - Bandwidth at a level where it is visually lossless with the HDMI/SDI output. (normally ~80Mbit/s)
> - Place The  video compressor in a low latency mode (e.g. I-frame only)
> 
> To claim NDI|HX3 support, NDI® must  test it and certify it In addition:
> - It must conform with other the latest usage implementation guide (e.g. for source naming, etc…)
> - It is visually lossless.
> - End to end latency with Studio Monitor is <100ms

**Comment by high-solutions** [comment]
would be nice to add HX3 output option to support Gigabit networks with multiple streams. 
+1 for me.

**Comment by ogmkp** [comment]
HX3 is just a tweak to prevent the artifacts from showing, we were already doing it on HX2 with more bitrate, they could have called it HX2.1, honestly in HEVC, 12 Mbits is enough for 1080p60.
