### ISSUE TITLE
Dedicated NDI tally

### ISSUE THREAD

**Issue by fgolman** [DistroAV/DistroAV#725]
When viewing the dedicated NDI output from a source it doesn't seem to send tally (as viewed through NDI Studio Montior).

**Comment by high-solutions** [comment]
a dedicated source is not the live source or not even previewed, the filter in OBS doesn't know it's source is in preview or in live, only the source itself knows if its live or previewed.
Aside from that: if the source doesn't have a tally (like a regular webcam) i'm not sure the dedicated NDI output can use it on that source.
