### ISSUE TITLE
Washed out colors

### ISSUE THREAD

**Issue by Piipperi** [DistroAV/DistroAV#726]
NDI (from a Windows OBS to macOS OBS) has quite washed-out colors. Please take a look at the screenshot attached. As you can see, the Windows Settings which is supposed to be black, appears as gray. And mostly anything dark appears more lighter than it should be, and dark colors have a gray-ish tone to them. The screenshot is just from the OBS Preview, but the same result is seen on the recording itself.
<img width="1680" alt="Näyttökuva 2022-3-3 kello 20 25 42" src="https://user-images.githubusercontent.com/29174220/156628937-20091d41-48d8-43ce-ab70-922057933642.png">

**Comment by JJTech0130** [comment]
Maybe my monitor is just bad, but that screenshot looks the same as the actual windows settings on my computer.

**Comment by Piipperi** [comment]
> Maybe my monitor is just bad, but that screenshot looks the same as the actual windows settings on my computer.

I moved the screen cap in the preview slightly so you can see how the black is actually supposed to look. I hope it helps

**Comment by JJTech0130** [comment]
Ah yeah. I colored the middle part black and now it’s obvious. 
![C98739AE-F7C4-4FFE-9751-863DF59B1832](https://user-images.githubusercontent.com/53275876/162016592-f07f0371-ff70-44a4-894a-98ef30d26463.jpeg)
Only thing is, do we know what windows settings looks like really? Could you screenshot it on the OBS pc, next to the reference black? IDK just a thought, dunno if it’s semi transparent or smth and your light background is shining through

**Comment by Piipperi** [comment]
![image](https://user-images.githubusercontent.com/29174220/162017725-39b282ff-c21e-448b-ad11-7ccee53f5c37.png)


> Ah yeah. I colored the middle part black and now it’s obvious. ![C98739AE-F7C4-4FFE-9751-863DF59B1832](https://user-images.githubusercontent.com/53275876/162016592-f07f0371-ff70-44a4-894a-98ef30d26463.jpeg) Only thing is, do we know what windows settings looks like really? Could you screenshot it on the OBS pc, next to the reference black? IDK just a thought, dunno if it’s semi transparent or smth and your light background is shining through

Yeah, it's supposed to be pitch black

**Comment by JJTech0130** [comment]
Hum. Do you know what side is doing it (I.e obs receive or transmit)? I’m assuming your using this plug-in on both ends.

**Comment by Piipperi** [comment]
> Hum. Do you know what side is doing it (I.e obs receive or transmit)? I’m assuming your using this plug-in on both ends. I would try it with an actual NDI software.

What would you recommend? I use NDI for game recordings so I don't really know of any actual software

**Comment by JJTech0130** [comment]
I dunno. I only use it to display a livestream on a remote RPi with DiCaffine. And color accuracy doesn’t matter for that.

**Comment by JJTech0130** [comment]
I’m mostly trying to help because when there’s plenty of information available the maintainers of these things tend to be more likely to help (in my experience). Lol.

**Comment by JJTech0130** [comment]
Perhaps something from https://www.ndi.tv/tools/#download-tools
It appears to be their official website

**Comment by paulpv** [comment]
Is this still an issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?

**Comment by AkmanTV** [comment]
Hey guys, I've the same problem, I don't think the OS is relevant cause I'm having this issue on Windows 11 and 10 PCs

Here is the side by side comparison while my game opened, I used the NDI Studio Monitor but it didn't matter as well

<img width="556" alt="1" src="https://github.com/obs-ndi/obs-ndi/assets/42110403/37f96b4d-3285-4c3a-88c0-55f59aae06d2">

**Comment by AkmanTV** [comment]
@paulpv

**Comment by paulpv** [comment]
> Hey guys, I've the same problem, I don't think the OS is relevant cause I'm having this issue on Windows 11 and 10 PCs
> 
> Here is the side by side comparison while my game opened, I used the NDI Studio Monitor but it didn't matter as well
> 
> <img alt="1" width="556" src="https://private-user-images.githubusercontent.com/42110403/294326604-37f96b4d-3285-4c3a-88c0-55f59aae06d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MTc1ODIsIm5iZiI6MTcwNDkxNzI4MiwicGF0aCI6Ii80MjExMDQwMy8yOTQzMjY2MDQtMzdmOTZiNGQtMzI4NS00YzNhLTg4YzAtNTVmNTlhYWUwNmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEwVDIwMDgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkZGQ2Njc3YzcyYTIyMGE4NjRmZjM1ZTNiYmRlYTc1YWZkOWY4NDMxZDQ2MzNjMTBiY2U1ZjgwOGU0YzViMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KwulVEL6HAv3Q-DtfNvQvGA3DC4YEQl0SvhDCBd-RzI">

To be frank, maybe my eyes are bad, but I do see a subtle difference between those two, but I would have never spotted that if not side-by-side.

I recall there being a comment in another ticket about this being related to the Latency Mode.
What Latency Mode are you using?
Try Low or Normal.

As a general 80/20 rule here, >80% of people should be using Normal latency.
Non-Normal settings should be used only on an exceptional basis, but I think it is human nature for people to always manually select Low or Lowest (why wouldn't everyone conceptually want the lowest latency?).

I really want to add Analytics/Telemetry to this library so that I can see how people are using this.

Note to self to:
1. Clearly output a summary of NDI Source settings in the OBS Log
2. Add an OBS Log field to this repo's Issue template

**Comment by RayneYoruka** [comment]
To add here: Is the colour output set to limited in OBS?
