### ISSUE TITLE
Skype NDI Video sources in OBS are changing size at random

### ISSUE THREAD

**Issue by quadcom** [DistroAV/DistroAV#727]
So I pulled in Skype feeds via NDI and added them to a scene. I noticed that quite often, the video feeds, at random, would change their physical size independently.

I had to manually rescale the size and placement of the video on the scene multiple times. The video would shrink, I'd resize and a few seconds later it would scale itself back up again without me touching it at all.

Not sure if this is an NDI, Skype or plugin issue.

It seems that maybe Skype is automatically changing the resolution depending on the bandwidth available. If the bandwidth drops Skype drops the resolution from 1080 to 720. When the bandwidth is back it scales it back up again. This change screws up the placement on the OBS scene. If there were a way to force the physical dimensions and position to stay as set in OBS regardless of the resolution coming in that might fix the problem.

**Comment by high-solutions** [comment]
isn't this skype's doing? if i recall correctly the resolution of skype's NDI is the size of the camera on screen,
so if you have 4 people in your meeting it's like your screen size (minus borders) devided by 4. if you have 7 people online it will be your screen size (minus borders) devided by 7.

i'm not sure this is quiet easy to fix in OBS

**Comment by aepex** [comment]
One way to fix is adding a "Scaling/Aspect Ratio" filter to your camera source, and setting a fixed resolution that matches the aspect ratio of the camera, e.g. 1280x720 for a 16:9 source. Then the transforms made in the scene will always start from this fixed resolution.

**Comment by high-solutions** [comment]
I don't think skype always gives the same Aspect Ratio. It can differ if you have 3 people or 10. But its a good solution still

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849
