### ISSUE TITLE
One of two sources missing from obs-ndi source list

### ISSUE THREAD

**Issue by 00goat** [DistroAV/DistroAV#732]
I'm adding a new camera (Avkans) to an existing OBS-NDI setup that has a PTZOptics camera. The Avkans was tested and working with NDI prior to being added to this network. Both cameras are on the same switch with the OBS PC, and the NDI studio monitor software detects them both with no issue.

Within OBS when I attempt to create a second scene with a second NDI source, the Avkans camera is not available in the dropdown as a source, only the PTZOptics shows up. Does anyone have a suggestion what might be going wrong here?

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849
