### ISSUE TITLE
NDI Privacy Group Names not Auto-Discovering

### ISSUE THREAD

**Issue by kathampy** [DistroAV/DistroAV#741]
I have configured a receiving group name in NDI Access Manager.
I configured the same group name in the camera.
The camera is on the same subnet as the PC.
Other NDI applications automatically detect the source with a name like `RC26 (NDI HX2, 192.168.1.100)`.

However, the source does not show up in OBS with the NDI plugin.
I can get it to work by manually entering the source name above.
Ideally auto-discovery should work with the group names configured in NDI Access Manager.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849
