### ISSUE TITLE
Bandwith Usage - Win 11/10 Compatibility 

### ISSUE THREAD

**Issue by r0dBit** [DistroAV/DistroAV#748]
I have only NDI installed on my gaming PC, and NDI, NDI Plugin and OBS on my streaming PC. I managed to add NDI as a source just fine, and I got my gaming PC desktop image, however, with huge delay and stutters all the time. I'm on a Gigabit network between these 2 PCs via an unmanaged Ethernet switch - already tested it, and I am getting 940 Mbps speed when sending/receiving files. HOWEVER, I noticed NDI is not using nothing more than 15 Mbps, even though it potentially have a lot more available to use. Gaming PC is running on Windows 11, and streaming PC on Windows 10 - do you think this could be the issue? Really wanted to make sure before I format my Win11 PC.

**Comment by r0dBit** [comment]
UPDATE: issue happening only with Screen Capture HX, normal Screen Capture is working fine

**Comment by krystofkrticka** [comment]
This will probably be fixed with release of NDI plugin updated to version 5 for OBS 28.

**Comment by IonicEcko** [comment]
NDI HX is designed to use very little bandwidth. As far as I can tell this is working as expected.

**Comment by paulpv** [comment]
Is this still an issue in https://github.com/Palakis/obs-ndi/pull/849 's 4.11.0-RC?
