### ISSUE TITLE
Possible bugs found in latest alpha build

### ISSUE THREAD

**Issue by krystofkrticka** [DistroAV/DistroAV#760]
Well when I was testing latest alpha build of OBS NDI, I found some possible issue which sound can sometimes cut out and video colors are way of in comparison to OBS Preview.

Here is screenshot of issue with messed up colors
![image](https://user-images.githubusercontent.com/37749100/188141512-2de15de2-f616-469d-87e0-e8f64314237f.png)

Issue with sound I noticed when testing plugin between multiple computers, on my main computer I started OBS sending feed over NDI and I was receiving in on my laptop with NDI Studio Monitor. But devices were connected to 1Gbps wired LAN.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849
