### ISSUE TITLE
No “Dedicated NDI Output” filter for MacOS in Alpha (yet?)

### ISSUE THREAD

**Issue by AskMP** [DistroAV/DistroAV#772]
##### Issue type
- Bug report

##### Description
Alpha build for 28 (macOS) seems to be missing the filter to allow for scenes or shots

##### Steps to reproduce and other useful info
Right-click on a scene and open the filters
Search the “add” menu to see no “Dedicated NDI Output”

##### Technical information
- MacOS (latest on M1 chip)
- 28.0.4
- Alpha Build for 28m (arm)

I’m hoping that this is simply not implemented yet but just wanted to confirm.

**Comment by rse** [comment]
It seems to be not related to the macOS variant, as I also do not see the "Dedicated NDI Output" filters and longer under Windows.

**Comment by AskMP** [comment]
> It seems to be not related to the macOS variant, as I also do not see the "Dedicated NDI Output" filters any longer under Windows. What is the reason?

I’m sure it'll be there soon enough, I just want to ensure that it is a known missing component. Thanks for confirming it for Windows, I didn't want to risk the install on my systems as a safety measure. Thankfully the old plugin still works with a local version of 27.x until this is updated too.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849
