### ISSUE TITLE
No Dedicated NDI Filter Windows

### ISSUE THREAD

**Issue by Syinites** [DistroAV/DistroAV#774]
Issue type
Bug report
Description
Alpha build for 28 windows

Right click a source, theres no Dedicated Fitler NDI

Technical information
Windows 10
28.0.4
This is a really big feature that i can't stream withou :( really hoping its fixed/added soon

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849
