### ISSUE TITLE
Question: One iPhone NDI Camera HX shows up as stereo in OBS, all others mono. Why?

### ISSUE THREAD

**Issue by MarximusMaximus** [DistroAV/DistroAV#783]
One of the iPhones always shows up as stereo audio, the rest always show up as mono audio. Does anyone have any idea why this one is showing up differently?

All the iPhones are running the same versions (iOS 15.7, 

- latest available NDI Camera HX available on 2022-11-02). 
- I am using external, but they're all the same type -- Blue Yeti in Cardioid mode (so expected mono). (I also tried without the external mics, but did not see a change. I have confirmed that the mics are indeed being used by lightly brushing the phone mics and the external to confirm which is sending audio.)
- Mic is connected via and external power is supplied to phone and mic through the Apple camera dongle (usb A + lightning to lightning).

I have gone through every setting I can see in the phones and in NDI Camera HX itself and for the ndi-obs source, but cannot find something that changes this.

Anyone know what's going on? Thank you.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849
