### ISSUE TITLE
Feature Request : Please add option to use a Discovery Server

### ISSUE THREAD

**Issue by speedy01** [DistroAV/DistroAV#829]
Please add an option to use a discovery server.  Some networks disable or drop mDNS packets.  Using NDI Discovery Server would also allow for sources to be on different subnets. Discovery server is available in the NDI SDK.
Thank you for your time and consideration.

**Comment by speedy01** [comment]
This may be more of al linux issue.  Using NDI tools for windows, I'm able to use to Access manager to set the discovery server addresses.  NDI doesn't seem to offer access manager for linux.

**Comment by apaulco3** [comment]
NDI on Linux uses a config file instead of the Access.  Should be (user home directory)~/.ndi/ndi-config.v1.json
It would just be a case of respecting the values there.
https://docs.ndi.video/docs/sdk/configuration-files
