### ISSUE TITLE
change codec to NDI|HX

### ISSUE THREAD

**Issue by arteVact** [DistroAV/DistroAV#870]
Is there a way to change the NDI output to NDI|HX, or the codec from SpeedHQ to H.264?
I have further processing equipment (e.g. TBS2603AU) that unfortunately only accepts NDI|HX h.264 and solving the problem purely via Screen Capture HX is a bit awkward.
I was a bit surprised not to find anything on the forums/Google about this, but maybe I'm searching too stupidly....
Many thanks in advance
Jethro

**Comment by Trouffman** [comment]
NDI|HX encoding require a special access to the Advanced SDK and it is being discussed. There are possible licensing requirement to consider as well.

**Comment by arteVact** [comment]
Thank you for the fast reply!

 
 

Gesendet: Mittwoch, 22. März 2023 um 14:01 Uhr
Von: "Trouffman" ***@***.***>
An: "obs-ndi/obs-ndi" ***@***.***>
Cc: "arteVact" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [obs-ndi/obs-ndi] change codec to NDI|HX (Issue #870)


 

NDI|HX encoding require a special access to the Advanced SDK and it is being discussed. There are possible licensing requirement to consider as well.

**Comment by chansearrington** [comment]
@Trouffman I'm willing to pay the license fee or jump through hoops... It just appears that there's zero way to do this at the moment.

In fact, I can't currently find any macOS software that supports outputting NDI | HX.

**Comment by Rotund** [comment]
On Windows, you can use the standard NDI Bridge tool to rebroadcast from full NDI to NDI|HX. I assume the Mac version has the Bridge tool too. https://ndi.video/tools/ndi-tools/

**Comment by jbcurler2010** [comment]
NDI Bridge is a good workaround, but for some workflows, it's not practical. I have considered having a separate device exclusively to run Bridge for this purpose but that is a little cost prohibitive.

**Comment by Trouffman** [comment]
I have pushed again regarding this. Especially as pretty much all of the ecosystem is moving toward the NDI|HX.

**Comment by jbcurler2010** [comment]
@Trouffman I had another discussion with Matt Lukens today. Can you contact me directly? He said he would be very happy to speak with you. I also have information regarding legally developing the plugin to enable NDI HX for non-commercial distribution/internal use. Happy to supply my email. Thanks.

**Comment by Trouffman** [comment]
@jbcurler2010 you've got email ;)

For the sake of sanity in the repo.

Status: the developpement of NDI HX could be done with the advanced SDK as available today but the distribution/ release could not for  licensing reason (as far as we understand).

This would also not be functional for more than a couple minutes without the proper license.

The discussion with NDI is to understand the limit & find a solution that would allow the OBS-NDI project/users to use NDI HX without too many hoops.

Wait and see.

**Comment by ogmkp** [comment]
HX has a limit of 30 free minutes on Advanced SDK. You need a licence to run it indefinitely. Could the project support this instruction mechanism?

**Comment by paulpv** [comment]
I could look into it...after I get all of the plugin functional instability issues under control! :)

**Comment by ayancey** [comment]
> I assume the Mac version has the Bridge tool too. https://ndi.video/tools/ndi-tools/

It does not.

**Comment by SecJoe** [comment]
Would be nice, if OBS could support NDI HX output. Devices like the Osee GoStream, only support NDI HX input, not the old NDI type

**Comment by RayneYoruka** [comment]
> Would be nice, if OBS could support NDI HX output. Devices like the Osee GoStream Duet (Atem mini successor), only support NDI HX input, not the old NDI type

NDI HX requires licensing, you can compare the normal SDK and the Advanced SDK here https://ndi.video/for-developers/ndi-sdk/

**Comment by Trouffman** [comment]
This cannot be done for now. But there is a PR "placeholder" for this .

https://github.com/DistroAV/DistroAV/pull/738
Will close for now.
