### ISSUE TITLE
Ability to "Disable" NDI Source without deleting

### ISSUE THREAD

**Issue by sideswipe001** [DistroAV/DistroAV#880]
Use Case: Two PCs running OBS. PC 1 has a webcam source with NDI Source filter added. PC 2 has an NDI source added, attached to the webcam from PC 1.

There should be a way for PC 2 to "Disable" the NDI source, freeing up resources, when that source is not needed for a scene. 

Currently this is a problem, because once the source is added, the connection between the PCs is left open constantly, even if the webcam is not used in the current scene (or is disabled) on PC 2. In my environment, this results in constant network traffic between the PCs, eating up about 57 Mbps on both NICs, as well as CPU use on both systems.

My use case is a dual PC setup, where PC 1 is a gaming PC and PC 2 does the transcoding; usually the webcam is picked up by the video capture card in PC 2, but if I want to stream a different source - like a Switch or Xbox - the Gaming PC is not used, and I set up NDI to get access to the webcam and microphone from it. The problem is that when I don't need those NDI sources, they stay active, and keep using resources, unless I delete them. Then I need to re-create them the next time I want to stream from a source that isn't the PC.

I'd like to just be able to go into OBS, select the NDI source, and "deactivate" it until I need it again, freeing up the resources when they aren't needed.

**Comment by paulpv** [comment]
@sideswipe001 When I hide my NDI Source my network usage drops:
![image](https://github.com/obs-ndi/obs-ndi/assets/1393897/cada5932-12e0-4878-aa29-799117ded1ea)
That screenshot is with my:
1. first viewing an NDI source that has been active for over an hour
  Received bandwidth is >200MB
2. just hiding the NDI source my clicking on the eyeball
  ![image](https://github.com/obs-ndi/obs-ndi/assets/1393897/9220776d-7e1f-49be-a4a3-49fdb7d59739)
  Received bandwidth is ~18MB
3. waiting about a minute and then clicking on the eyeball to show the NDI source again
  Received bandwidth is >200MB

That was with OBS staying as the foreground application.

What is odd is that changing the focus away from OBS to a different application causes the bandwidth to come back.
I can look into this more.

**Comment by SHIRO-Suit** [comment]
@paulpv Are there any steps required to do that ? I tested it but it's not working. The received bandwidth only changes when I delete sources.

**Comment by paulpv** [comment]
I looked in to this.
I think the bandwidth changes I experienced are actually due to Issue #875 .

I experimented with a code change to stop the NDI if the view is hidden.
The problem is, that conflicted with logic of changing scenes where a source is also not visible.
In a perfect world it would be expected to stop NDI in these cases.
But, this world is not perfect and when switching back to a scene with NDI this results in a delay in starting the NDI video.

This is still probably doable, but this was more than I was willing to do for the next 4.12.0 release.

I plan for a nice refactor in a 5.1.0 release and will try to squeeze this in then.

**Comment by gdantuono** [comment]
@paulpv news?

**Comment by paulpv** [comment]
> @paulpv news?

@haakonnessjoen created PR https://github.com/obs-ndi/obs-ndi/pull/993 to do just this on 2024/04/04 and it was merged to master on 2024/04/10.
It has not been released yet.
It will be "soon" (hopefully within a week or two).

**Comment by RikvdReijen** [comment]
Are NDI sources now disabled when not requested? Since starting to use NDI the performance of my OBS had dropped considerably and I am afraid NDI sources remain to be active even if not requested/viewed.

**Comment by RayneYoruka** [comment]
> Are NDI sources now disabled when not requested? Since starting to use NDI the performance of my OBS had dropped considerably and I am afraid NDI sources remain to be active even if not requested/viewed.

Source behaviour should have you covered. @RikvdReijen 
https://github.com/DistroAV/DistroAV/wiki#ndi-source
