### ISSUE TITLE
[Bug]: obs-ndi Romanian translation available

### ISSUE THREAD

**Issue by secarica** [DistroAV/DistroAV#883]
### OBS Version

29.0.x

### NDI Tools Version

5.5.4 runtime

### Describe the bug

Not a true bug, just adding the Romanian translation via the 'bug' method.

Sorry, I don't know how else to do this in git**b, only that I am using this 'bug' method for same purpose in Inkscape project (where there this is one of the officially accepted methods).

### Steps to reproduce

Just add the ro-RO.ini to the obs-ndi/locale directory.
[ro-RO.zip](https://github.com/obs-ndi/obs-ndi/files/11368500/ro-RO.zip)

**Comment by Trouffman** [comment]
I did the check + pushed a pull request : https://github.com/obs-ndi/obs-ndi/pull/891
cc @paulpv

**Comment by paulpv** [comment]
I will merge in to 4.12.0
