### ISSUE TITLE
[Bug]: NDI-OBS freezing/crashing

### ISSUE THREAD

**Issue by Rotund** [DistroAV/DistroAV#889]
### Operating System Version

Windows 11

### OBS Version

29.0.2 and 28.1.2

### NDI Tools Version

5.5.3.0 and none

### Describe the bug

The OBS-NDI plugin freezes so that the video stops updating on the NDI Sources. Then when attempting to close OBS, the obs-ndi plugin will keep OBS from closing. (Sorry, I had a stack trace log but not with me. It included the plugin shutdown function though.) During this time, the display capture and DroidCam plugins keep updating. Using NDI Tools/Monitor, the cameras are still updating. The freeze usually happens within the first hour of use but could be first 5 minutes.

NOTE: We don't seem to have this issue w/ the 4.10 obs-ndi plugin.

We're using Mevo Start cameras configured to use NDI|HX and low latency mode.

There are mentions of other people with the same issues on the OBS forum: https://obsproject.com/forum/threads/obs-ndi-newtek-ndi%E2%84%A2-integration-into-obs-studio.69240/page-47

### Expected behavior

It shouldn't freeze and crash the plugin.

**Comment by paulpv** [comment]
I will soon release a 4.12.0 version w/ updated NDI lib that might help/avoid this.

You can try out 4.12.0 Release Candidate if you want.

The Pull Request https://github.com/obs-ndi/obs-ndi/pull/919 has been labeled with "Seeking Testers" and the build generates installer packages that you can download try out.

Steps:
1. Browse to https://github.com/obs-ndi/obs-ndi/pull/919
2. Click on "Show all checks"
3. Click on any of the "Details"
4. Click on "Summary"
5. Scroll down and see the "Artifacts"
6. Download the relevant Linux/MacOS/Windows artifact for your platform
7. Windows may complain that the download looks suspicious; you may safely ignore 
8. Unzip the download
9. Run the installer

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?

**Comment by TheNinjaofEarth** [comment]
> Is this still an issue using 4.13.0?

I would test this for you but I don't have a file to install 4.13.0 unless you can provide said file.

**Comment by RayneYoruka** [comment]
> I would test this for you but I don't have an install file for 4.13.0 to roll back to, unless you can provide said file.

https://github.com/obs-ndi/obs-ndi/releases/tag/4.13.0

**Comment by TheNinjaofEarth** [comment]
> > I would test this for you but I don't have an install file for 4.13.0 to roll back to, unless you can provide said file.
> 
> https://github.com/obs-ndi/obs-ndi/releases/tag/4.13.0
Yes this is still an issue with 4.13.0

After testing 4.13.0 with OBS removed OBS from the equation and it still freezes...



> > I would test this for you but I don't have an install file for 4.13.0 to roll back to, unless you can provide said file.
> 
> https://github.com/obs-ndi/obs-ndi/releases/tag/4.13.0

Yes. This is still an issue with  4.13.0....

**Comment by TheNinjaofEarth** [comment]
> Is this still an issue using 4.13.0?

Yes it is still an issue in 4.13.0; I tested 2 different setups. Same results both times.

**Comment by TheNinjaofEarth** [comment]
> Is this still an issue using 4.13.0?

Yes

**Comment by anandasanz** [comment]
I also have freezing using obs-ndi. In streaming pc only the webcam dont freeze because doesnt use obs-ndi. I have tried using OBS 30.2.3 and the older versión I usuallly used last year, and tried with obs-ndi 4.14.1 and 4.11.1 and DistroAV 6.0.0 RC1, and NDI 5.5.3 Runtime and NDI 6 Runtime. I have made all combinations with all this versions i have mentioned and the freezing is happening every time. I have disconected and reconected all the LAN router cables, and the problem continues. Any idea to solve it?

**Comment by Trouffman** [comment]
We changed some behavior in V6 to solve bug that would hang closing OBS when sources are not sending data.

This is also on an old OBS and old plugin version.
Of you experience this again. Please ope a. New issue and follow the updated reporting process as well.

Thank you
