### ISSUE TITLE
NDI OBS OUTPUT - NDI Aceess 

### ISSUE THREAD

**Issue by Terrykay69** [DistroAV/DistroAV#907]
Hey guys.

BY default the NDI OBS output sends signal from OBS to the public channel. Is there a way to reconfigure this so that you can choose which sending group the feed is being send to?

**Comment by paulpv** [comment]
This would be an enhancement to add group support to:
* https://github.com/obs-ndi/obs-ndi/blob/79b2f80b645efebf276f4cd2567775384970e093/src/obs-ndi-filter.cpp#L246
* https://github.com/obs-ndi/obs-ndi/blob/79b2f80b645efebf276f4cd2567775384970e093/src/obs-ndi-output.cpp#L198

Seems fairly trivial to do if the UI is kept simple (simple text field that is not validated).

**Comment by Terrykay69** [comment]
Thanks Paul.

**Comment by Trouffman** [comment]
Closing as this is an older issue.
Please update to the latest version of the DistroAV plugin.

Is available now for program/preview.
