### ISSUE TITLE
[Bug]: OBS studio не видит плагин ndi

### ISSUE THREAD

**Issue by urunovanton** [DistroAV/DistroAV#911]
### Operating System Version

Windows 10

### OBS Version

29.1.3

### NDI Tools Version

5

### Describe the bug

Установил плагин, перезапустил компьютер. Запускаю OBS Studio, плагин вообще не определяется, даже никакую ошибку не выдаёт.

### Expected behavior

При нажатии на вкладку "Инструменты" должна появиться кнопка NDI

**Comment by paulpv** [comment]
@urunovanton Please attach an OBS log
In OBS select Help > Log Files > Upload last Log File.
Copy the URL and paste it here.
