### ISSUE TITLE
[Bug]: black screen or no serch input  HELP ME!!

### ISSUE THREAD

**Issue by ShaneTwentySiX** [DistroAV/DistroAV#928]
### Operating System Version

win10 and win11

### OBS Version

30.0.0.0

### NDI Tools Version

5.5.3.0 and try 5.6.0.0

### Describe the bug

it finds me the path if I don't mention it in hevc, once I select the relevant source it gives me a black screen, it can't record the screen or in any case bring back the screen of the other PC

### Screenshots

![Screenshot_1](https://github.com/obs-ndi/obs-ndi/assets/150826583/d837c873-e2bd-418c-84dd-a4cd18e1f353)
![Screenshot_2](https://github.com/obs-ndi/obs-ndi/assets/150826583/6f0a6167-519f-4fbc-ac5d-87bba9b9faf6)

**Comment by paulpv** [comment]
* What does "if I don't mention it in hevc" mean?
* What is the sender?
* Have you tried toggling any of the other settings to see if they help?
* Can you view it in NDI Studio Monitor?
* Please attach a log.

**Comment by ShaneTwentySiX** [comment]
because you can put the screen capute h.264 and hevc, however nothing starts black screen and stop. how do you check the logs I'm not very good with these things.... sorry

**Comment by paulpv** [comment]
No problem. Just trying to understand your English clearer.

* So on the NDI Capture side you can select HEVC or H.264.
  Does it matter which one you select?
  Does one work OK and the other not?
* For OBS logs, see https://obsproject.com/tools/analyzer
  You can also just view the OBS Log directly and copy-and-paste it here.

Please answer my other questions too.

**Comment by ShaneTwentySiX** [comment]
exactly with one it doesn't even detect the resource and with the other yes, as soon as I select it it goes black and doesn't show anything.

**Comment by ShaneTwentySiX** [comment]
https://obsproject.com/logs/s57wPZfYb2pmaOB6
https://obsproject.com/logs/ciikohzcSKLYaPcB
https://obsproject.com/logs/QLgeM8kNTE1WGPNn
https://obsproject.com/logs/qLBACsBiOXsNd5kq
https://obsproject.com/logs/ZnU2ZLzGzwkY6Nvo
https://obsproject.com/logs/2UCGNHRqpgYRHiOU

**Comment by ShaneTwentySiX** [comment]
they are all roughly the same... xD

**Comment by paulpv** [comment]
* Is audio working ok?
* What is the sender?
* Have you tried toggling any of the other settings to see if they help?
* Can you view it in NDI Studio Monitor?

**Comment by ShaneTwentySiX** [comment]
in the past I used it and it worked then I don't know why it didn't work, the audio doesn't work, with the monitor it worked 2 times and then that's it. I use 2 PCs, the one where I sent the links and the one I use for streaming, the other one where I only play

**Comment by paulpv** [comment]
* Is audio working ok?
> n the past I used it and it worked then I don't know why it didn't work, the audio doesn't work, with the monitor it worked 2 times and then that's it
  So it isn't just that the screen it black (no video)...it is also that there is no audio...which is an important clue about the root cause.
  It seems like it is just not getting data.
  I have pushed to the `develop` branch a `--obs-ndi-verbose` command-line option to log an `a` or `v` for any incoming audio or video frames.
  https://github.com/obs-ndi/obs-ndi/blob/61f4d052349918f5303475acd43170699748ae73/src/obs-ndi-source.cpp#L714-L716
  If we are not getting any frames at all then that is important to know.
* What is the sender?
> I use 2 PCs, the one where I sent the links and the one I use for streaming, the other one where I only play
  Sure, but what app on those PCs is doing the capturing? How is it set up?
* Have you tried toggling any of the other settings to see if they help?
  ?
* Can you view it in NDI Studio Monitor?
  ?

**Comment by ShaneTwentySiX** [comment]
I can also show you on discord and I'll show you everything so you understand better, the streaming PC that takes the signal from the PC I play. It's very strange that this happens to me because I've always done this and nothing happened to me.
Yes I tried everything but nothing and NDI Studio Monitor not working

**Comment by paulpv** [comment]
I am busy with my day job most of the time.

The fact that NDI Studio Monitor also does not see the video tells me that is an NDI or Network issue.

**Comment by ShaneTwentySiX** [comment]
I don't know about the network, maybe it's not possible, so what do I do, untag everything and reinstall it? I'm distressed by the fact that it worked and now nothing works anymore...

**Comment by ShaneTwentySiX** [comment]
I tried with the remote sending me the invitation and it certainly looks a little bad but it shows, I don't understand why if I didn't do it right I didn't

**Comment by ShaneTwentySiX** [comment]
I confirm with Studio Monito it works but it doesn't capture the audio, for the rest it remained unchanged if I try to screen capture hx and then create the source on obs and select the source, nothing works

**Comment by paulpv** [comment]
Sorry, I am having a little bit of a hard time following your English.

> I don't know about the network, maybe it's not possible, so what do I do, untag everything and reinstall it? I'm distressed by the fact that it worked and now nothing works anymore...

"untag" meaning uninstall? In my experience that doesn't usually help very much and just repeats/prolongs the problem and increases frustration. If it doesn't work the first time, why would the second time be any different?

I missed/forgot that you said this used to work.

On both your side and ours little has changed between recent versions that would have made any difference in this area.

> I tried with the remote sending me the invitation and it certainly looks a little bad but it shows, I don't understand why if I didn't do it right I didn't

What do you mean by "sending me the invitation"?

What do you mean by "it certainly looks a little bad but it shows"?
Is "it" `obs-ndi` or `NDI Studio Monitor`?
Are you saying `obs-ndi` is working now?
And earlier you said "I tried everything but nothing and NDI Studio Monitor not working".
So, respectful apologies, but I am a bit confused/lost in this conversation.

> I confirm with Studio Monito it works but it doesn't capture the audio, for the rest it remained unchanged if I try to screen capture hx and then create the source on obs and select the source, nothing works

Earlier you said "I tried everything but nothing and NDI Studio Monitor not working".
But now it NDI Studio Monitor is working but without audio.
Did you do anything to get NDI Studio Monitor working?

If NDI Studio Monitor isn't capturing audio then that will have to be resolved.
**As a general rule**, obs-ndi will never be better (more reliable) than NDI Studio Monitor.
If NDI Studio Monitor does not show video or play audio then obs-ndi won't either.

One of my original questions was "What is the sender?" and "Sure, but what app on those PCs is doing the capturing? How is it set up?".
I don't see any specific answer other than your recent "if I try to screen capture hx".
Were you capturing hx before?
There are [**some** reported issues with hx](https://github.com/obs-ndi/obs-ndi/issues?q=is%3Aissue+is%3Aopen+hx), but in general it works for me to use `NDI Screen Capture HX` on one PC and capture it in OBS on another PC.

There are still many [to me] unexplained ghosts about NDI not working that I still do not understand.
Even when it used to work for one version and isn't now.
Again, I am fairly confident that little to nothing changed in the obs-ndi code in recent versions that would cause breaks **in this area**.

**Comment by ShaneTwentySiX** [comment]
then having 2 PCs, one uses OBS and the other doesn't. pc 1 uses obs and takes the signal from pc 2 which is what I need to display on obs. If I use NDI Studio Monitor it shows but doesn't pick up the audio. if instead I use PC 2 which would be the one to record I use NDI Screen Capture HX on obs it gives me a black screen, or sometimes it doesn't find the source

Yes, I uninstalled everything and reinstalled to see if it worked but nothing changed. As I told you previously, I was already using it to tighten up but from one day to the next it no longer worked

In both PCs they use the same versions of both ndi tools and obs - therefore only one operating system changes and windows 10 and the other 11.

**Comment by paulpv** [comment]
FYI: Apologies in advance. My wording below is not trying to difficult. I am just trying to better understand your English.

1.
> 2 PCs, one uses OBS and the other doesn't. pc 1 uses obs and takes the signal from pc 2 which is what I need to display on obs. If I use NDI Studio Monitor it shows but doesn't pick up the audio.

2.
> if instead I use PC 2 which would be the one to record I use NDI Screen Capture HX on obs it gives me a black screen

Those two sentences confuse me.

In #1 you say that PC1's OBS receives PC2's NDI stream. You do say that OBS is only on one PC, PC1, but I still don't know what on PC2 is capturing and sending the NDI stream.

I am still mostly following you so far, but then in #2 you say "instead" PC2 uses `NDI Screen Capture HX`... but again I still don't know that on PC2 is **normally** (not "instead") capturing and sending the NDI stream.

Or...are you saying that on PC2 "which would be the one to record" you also have OBS local capturing `NDI Screen Capture HX` and that is black?  
I don't think this is what you are trying to say, but it almost reads like this.

Do this: On PC1 that is running OBS run `NDI Screen Capture` (either HX or not HX) and see if OBS can see that.  
I local capture on PC1 of PC1 should eliminate any network/firewall issues.

**Comment by ShaneTwentySiX** [comment]
I'm Italian and I'm getting help from the translator, that's why you don't understand hahaha my fault

yes you understand what I want to tell you. PC 1 which uses OBS takes PC 2 which does not have AOBS but only has the HX screen capture for PC 1 to display.

as it has always been even if you have no open applications to stream it should still take the desktop and play it on obs,

I apologize for this general inconvenience but I would like to resolve it so as not to spend money, which I don't already have a lot of

**Comment by ShaneTwentySiX** [comment]
anyway you capture pc 1 it captures itself via screen capture hx, as soon as I change and put pc 2 no black screen

**Comment by paulpv** [comment]
> yes you understand what I want to tell you. PC 1 which uses OBS takes PC 2 which does not have AOBS but only has the HX screen capture for PC 1 to display.

PC1: Running `OBS + obs-ndi`
PC2: Running `NDI Screen Capture HX`

Result:
PC1 sees only black NDI video

Does it get audio at all?
What happens if you try to run the non-HX `NDI Screen Capture`?

> anyway you capture pc 1 it captures itself via screen capture hx, as soon as I change and put pc 2 no black screen

Are you saying that PC1 can successfully capture its own `NDI Screen Capture HX` video and audio?
That sort-of makes sense, since local receiving of a local capture never touches the network.
That sort-of does not make sense, since the problem you've described so far seems to be HX related, so if HX is a problem I would expect a local HX capture to also not work.

> I tried to reverse pc2 which takes pc1 and it doesn't work. I think they can't communicate with each other

Setup:
PC1: Running `NDI Screen Capture HX`
PC2: Running `OBS + obs-ndi`

Result:
PC2 sees only black NDI video

Does it get audio at all?
What happens if you try to run the non-HX `NDI Screen Capture`?

**Comment by paulpv** [comment]
@ShaneTwentySiX What GPU is on your PC1 and PC2?
Are you using HX HEVC or H.264?
Try using the other.

**Comment by paulpv** [comment]
Interestingly:
https://forums.newtek.com/threads/ndi-bridge-ndi-hx-encoder-not-work.167925/post-1648284
> This morning I´ve heard during some ´business´ NDI/Tricaster talks with a client of mine some tools from current NDI 5.6.0.0 may not feel so well with WIN11 as on WIN10, while obviously an earlier 5.5.x build did do as expected for these their issue(s) with 5.6.0.0 on WIN11.
If so, I guess upcoming, already anounced, NDI Tools 6 will take care of this topic, if there is/are indeed issues on WIN11 vs. WIN10.
