### ISSUE TITLE
[Bug]: Flatpak [SteamOS3.5.7] install does not list NDI sources

### ISSUE THREAD

**Issue by UZTQD** [DistroAV/DistroAV#941]
### Operating System Version

SteamOS 3.5.7 (Based ArchLinux)

### OBS Version

OBS 30.0.0 (linux)

### NDI Tools Version

NDI SDK LINUX 10:26:04 Nov 17 2023 5.6.0

### Describe the bug

Video sent with obs-ndi enabled in OBS running on SteamOS_3.5.7 could not be discovered on Windows, Linux and Mac.

### Steps to reproduce

1. OBS install on Steam OS used discover software center
2. ndi-obs install on Steam OS used discover software center
3. NDI 5 Runtime Download & Install
4. Run OBS and Activate in tools collum 'NDI Output settings'
5. Trying to find NDI source from OBS NDI source run on Windows to NDI run on SteamOS 3.5.7 (on Steam Deck)

### Expected behavior

As far as I can read from the logs, both the runtime installation and the plug-ins seem to be working well. I wonder if Valve's team has done anything special to configure SteamDeck to run obs-ndi? I have no idea. I also thought it might be a communication problem, so I tested it by temporarily mutually disabling the Firewall, but that didn't work either. I'm not even sure if my isolation is a bug or not, so I'm posting it here. Please forgive me.

### Additional context

This is logs
https://obsproject.com/logs/h10LRRR9rB3ELJeu

**Comment by UZTQD** [comment]
Thanks for the comment.

> What is the setup here? I [think I] get that obs-ndi is running on SteamOS and Windows, but I do not understand which is sending and which is receiving, or even if obs-ndi is both sending and receiving or if you are using something else which is being used to send or receive.

First about here, I was unable to detect the source both for video transmission from SteamOS to Windows/Linux/Mac and for transmission in both reverse order paths.
 
> I am thinking of this as just a well known but still not understood/fixed issue of obs-ndi Source Discovery. Can you see the NDI source in NDI Studio Monitor? Can you see the NDI source in OBS/obs-ndi is using NDI Screen Capture to capture/transmit/send?

Next, about here, I tried to explore the sources originating from SteamOS in the NDI Studio Monitor, but could not find them. The NDItools I tried is 5.6.0.

Other Windows, Linux, and Mac computers are detecting each other's sources, so I'm thinking it's not a network problem at this point.

**Comment by RayneYoruka** [comment]
Any way to verify that this isn't a firewall problem on the SteamOS?

**Comment by UZTQD** [comment]
I also thought it might be a firewall issue or a NIC issue, so I ran it once in a standalone network with the machines mutually set to firewall off, but I could not detect it. （I tried three different connections (wired and wireless through a router, and direct connection without a router).

**Comment by paulpv** [comment]
> Next, about here, I tried to explore the sources originating from SteamOS in the NDI Studio Monitor, but could not find them. The NDItools I tried is 5.6.0.

Exactly; if NDI Studio Monitor cannot see the source, then obs-ndi never will be able to.

I am not of much help here, but try to get NDI Studio Monitor working.
If you can get that working, then please report back here if obs-ndi started working or not.

**Comment by UZTQD** [comment]
> I am not of much help here, but try to get NDI Studio Monitor working. If you can get that working, then please report back here if obs-ndi started working or not.

I understand to some extent.
NDI Studio Monitor running on Windows 10 is detecting sources from other machines (Linux and Mac), is this treated as working? (It is not detecting sources from SteamOS).

**Comment by UZTQD** [comment]
We are currently thinking of two possible cause scenarios.
1. obs-ndi is able to run on SteamOS, but SteamOS is not able to send packets from the NIC.
2. obs-ndi appears in the logs to be running on OBS, but in fact it is not.

I still think pattern 1 is more likely at this point, but I can't think of a way to isolate it.

**Comment by paulpv** [comment]
In the log you posted in your original message:
https://obsproject.com/logs/h10LRRR9rB3ELJeu

It says:
```
18:10:03.891: Using EGL/X11
18:10:03.892: CPU Name: AMD Custom APU 0405
18:10:03.892: CPU Speed: 2022.890MHz
18:10:03.892: Physical Cores: 4, Logical Cores: 8
18:10:03.892: Physical Memory: 14814MB Total, 6445MB Free
18:10:03.892: Kernel Version: Linux 6.1.52-valve9-1-neptune-61
18:10:03.892: Flatpak Branch: stable
18:10:03.892: Flatpak Arch: x86_64
18:10:03.892: Flatpak Runtime: runtime/org.kde.Platform/x86_64/6.5
18:10:03.892: App Extensions:
18:10:03.892:  - com.obsproject.Studio.Plugin.NDI
18:10:03.892:  - com.obsproject.Studio.Locale
18:10:03.892: Runtime Extensions:
18:10:03.892:  - org.freedesktop.Platform.GL.default
18:10:03.892:  - org.freedesktop.Platform.openh264
18:10:03.892:  - org.gtk.Gtk3theme.Breeze
18:10:03.892:  - org.kde.Platform.Locale
18:10:03.892:  - org.freedesktop.Platform.GL.default
18:10:03.892: Flatpak Framework Version: 1.14.4
18:10:03.892: Desktop Environment: KDE (KDE (One-Time Launch))
18:10:03.892: Session Type: x11
18:10:03.892: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
18:10:03.893: Qt Version: 6.5.3 (runtime), 6.5.3 (compiled)
18:10:03.894: Portable mode: false
18:10:03.962: OBS 30.0.0 (linux)
```

It looks like you installed OBS from a flatpak.
What flatpak?

How did you install obs-ndi?

obs-ndi flatpak also ships a libndi installer, and that libndi also requires ffmpeg installed:
https://github.com/obs-ndi/obs-ndi/issues/724#issuecomment-1818762500

The log also shows the scene has an NDI source in it.
That should be fine, but I thought this log was from the SteamOS transmitter, so why is the SteamOS transmitter also receiving NDI?

Another thing you can try to do is to local loopback obs-ndi output and capture that output on the same PC.
This ignores the network card and tests that data is flowing.

**Comment by UZTQD** [comment]
Excellent. I have a feeling that this example will match my symptoms with high probability. Thank you. I will try a few.

**Comment by UZTQD** [comment]
In the meantime, I will answer the questions that are unclear.

> It looks like you installed OBS from a flatpak. What flatpak?
> 
> How did you install obs-ndi?
We receive and install Flatpak packages via Discover Software Center.
![image](https://github.com/obs-ndi/obs-ndi/assets/113956120/94678c91-7769-4b6e-8f97-a196ce76f815)

> The log also shows the scene has an NDI source in it. That should be fine, but I thought this log was from the SteamOS transmitter, so why is the SteamOS transmitter also receiving NDI?
Sorry for the confusion.
This is because I was trying to send and receive on this OBS.
This device (SteamDeck) will be used for transmitting.

> Another thing you can try to do is to local loopback obs-ndi output and capture that output on the same PC. This ignores the network card and tests that data is flowing.
Do you mean that the local loopback is established on this machine (one OBS session running on SteamDeck's SteamOS) by itself?
I could not get the OBS source to detect the ndi I am outputting with obs-ndi activating the main output.
![image](https://github.com/obs-ndi/obs-ndi/assets/113956120/70214988-a536-4327-968f-b2f6b929a45f)
This GUI is a property when trying to add ndi sources to an OBS running the main output of obs-ndi. Normally it would seem that the Source name pull-down would list the output of self, but I got nothing.

**Comment by UZTQD** [comment]
Excellent.
Completely resolved.
It was all due to the fact that Avahi-daemon was not enabled by default as you mentioned.

sudo systemctl enable avahi-daemon
sudo systemctl start avahi-daemon

By doing the above, obs-ndi is working perfectly.

![image](https://github.com/obs-ndi/obs-ndi/assets/113956120/4fa55836-a015-4229-b22c-66192cc841b9)

Loopback was also confirmed to be excellent!
The firewall also remains strong and functional without the need for any additional port settings.

**Comment by UZTQD** [comment]
Thank you all for your help and advice.

**Comment by paulpv** [comment]
Re-opening until this [and a few other] fix is added to a new Troubleshooting section of the readme.

Would this be a "Troubleshooting" or "Known Issues"...or just "Required Post Setup Steps" specific to Flatpak?

Proposed text:

Part 1 (Flatpak install instructions)
```
# Install
...

## OBS-NDI
...
* Linux
    ...
    * Flatpak (per https://github.com/obs-ndi/obs-ndi/issues/724#issuecomment-1817782905):
      ```
      flatpak install com.obsproject.Studio com.obsproject.Studio.Plugin.NDI
      sudo systemctl enable avahi-daemon
      sudo systemctl start avahi-daemon
      sudo ufw allow 5353/udp
      sudo ufw allow 5959:5969/tcp
      sudo ufw allow 5959:5969/udp
      sudo ufw allow 6960:6970/tcp
      sudo ufw allow 6960:6970/udp
      sudo ufw allow 7960:7970/tcp
      sudo ufw allow 7960:7970/udp
      sudo ufw allow 5960/tcp
      obs --system-talk-name=org.freedesktop.Avahi
      ```
      obs-ndi's flakpak is still a work in progress; please experiment and
      report on our [Discord server](#discord) any problems or improvements.
```

**Comment by paulpv** [comment]
I'll also look into updating the https://github.com/flathub/com.obsproject.Studio.Plugin.NDI readme with whatever text we settle on here.

**Comment by paulpv** [comment]
Interesting!

Seems obvious now, but Avahi daemon must be running for all Linux libndi use cases.

Sounds like something NDI could document better!

So, yes, I will add this requirement to all Linux installations:

@tytan652 is this better:
```
## Requirements
* OBS >= 30.0.0 (Qt6 & x64)
* NDI 5 Runtime  
  We are not allowed to directly distribute the NDI runtime here, but you can get it from either
  [the links below](#ndi-runtime), or installing [NDI Tools](https://ndi.video/tools/), or the
  [NDI SDK](https://ndi.video/download-ndi-sdk/).

# Install

## NDI Runtime
* Linux:
  * Debian: [./CI/libndi-get.sh](./CI/libndi-get.sh)
  * Flatpak: Already included
* MacOS: http://ndi.link/NDIRedistV5Apple
* Windows: http://ndi.link/NDIRedistV5

## Linux Additional Requirements
```
sudo apt install avahi-daemon ffmpeg
sudo systemctl enable avahi-daemon
sudo systemctl start avahi-daemon
sudo ufw allow 5353/udp
sudo ufw allow 5959:5969/tcp
sudo ufw allow 5959:5969/udp
sudo ufw allow 6960:6970/tcp
sudo ufw allow 6960:6970/udp
sudo ufw allow 7960:7970/tcp
sudo ufw allow 7960:7970/udp
sudo ufw allow 5960/tcp
```
Firewall rules taken from https://ndi.tv/tools/education/networking/best-practices/networking-best-practice/

## OBS-NDI
Download and install the Linux, MacOS, or Windows version at [Releases](https://github.com/obs-ndi/obs-ndi/releases).
* Linux
    * Debian:
      1. Download [obs-ndi-4.14.0-x86_64-linux-gnu.deb](https://github.com/obs-ndi/obs-ndi/releases/download/4.14.0/obs-ndi-4.14.0-x86_64-linux-gnu.deb)
      2. `sudo dpkg -i obs-ndi-4.14.0-x86_64-linux-gnu.deb`
      3. If this does not work then try:
      ```
      sudo ln -s /usr/lib/x86_64-linux-gnu/obs-plugins/obs-ndi.so /usr/local/lib/obs-plugins/obs-ndi.so
      sudo ln -s /usr/share/obs/obs-plugins/obs-ndi/ /usr/local/share/obs/obs-plugins/obs-ndi
      ```
    * Flatpak (per https://github.com/obs-ndi/obs-ndi/issues/724#issuecomment-1817782905):
      ```
      flatpak install com.obsproject.Studio com.obsproject.Studio.Plugin.NDI
      obs --system-talk-name=org.freedesktop.Avahi
      ```
      obs-ndi's flakpak is still a work in progress; please experiment and
      report on our [Discord server](#discord) any problems or improvements.
...
```

**Comment by tytan652** [comment]
> * Flatpak (per https://github.com/obs-ndi/obs-ndi/issues/724#issuecomment-1817782905):
>    ```
>    flatpak install com.obsproject.Studio com.obsproject.Studio.Plugin.NDI
>    obs --system-talk-name=org.freedesktop.Avahi
>    ```

About:
```
obs --system-talk-name=org.freedesktop.Avahi
```

This does not execute the OBS Studio Flatpak and anyway trying to add `--system-talk-name=org.freedesktop.Avahi` is unnecessary since OBS Studio Flatpak already has it for historical reason.

---------------------------------------------------------

About the firewall, `ufw` is just a commonly used firewall software there is other firewall software.

---------------------------------------------------------

The Avahi daemon might be already enabled so `sudo systemctl status avahi-daemon` is worth to check before enabling it.

---------------------------------------------------------

The FFmpeg "dependency" for NDI|HX is specifically for FFmpeg 4.x (not 5.x, not 6.x), unfortunately beside Arch Linux and Flatpak not many Linux distribution will provide a way to install FFmpeg 4.x side by side to the main FFmpeg package

**Comment by UZTQD** [comment]
I think it is an understandable proposal.

As for the firewall port settings, I think most users switch profiles for each network they connect to.
So why not do it all at once when activating Avahi-daemon, but as a check step in case communication fails after activation?

At least on SteamOS, the network area setting was selected as "Public" and it worked with the default settings.
