### ISSUE TITLE
[Bug]: Audio cutting in and out rapidly

### ISSUE THREAD

**Issue by qwertychouskie** [DistroAV/DistroAV#943]
### Operating System Version

Ubuntu 23.10

### OBS Version

30.0.1

### NDI Tools Version

obs-ndi 4.13.0
libndi5 5.5.3-1

### Describe the bug

Audio flickers in and out rapidly after a short while of the NDI stream being active.  Can be seen starting here: https://www.youtube.com/live/2CBYiMyasN0?si=W8K9xa5TZu_m6q9Q&t=1170

Restarting the app providing the source (Tallis NDI in this case) didn't fix it in my testing.  I believe OBS needs to be restarted to restore normal functionality.

### Steps to reproduce

Stream an NDI stream with audio from a phone (using Tallis NDI app)

### Expected behavior

Audio stays normal

**Comment by paulpv** [comment]
At 19m:34s there is a visual stutter of the video too immediately as the audio starts to mess up.

Can you run CPU and Memory profiling on this PC to see how it is being utilized?

An OBS Log from a bad session could also help.

**Comment by paulpv** [comment]
Interestingly, at 20m:23s the loud automated "3 2 1" announcement sounds almost as if it is coming through with no audio glitches, while the live MC "3 2 1" announcement simultaneously is very choppy.
Are those two countdowns coming from different sources?

**Comment by paulpv** [comment]
Same at 20m:53s when the match ends.
The automated voices sound clear.
Only the live MC voices sound choppy.

**Comment by paulpv** [comment]
It could just be an audio illusion; I would have to yt-dlp the video and view the audio frames to be certain.

**Comment by qwertychouskie** [comment]
The automated announcement sounds are coming from the overlay software AFAIK.

**Comment by Trouffman** [comment]
Closing as this is for old version. Please re open is this is still happening on latest release.
