### ISSUE TITLE
[Bug]: Cannot see my phone camera in the list

### ISSUE THREAD

**Issue by Serhioromano** [DistroAV/DistroAV#944]
### Operating System Version

Windows 10 x64

### OBS Version

30.0.2

### NDI Tools Version

5.6.0.0

### Describe the bug

I downloaded NDI HX Camera app in Google playmarket and launched a camera. If I use New tech NDI tools web camera I can see my phone camera and make it work as a webcam. But in OBS I installed plugin, when I select NDI source, in the list I do not see my phone camera. It is al on the same PC, so it is not a firewall.

### Screenshots

![2023-12-15_13-27-29](https://github.com/obs-ndi/obs-ndi/assets/650741/4b6c5eae-568b-4877-b524-b673de1ceca4)
![2023-12-15_13-28-21](https://github.com/obs-ndi/obs-ndi/assets/650741/f0512a9f-c611-48f5-95c8-4328830d7394)

**Comment by paulpv** [comment]
@Serhioromano Can you see it in NDI Studio Monitor?

**Comment by Serhioromano** [comment]
@paulpv yes i do. I see my Newtech NDI HX camera output everywhere but OBS.

**Comment by Trouffman** [comment]
This might be blocked by your firewall.

Try the following:
- set your network in "private network"

Of does not solve it
- run OBS as admin
