### ISSUE TITLE
[Bug]: Lots of laggey and stuck when pulling NDI HX3 H264

### ISSUE THREAD

**Issue by Philogag** [DistroAV/DistroAV#948]
### Operating System Version

Windows 10 Pro 21H2 with i7-11700K and RTX3070

### OBS Version

30.0.2

### NDI Tools Version

4.13.0

### Describe the bug

There will be a relatively uniform stuttering phenomenon in the video preview, which is especially obvious when the camera rotates the gimbal.
It only happend when camera output HX3 standerd video (H264 1080P60 CBR 62Mbps GOP=20 ). Using the same camera with lower encoder profile will not cause this problem.

+ Extra Tests
  + Using the same computer pull the same video source (HX3) with NDI Studio Monitor or VMIX. **Very smooth**
  + Using the same OBS version and plugin version on a MacBook(M1 Chip) and the same video source. **Very smooth**

I also noticed that the intervals between stuttering seemed to coincide with the GOP

### Steps to reproduce

1. Source -> Add -> NDI Source 
2. Select a camera which output NDI HX3
3. See the preview in OBS

### Additional context

I guess it is a issue of decoder. The bitrate is too high and it seems decode at CPU

I recorded some videos for compare, but I don’t know where to upload them

**Comment by Trouffman** [comment]
Thank you for reporting this.

Please update to the latest version and test again.

Usually when we have this issue, reconnecting the camera does help.
