### ISSUE TITLE
[Bug]: Black Screen on Windows 11 from SteamOS OBS NDI

### ISSUE THREAD

**Issue by Articade** [DistroAV/DistroAV#950]
### Operating System Version

Windows 11

### OBS Version

30.0.2 (64 bit) (windows and steamos) 

### NDI Tools Version

5.6.0 (windows and steamos)

### Describe the bug

I installed obs-ndi from the discovery store after installing OBS from it as well.  I can set everything up on both ends, but when choosing any NDI (Main, Program, or dedicated), only a black screen appears.  I disabled windows firewall and ensured media sharing on my network adapter was enabled on windows.  Not sure how to fix.

**Comment by paulpv** [comment]
@Articade Can `NDI Studio Monitor` see the stream?

**Comment by Articade** [comment]
> @Articade Can `NDI Studio Monitor` see the stream?

Just tested, it cannot.  It works when I do the opposite, Windows to my SteamOS.  Not sure if there if its something I have to change in SteamOS?

**Comment by Articade** [comment]
Also to add, it sees it listed, but only a black screen is showing.

**Comment by paulpv** [comment]
> it sees it listed, but only a black screen is showing.
"it" being NDI Studio Monitor, or obs-ndi?

If the official `NDI Studio Monitor` doesn't work, then obs-ndi probably also won't.
Try getting Studio Monitor working.
Check your Windows firewall and Ethernet on Private network.
Do let us know if you get it fixed.
