### ISSUE TITLE
[Bug]: Only local NDI sources in dropdown list

### ISSUE THREAD

**Issue by patmu** [DistroAV/DistroAV#953]
### Operating System Version

Windows 11 (release: 23H2; revision: 2861; 64-bit)

### OBS Version

 OBS 30.0.2 (64-bit, windows)

### NDI Tools Version

4.13.0

### Describe the bug

After starting OBS, only NDI sources from the same computer are available for selection in the dropdown list. There are no other  running NDI sources on the network available in the dropdown list.

### Steps to reproduce

1. Add NDI Source
2. Check available sources in "source name" dropdown list

### Expected behavior

All available sources shoud be displayed in the dropdown list.

### Additional context

NDI Studio Monitor, which is running on the same computer as OBS, shows all available sources. So there is no firewall blocking.

What I see in the obs plugin directory: almost every plugin has a pdb file with the same filename as the dll. This is not the case for obs-ndi.dll. obs-ndi.pdb is missing. Could this be the reason for the issue?

Computer has fixed IPv4 address set, IPv6 is disabled. Changing to DHCP for both doesn't help.

Workaround 1)
When I start OBS explicitly with administrator permissions, then all the sources are available. 

Workaround 2)
Add remote computers in access manager. After doing this, the sources from this host are in OBS available s well.

**Comment by patmu** [comment]
[2024-01-05 13-46-25.txt](https://github.com/obs-ndi/obs-ndi/files/13842197/2024-01-05.13-46-25.txt)

**Comment by patmu** [comment]
Log-File from OBS start as administrator (right click on the icon -> run as administrator):
[2024-01-05 13-49-01.txt](https://github.com/obs-ndi/obs-ndi/files/13842222/2024-01-05.13-49-01.txt)

**Comment by BarryCarlyon** [comment]
Try adding OBS to your firewall allow list and see if that resolves it

**Comment by patmu** [comment]
Thank you for the idea. Tried it, and success :-)

Looks like NDI plugin installer should add OBS to the firewall allow list by default.

**Comment by tmushy** [comment]
Thanks for everyone fixing my issue. Run as administrator was the solution
