### ISSUE TITLE
[Bug]: Windows Build Error: "The term 'iscc' is not recognized as a name of a cmdlet"

### ISSUE THREAD

**Issue by DavidXenakis** [DistroAV/DistroAV#968]
### Operating System Version

Windows 10

### CPU

Ryzen 5

### OBS Version

Building from latest source, 30.0.2

### OBS Installation Method

From srouce

### OBS-NDI Version

Latest

### OBS-NDI Installation Method

From source

### NDI Version

5.6.0.0

### Describe the bug

I'm having trouble building obs-ndi on my windows 10 machine. Following the README, I ran:
`.github/scripts/Build-Windows.ps1 && .github/scripts/Package-Windows.ps1 -BuildInstaller`

The Package-Windows.ps1 fails with this error:
```
-- Installing: C:\Users\David Xenakis\projects\obs-studio\plugins\obs-ndi/release/RelWithDebInfo/data/obs-plugins/obs-ndi/locale/zh-CN.ini
    =>   Check Windows build requirements
     >   Found dependency cmake as C:\Program Files\CMake\bin\cmake.exe
     >   Installing package innosetup 
Found an existing package already installed. Trying to upgrade the installed package...
No available upgrade found.
No newer package versions are available from the configured sources.
    =>   Packaging obs-ndi...
    =>   Creating InnoSetup installer...
Write-Error: C:\Users\David Xenakis\projects\obs-studio\plugins\obs-ndi\.github\scripts\Package-Windows.ps1:96:1
Line |
  96 |  Package
     |  ~~~~~~~
     | The term 'iscc' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the    
     | path is correct and try again.
```

**Comment by paulpv** [comment]
```
> dir /s c:\iscc.exe
```
Check that that is in your PATH

**Comment by paulpv** [comment]
Glad that worked for you...but that does not make any sense.

https://github.com/obs-ndi/obs-ndi/blob/master/.github/scripts/Package-Windows.ps1 defines `function Package {`
https://github.com/obs-ndi/obs-ndi/blob/master/.github/scripts/Package-Windows.ps1#L28
and then calls that function
https://github.com/obs-ndi/obs-ndi/blob/master/.github/scripts/Package-Windows.ps1#L96

I don't know what changing `Package` (what calls the defined `Package` method) to `Get-Package` would make the `The term 'iscc' is not recognized as a name of a cmdlet` error go away.

**Comment by Trouffman** [comment]
I ended up having the same issue when building on my side as well.

This is mostly the PATH update issue.

The first time you run the script it will install Innosetup. But the environment variables (while being set) are not reloaded and iscc will not be found.

Relaunching the command will not solve it. 

Technically re-launching a new powershell window should work but it's not.

Killing/ restarting explorer did not help either.

Rebooting did help in 1 system but not the other.

Had to remove, reinstall, reboot (outside of the script itself).

Something to check : is this an issue when using the winget / get package install only ?

**Comment by Trouffman** [comment]
This seems to be because of an outdated script.

This is different in the source template:
https://github.com/obs-ndi/obs-ndi/blob/master/.github%2Fscripts%2Futils.pwsh%2FInstall-BuildDependencies.ps1#L37

Suggestions : update with the upstream data.

**Comment by Trouffman** [comment]
This has not been happening for month now. Closing :)
