### ISSUE TITLE
[Bug]: obs-ndi missing updates on low-fps connections

### ISSUE THREAD

**Issue by schuettecarsten** [DistroAV/DistroAV#970]
### Operating System Version

Windows 10

### OBS Version

30.0.2

### OBS Installation Method

exe

### OBS-NDI Version

4.13.0

### OBS-NDI Installation Method

exe

### NDI Version

5.6.0.0

### Describe the bug

I use the NDI Screen Capture to capture Powerpoint presentation on a presentation PC. OBS is running on a second PC. The setup works as expected when using NDI Studio Monitor on the OBS PC. I use a NDI source to import this NDI source to OBS. Now, OBS often misses updates when the next Powerpoint slide is shown. Sometimes the screen gets updated, sometimes not.

I think this is caused because NDI Screen Capture does not use a stable fps rate but only sends single, full-screen updates when the screen changes. If no updates are there, no NDI data is sent, which is by design. If you use vMix Screen Capture tool it will show you the actual FPS rate, which is often 0 if nothing must be updated.

I've tested a lot of combinations with NDI source settings in OBS, validated the network, used other LAN cables, other router, even tried Wifi and I am really sure that this is not an NDI/network/PC issue. Screen updates work in NDI Studio Monitor but not reliable in OBS.

**Comment by Trouffman** [comment]
Please use the latest version and select the behavior to be "always connected".
