### ISSUE TITLE
Your Doc Link for OS X Install is not working

### ISSUE THREAD

**Issue by daveschinkel** [DistroAV/DistroAV#972]
this link does nothing, doesn't open anything
MacOS: http://ndi.link/NDIRedistV5Apple

**Comment by thpryrchn** [comment]
That is basically a link shortener to https://downloads.ndi.tv/SDK/NDI_SDK_Mac/libNDI_for_Mac.pkg

Brave browser blocks it. It is now saved on the wayback machine.

Also, if you have NDI tools installed, you can just paste this in your terminal, and use NDI from there: 
`ln -s /Applications/NDI\ Video\ Monitor.app/Contents/Frameworks/libndi_advanced.dylib /usr/local/lib/libndi.dylib`
That way you don't need an extra thing installed if you have NDI tools already.

**Comment by dschinkel** [comment]
ah ok, I'm using brave thanks.

**Comment by paulpv** [comment]
> Also, if you have NDI tools installed, you can just paste this in your terminal, and use NDI from there: `ln -s /Applications/NDI\ Video\ Monitor.app/Contents/Frameworks/libndi_advanced.dylib /usr/local/lib/libndi.dylib` That way you don't need an extra thing installed if you have NDI tools already.

@Trouffman we should add this as an option to our Installation or Troubleshooting wikis

**Comment by Trouffman** [comment]
We added the alternative download link in installation. This will be easier to manage and support over longer time.

The issue is at the vore of the NDI.link domain not liking the https. There is a support ticket about this with NDI.
