### ISSUE TITLE
[Bug]: OBS-ndi changes scene name arbitrarily

### ISSUE THREAD

**Issue by wpl-test** [DistroAV/DistroAV#974]
### Operating System Version

Windows11

### OBS Version

29.1.3～30.0.2

### OBS Installation Method

exe

### OBS-NDI Version

4.12.0～4.13.0

### OBS-NDI Installation Method

exe

### NDI Version

5.6.0.0

### Describe the bug

If scene names overlap between different scene collections, the scene names will be changed automatically.
This issue does not occur in safe mode, so after verifying it, it does not occur if "NDI Output settings" is turned off.

### Steps to reproduce the problem

1. Create scene “test” in scene collection “01”
![スクリーンショット 2024-02-06 153315](https://github.com/obs-ndi/obs-ndi/assets/159099855/94a557a6-8342-48e7-bf86-ed0c522610fc)
2. Create scene “test” in scene collection “02”
![スクリーンショット 2024-02-06 153411](https://github.com/obs-ndi/obs-ndi/assets/159099855/4d87cdbf-3ddf-43c7-934a-1b2d2cd7664f)
3.  When you return to scene collection “01”, scene “test” has been changed to “test 2”.
![スクリーンショット 2024-02-06 153646](https://github.com/obs-ndi/obs-ndi/assets/159099855/be0f99a5-48d5-4ca8-95c3-134ae666c954)

If "NDI Output settings" is turned off, this problem will not occur.
![スクリーンショット 2024-02-06 154010](https://github.com/obs-ndi/obs-ndi/assets/159099855/109815ec-41d2-48b6-b3db-c6b4e4c808eb)
![スクリーンショット 2024-02-06 154219](https://github.com/obs-ndi/obs-ndi/assets/159099855/b72c098f-ea8d-4977-81e3-eade8c78f80f)
![スクリーンショット 2024-02-06 154243](https://github.com/obs-ndi/obs-ndi/assets/159099855/b587f4db-faad-420d-b396-8d5fe41d96e7)

**Comment by BitRate27** [comment]
This is because the COLLECTION_CLEANUP event is not acted on in preview_output.cpp:
Add this case in the on_preview_scene_changed callback:
	case OBS_FRONTEND_EVENT_SCENE_COLLECTION_CLEANUP:
		obs_source_release(ctx->current_source);
		ctx->current_source = nullptr;
                 break;
Because we don't release the source, the previous collection isn't cleaned up. When a new collection is selected with a duplicate scene name, it thinks there is already a scene with that name.

**Comment by Trouffman** [comment]
To test and confirm behavior:

Is the behavior reported identical when "streaming" or "recording" is used instead of the "NDI output" ?

**Comment by BitRate27** [comment]
This bug was fixed by this commit: [5ff623](https://github.com/DistroAV/DistroAV/commit/fb4ef18e8f354d21805537e1cc601d88545ff623) and is in the latest release. 
Please close this issue.
