### ISSUE TITLE
ndi not work to see other pc on obs [Bug]: 

### ISSUE THREAD

**Issue by Peterl627** [DistroAV/DistroAV#980]
### Operating System Version

windows 11

### OBS Version

30.0.2

### OBS Installation Method

exe

### OBS-NDI Version

4.13.0

### OBS-NDI Installation Method

exe

### NDI Version

5.6.0.0

### Describe the bug

I am trying to see the other pc for livestream. it worked 2 weeks ago but then all of a sudden it is not working not sure when I updated obs. Live steam on windows trying o get conduct from mac. I believe I downloaded all the plugins. I can get NDI on obs but the other pc dos not show up.

**Comment by RayneYoruka** [comment]
Firewall?

**Comment by Peterl627** [comment]
firewall is open

**Comment by RayneYoruka** [comment]
Are they on the same network?, are they both on ethernet? does NDI tools pick the signal on the recieving end?

**Comment by Peterl627** [comment]
same network wifi, no it doesn't show up on ndi tools either

**Comment by RayneYoruka** [comment]
Then this might be network isolation. Which it's a security measure a lot of routers toggle by default. Please investigate.

**Comment by Peterl627** [comment]
I don't know why it just happened it was working fine 2 weeks ago; last week end it didn't work anymore.

**Comment by RayneYoruka** [comment]
You will need to vetify with NDI studio monitor.

Otherwise it might just be firewall. This are the ports used by NDI:
https://ndi.tv/tools/education/networking/best-practices/networking-best-practice/
