### ISSUE TITLE
[Bug]: Transparency only works if Latency Mode = Normal (not on Low nor Lowest)

### ISSUE THREAD

**Issue by Yonatan-Mijelshon** [DistroAV/DistroAV#983]
### Operating System Version

Windows 10

### CPU

I7 11700K

### GPU

3060Ti

### NDI Devices

ZoomISO on Mac M1 

### OBS Version

30.0.2

### OBS Installation Method

.exe

### OBS-NDI Version

4.13.0

### OBS-NDI Installation Method

exe

### OBS Log [URL]

https://obsproject.com/logs/rYODUZqUcQjGkhGI

### NDI Version

5.5.4.0

### Describe the bug

ZoomISO V2 provides a transparent background image over NDI when no actual camera image is detected. It used to be the case until OBS-NDI 4.11.0 that this feature worked for both Latency Mode = Normal and = Low (experimental). Now, the transparency ONLY works in Latency Mode = Normal (safe), and shows a black box instead in = Low and = Lowest.   

### Steps to reproduce the problem

1. Open ZoomISO on a Mac M series, join a meeting, enable Output Engine (needs to be made co-host), switch Video Loss Mode to TRANSPARENT and enable output 1, mode = PARTICIPANT, selection = *someone with their camera ON* (It can be "yourself"), output type = NDI
2. Watch the NDI stream by creating a OBS NDI source in OBS on a local computer and selecting ZoomISO 1 as source. Put ANOTHER source (can be a solid color) in a bottom layer on the same scene
3. Toggle camera on and off on the participant and watch as the background color appears and disappears on OBS.
4. Then, change the OBS NDI source settings to either Low or Lowest Latency and do the same experiment

### Expected behavior

Same as before. The transparency working equally on all latency settings

**Comment by RayneYoruka** [comment]
it's known and it's supposed to be fixed by next release (4.14)
