### ISSUE TITLE
[Bug:] ndi LAN drops

### ISSUE THREAD

**Issue by DieDana89** [DistroAV/DistroAV#988]
### Operating System Version

Windows 10

### OBS Version

30.0.2

### OBS Installation Method

Exe

### OBS-NDI Version

4.13.1 with ndi 5 runtime

### OBS-NDI Installation Method

Exe

### NDI Version

4.13.1 with ndi 5 runtime

### Describe the bug

Hello, I have the problem that the transmission from the gaming PC is stuttering. The internet transmission briefly drops to 8MBit/s and then increases again. This of course causes the streaming PC to stutter.

translated with Google translator

**Comment by Jaybonaut** [comment]
I have never seen this happen, perhaps it is your router/gateway?

**Comment by RayneYoruka** [comment]
Are you using ethernet?

**Comment by Trouffman** [comment]
Step to test / confirm
- Connect both computer only with ethernet cable (disable wifi)
- Confirm both are on the same network (not over internet)
- Confirm both PC are Win 10 with NDI 4.13.1 and NDI 5

**Comment by paulpv** [comment]
@DieDana89 still happening, or can we close this ticket?

**Comment by DieDana89** [comment]
Yes, the problem still exists, but it seems to be caused by the built-in LAN card on the motherboard. It is no longer used and is deactivated, but it seems to be throttling the transfer speed. It is a Killer LAN card.

**Comment by RayneYoruka** [comment]
Killer network cards are known to have performance issue.. I've avoided them as much as possible simply because of this..
