### ISSUE TITLE
[Bug]: NDI HX2 + HX3 Stuttering MacOS

### ISSUE THREAD

**Issue by jahaddow** [DistroAV/DistroAV#991]
### Operating System Version

MacOS 14.3.1

### CPU

M1 Max

### GPU

M1 Max

### NDI Devices

Hardware encoder

### OBS Version

29.1.3, 30.0.2, 30.1.1

### OBS Installation Method

DMG4.

### OBS-NDI Version

4.13.1

### OBS-NDI Installation Method

PKG

### NDI Version

5.6.1

### Describe the bug

Extensive testing on has shown that HX2 and HX3 sources seem to stutter at regular intervals (around every 15-20s in H264). When running HEVC the stutter is much worse (virtually constant). However, when running HX (1) in H264 there is absolutely no stutter, even in 4k sources.

Multiple Mac's and different 2.5g networks have been tested with the same results. The source is 30p and the OBS canvas is 30p. Full NDI sources (even up to 4k60 250mbps) do not have this issue on the same machine and networks.  We have tried both h/w and cpu decoding and all latency options to no avail. NDI Virtual Monitor does not present the same symptoms, it seems to only occur in OBS.

**Comment by Trouffman** [comment]
This seems to be a very difficult to diagnose issue. Could you share a clean OBS log of one of the machine?
